<?php

class Gka_InternalPayId_Model_System_Config_Backend_Ident extends Mage_Core_Model_Config_Data
{


    protected function _beforeSave() {
        $value     = $this->getValue();

        $pattern = "/[^a-z]/iu";
        if(preg_match($pattern,$value)){
            Mage::throwException(Mage::helper('internalpayid')->__('Buchungsliste Schlüssel f. internes Kassenzeichen is invalid! [a-zA-Z]'));
        }

        return parent::_beforeSave(); // TODO: Change the autogenerated stub
    }


}
