<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 * @var Dwd_Stationen_Block_Catalog_Product_View_Abstract $this
 */
?>

<?php if ($this->hasStationen()):?>
<div id="map" class="map_size"></div>
<script type="text/javascript">
var rssUrl       = "<?php echo $this->getRssUrl(); ?>";
var jsonUrl      = "<?php echo $this->getGeoJsonUrl(); ?>";
var marker_klein = "<?php echo $this->getSkinUrl(); ?>geomap/images/map2_point4.gif";
var marker_gross = "<?php echo $this->getSkinUrl(); ?>geomap/images/map2_point4.png";
</script>
<?php // Polyfill for Object.assign its used by ol3-popup ?>
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=Object.assign"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>geomap/js/ol.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>geomap/js/ol3-popup.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>geomap/js/ol3pz.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>geomap/js/map_plugin.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl(); ?>geomap/js/init.js"></script>
<?php endif;?>