<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */


/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div>
<?php if ($product->isSaleable()): ?>
    <a href="javascript:void(0);"
       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
       onclick="addWItemToCartCustom(<?php echo $item->getId()?>, false);"
       class="egov-cart"> </a>
<?php else: ?>
    <?php if ($product->getIsSalable()): ?>
        <p class="availability in-stock">
            <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value"><?php echo $this->helper('catalog')->__('In stock') ?></span>
        </p>
    <?php else: ?>
        <p class="availability out-of-stock">
            <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value"><?php echo $this->helper('catalog')->__('Out of stock') ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <a class="egov-pencile"
       href="<?php echo $this->getItemConfigureUrl($item) ?>"
       title="<?php echo $this->__('Edit') ?>"> </a>
<?php endif ?>
<?php foreach($this->getSortedChildren() as $childName):?>
    <?php echo $this->getChildHtml($childName, false);?>
<?php endforeach;?>
    <div class="mobile-small-remove">
        <a href="<?php echo $this->getItemRemoveUrlCustom($this->getItem(), false); ?>"
           onclick="return confirmRemoveWishlistItem();"
           title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"
           class="remove egov-delete"> </a>    
    </div>
</div>
