<div class="entry-edit-head entry-edit">
     <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('virtualgeo')->__('Selection Tools') ?></h4>
</div>



<script>
function init_db_nodes() {
<?php
foreach ($this->getNodes() AS $node){
	if($node->getParent()){
		$parent = 'node_'.$node->getParent();
	}
	else{
		$parent = '"root"';
	}
	echo "    var node_".$node->getId()." = nodeOptions.add(".$node->toJson()."," . $parent . ");\n";
}
?>
	nodeOptions.open_all();
}
</script>
