<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php /* @var $this Mage_Catalog_Block_Product_View_Options_Type_Select */ ?>
<?php $_option = $this->getOption(); ?>

<dt class="option-box option-block type-<?php echo $_option->getType(); ?>">
    <label>
        <?php echo  $this->escapeHtml($_option->getTitle()) ?>
        <?php if ($_option->getIsRequire()) echo '<span class="required"> *</span>' ?>
    </label>
    <span class="option-box-elements">
        <?php echo $this->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_RADIO || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
</dt>
