<?php
/**
 * Zusatz Info-Block für Kundeninformationen
 *
 * @category       	Egovs_Ready_Block_Catalog_Product_Price
 * @package			Egovs
 * @name           	Egovs_Ready_Block_Catalog_Product_Price
 * @author 			Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright      	Copyright (c) 2010 - 2017 B3 IT Systeme GmbH - http://www.b3-it.de
 * @license        	http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 *
 */

/**
 * @var $this Egovs_Ready_Block_Catalog_Product_Price_Info
 * @see Egovs_Ready_Block_Catalog_Product_Price
 * @see Egovs_Ready_Block_Catalog_Product_Price::_toHtml()
 */

$shippingCostUrl = Mage::helper( 'egovsready' )->getShippingCostUrl();
$showShippingLink = $this->getShowShippingLink();
$_taxPrefix = 'Incl.';
if ( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_EXCLUDING_TAX ) {
    $_taxPrefix = 'Excl.';
}
$_taxPostfix = $this->getFormattedTaxRate() === true ? 'Tax' : '% Tax';
$_productType = $this->getProduct()->getTypeId();
?>

<?php if ($_productType != 'eventbundle'): ?>

<?php if (!$this->getExcludeContainer()): ?>
    <span class="tax-details">
<?php endif; ?>
<?php if ($this->getFormattedTaxRate() !== false): ?>
    <?php if ($this->getFormattedTaxRate() === 0): ?>
        <?php echo $this->__( 'Tax Free' ); ?>
    <?php else: ?>
        <?php echo $this->__( "$_taxPrefix $_taxPostfix", $this->getFormattedTaxRate() ) ?>
    <?php endif ?>
    <?php if ( $showShippingLink && (!empty( $shippingCostUrl ) || $this->getWithoutShippingCostsText())): ?>
        <?php if (!$this->getExcludeContainer()): ?>
            <span class="tax-separator">,&nbsp;</span>
        <?php else: ?>
            ,&nbsp;
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
<?php if (!$this->getExcludeContainer()): ?>
    </span>
<?php endif; ?>
<?php if( !empty( $shippingCostUrl ) && $showShippingLink ): ?>
	<?php
        if ( $this->getIsIncludingShippingCosts() ) {
        	$_sIncludingShippingCosts = 'incl.';
        } else {
        	$_sIncludingShippingCosts = 'excl.';
        }
    ?>
    <?php if (!$this->getExcludeContainer()): ?>
        <span class="shipping-cost-details"><?php echo $this->__($_sIncludingShippingCosts.' <a href="%s">Shipping Cost</a>', $shippingCostUrl ) ?></span>
    <?php else: ?>
        <?php echo $this->__("$_sIncludingShippingCosts Shipping Cost") ?>
    <?php endif; ?>
<?php else: ?>
    <?php if ( $showShippingLink && ($wscText = $this->getWithoutShippingCostsText())): ?>
        <?php if (!$this->getExcludeContainer()): ?>
            <span class="shipping-cost-details"><?php echo $this->__($wscText) ?></span>
        <?php else: ?>
            <?php echo $this->__($wscText) ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
<?php if ($this->getDisplayProductWeight()): ?>
        <br/> (<?php echo $this->__('Shipping Weight %s', $this->getFormattedWeight()) ?>)
<?php endif; ?>

<?php endif; // End if is not EventBundle ?>