<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product cms template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="product-view">
    <div class="product-essential">
            
            <div id="product-base-block">
                <div class="product-img-box">
                    <?php echo $this->getChildHtml('thumbnail'); ?>
                </div>

                <div class="product-shop">
                    <div class="product-name">
                        <span class="name-prefix"><?php echo $_product->getNamePrefix() ?></span>
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h1>
                    </div>

                    <div id="details-block">
                        <div class="product-sku">
                            <?php echo $this->__('SKU') . ': ' . $_helper->productAttribute($_product, $this->htmlEscape($_product->getSku()), 'sku'); ?>
                        </div>
                       

                        <div class="extra-info">
                            <?php echo $this->getReviewsSummaryHtml($_product, 'default', false); ?>
                            <?php echo $this->getChildHtml('product_type_availability'); ?>
                        </div>

                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php echo $this->getChildHtml('extrahint') ?>

                      <?php if ($_product->getShortDescription()):?>
                        <div class="short-description">
                            <div class="std">
                                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                            </div>
                        </div>
                      <?php endif;?>


                     
                    </div>
                </div>
            </div>

            <?php echo $this->getChildHtml('media'); ?>

            <div class="product-additional-information">
                <?php //echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php //echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
            </div>

         

            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>

            <div class="product-collateral toggle-content tabs">
              <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                <dl id="collateral-tabs" class="collateral-tabs">
                  <?php foreach ($detailedInfoGroup as $alias => $html):?>
                    <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
                    <dd class="tab-container">
                        <div class="tab-content"><?php echo $html; ?></div>
                    </dd>
                  <?php endforeach;?>
                </dl>
              <?php endif; ?>
            </div>
    </div>


    <?php echo $this->getChildHtml('product_additional_data') ?>

  

</div>

