<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product components template
 *
 * @see Bkg_VirtualGeo_Block_Catalog_Product_View_Virtualgeo
 */
/** @var $this Bkg_VirtualGeo_Block_Catalog_Product_View_Virtualgeo */
?>
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var skipTierPricePercentUpdate = true;
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
        var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
        var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
        var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
        var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
        //]]>
    </script>
<?php endif; ?>
<style  type="text/css" >

.ui-controlgroup > .ui-helper-hidden-accessible {
  position: absolute !important;
}

#select-vg-menu > .ui-menu-item {
  line-height: normal;
}
.toogleModeCtrl {
	top: 0em;
}
.toogleSelectCtrl {
	top: 0em;
	left: 5.5em;
}
</style>
<pre>
<?php 
    /**
     * @var int $cid
     */
    $cid = Mage::getSingleton('customer/session')->getCustomerId();
?>
</pre>
<script type="text/javascript">
    var strPrefixSelected = '<?php echo $this->__('Selected Options'); ?>:';
    <?php if ($this->getComposit()): ?>

    <?php
        echo Mage::helper("virtualgeo/data")->getProj4();
    ?>

	var toolsfunc = function(epsg) {
      var tools = [];
      <?php
        $tools = $this->getSelectionTools();
        foreach ($tools as $tool) {
            /**
             *
             * @var Bkg_Viewer_Model_Composit_Selectiontools $tool
             */
            echo ($tool->getOpenLayers("epsg"));
        }
        ?>

      <?php if(Mage::helper('core')->isModuleEnabled("Bkg_Shapefile") && isset($cid)): ?>
	  url = baseUrl + "index.php/shapefile/file/files/id/" + <?php echo $cid; ?>;
	  $j.ajax(url, {
		async: false,
		success: function(files) {
  			fileIdx = 0;
			files.forEach(function(file) {
  	  			filesource = new ol.source.Vector({
  					format: new ol.format.WKT(),
  					loader: function(extent, resolution, projection) {
  	  					var self = this; 
  						url = baseUrl + "index.php/shapefile/file/shapes/id/" + file['id'];
  	  					$j.ajax(url, {
  	  						success: function(shapes) {
  	  	  						dataProj = ol.proj.get("EPSG:" + file['epsg_code']);
  	  	  						if (ol.proj.equivalent(dataProj, projection)) {
      	  	  						shapes.forEach(function(el) {
          	  	  						self.addFeatures(self.getFormat().readFeatures(el['shape'], {
          	  								dataProjection: dataProj,
          	  								featureProjection: projection
          	  							}));
      	  	  						});
  	  	  						}
  	  						}
  	  					});
  					}
				});
  				tools.push(new ol.layer.Vector({
  					title: file['name'],
  					visible: false,
  					source: filesource,
  					style: new ol.style.Style({
  	  					stroke: new ol.style.Stroke({
  	  	  					color: 'green',
  	  	  					width: 2
  	  					})
  	  				}),
  					zIndex: 500 + fileIdx
  				}));
  				fileIdx += 1;
			});
		}
	  });
      <?php endif; ?>
      return new ol.layer.Group({
        //title: 'Tools',
        layers: tools
      });
	}

	function _kachelFunc(f) {

    	kachelSource = null;
    	kachelVector = null;

    	struct = $j("input:checked[data-id='virtualgeo-components-structure[]']");
    	if (struct.length > 0) {
    		structid = struct.val();
    		georef = $j("input:checked[data-id='virtualgeo-components-georef[]']");
    		if (georef.length > 0) {
    			geocode = georef.attr("data-code");

    	        // the url should already support that epsg
    			url = baseUrl + "index.php/virtualgeo/map/structurLayer/id/" + structid + "/georef/" + geocode;
    			$j.ajax(url, {
    				//async: false,
        			success: function(str) {
            			//console.log(str);
            			if (!!str) {
            				kachelSource = new ol.source.Vector({
                		    	format: new ol.format.WFS({gmlFormat: new ol.format.GML3()}),
                		    	url: str
                			});
                			kachelVector = new ol.layer.Vector({
                	    	  source: kachelSource,
                	    	  zIndex: 1000
                	    	});
                			f.call(null, kachelVector);
            			}
        			}
    			}); 
    		}
    	}
    }
    var _layerFunc  = function(epsg) {
    	<?php echo $this->getComposit()->getOpenLayer("epsg"); ?>
    	return layers_0;
	};

	<?php endif; ?>
</script>

<div id="virtualgeo">
<?php
$blocks = $this->getBlocksFromComponents();
foreach ($blocks AS $blockname) {
    $block = $this->getComponentsBlock($blockname);
	if($block) {
        echo $block->toHtml();
	}
}
?>

</div>

<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
