<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product components template
 *
 * @see Bkg_VirtualGeo_Block_Catalog_Product_View_Virtualgeo
 */
/** @var $this Bkg_VirtualGeo_Block_Catalog_Product_View_Virtualgeo */
?>
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var skipTierPricePercentUpdate = true;
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
        var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
        var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
        var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
        var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
        //]]>
    </script>
<?php endif; ?>
<style  type="text/css" >

.ui-controlgroup > .ui-helper-hidden-accessible {
  position: absolute !important;
}
.ui-selectmenu-menu > ul > li.ui-menu-item {
  line-height: normal;
}
.toogleModeCtrl {
	top: 0em;
}
.toogleSelectCtrl {
	top: 0em;
	left: 5.5em;
}
</style>
<pre>
<?php 
    /**
     * @var int $cid
     */
    $cid = Mage::getSingleton('customer/session')->getCustomerId();
    ;
?>
</pre>
<script type="text/javascript">
    var strPrefixSelected = '<?php echo $this->__('Selected Options'); ?>:';
    <?php if ($this->getComposit()): ?>

	var pcode = "<?php echo $_product->getData('product_code'); ?>";
    <?php echo Mage::helper("virtualgeo/data")->getProj4(); ?>

    var shapesfunc = function(epsg) {
        var layers = [];
    	<?php if(Mage::helper('core')->isModuleEnabled("Bkg_Shapefile") && isset($cid)) :?>
    	files = <?php echo json_encode(Mage::helper("bkg_shapefile")->getFilesByUser($cid)); ?>;
        fileIdx = 0;
		files.forEach(function(file) {
			if (epsg != file['epsg_code']) {
				return;
			}
  			layers.push(new ol.layer.Vector({
				title: file['name'],
				layer_id: file['id'],
				visible: false,
				source: new ol.source.Vector({
					format: new ol.format.WKT(),
					loader: function(extent, resolution, projection) {
	  					var self = this; 
						url = baseUrl + "index.php/shapefile/file/shapes/id/" + file['id'];
	  					$j.ajax(url, {
	  						success: function(shapes) {
	  	  						dataProj = ol.proj.get("EPSG:" + file['epsg_code']);
      	  						shapes.forEach(function(el) {
          	  						list = self.getFormat().readFeatures(el['shape'], {
      	  								dataProjection: dataProj,
      	  								featureProjection: projection
      	  							});
      	  							list.forEach(function(l) {
          	  							l.setId(el['id']);
          	  						});
      	  	  						self.addFeatures(list);
      	  						});
	  						}
	  					});
					}
				}),
				style: shapeStyle,
				zIndex: file['zIndex']
			}));
			fileIdx += 1;
		});
        <?php endif; ?>
        return new ol.layer.Group({
            //title: 'Tools',
            layers: layers
        });
    }
    
	var toolsfunc = function(epsg) {
      var tools = [];
      <?php
        $tools = $this->getSelectionTools();
        foreach ($tools as $tool) {
            /**
             *
             * @var Bkg_Viewer_Model_Composit_Selectiontools $tool
             */
            echo ($tool->getOpenLayers("epsg"));
        }
        ?>
      return new ol.layer.Group({
        //title: 'Tools',
        layers: tools
      });
	}

	function _kachelFunc(f) {

		// reset the source and vector
    	kachelSource = null;
    	kachelVector = null;

    	struct = $j("input:checked[data-id='virtualgeo-components-structure']");
    	if (struct.length > 0) {
    		structid = struct.attr("data-entity-id");
    		georef = $j("input:checked[data-id='virtualgeo-components-georef']");
    		if (georef.length > 0) {
    			geoepsg = georef.attr("data-epsg");

    	        // the url should already support that epsg
    			url = baseUrl + "index.php/virtualgeo/map/structurLayer/id/" + structid + "/geoepsg/" + geoepsg + "/procode/" + pcode;
    			$j.ajax(url, {
    				beforeSend: incLoading,
    				complete: decLoading,
    				//async: false,
        			success: function(data) {
        				if (!!data.url) {
            				kachelSource = new ol.source.Vector({
                		    	format: new ol.format.WFS({gmlFormat: new ol.format.GML3()}),
                		    	url: data.url,
                		    	loader: ajaxLoader
                			});

                			// need to update the ID values for them
                			// need to use feature id attribute if able
                			if (!!data.fid) {
                    			kachelSource.once('change', function(e) {
                        			e.target.getFeatures().forEach(function(y) {
                               			y.setId(y.get(data.fid));
                        			});
                        		});
                			}

                			kachelVector = new ol.layer.Vector({
                    		  layer_id: data.id,
                	    	  source: kachelSource,
                	    	  zIndex: kachelZIndex
                	    	});
                			f.call(null, kachelVector);
            			}
        			}
    			}); 
    		}
    	}
    }
    var _layerFunc  = function(epsg) {
    	<?php echo $this->getComposit()->getOpenLayer("epsg"); ?>
    	return layers_0;
	};

	<?php endif; ?>
</script>

<div id="virtualgeo">
<?php
$blocks = $this->getBlocksFromComponents();
foreach ($blocks AS $blockname) {
    $block = $this->getComponentsBlock($blockname);
	if($block) {
        echo $block->toHtml();
	}
}
?>

</div>

<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
