<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product components template
 *
 * @see Bkg_VirtualGeo_Block_Catalog_Product_View_Virtualgeo
 */
/* @var $this Bkg_VirtualGeo_Block_Catalog_Product_View_Virtualgeo */
?>
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var skipTierPricePercentUpdate = true;
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
        var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
        var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
        var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
        var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
        //]]>
    </script>
<?php endif; ?>

<script type="text/javascript">
    var strPrefixSelected = '<?php echo $this->__('Selected Options'); ?>:';
    <?php if ($this->getComposit()): ?>
    var _layerFunc  = function() {
    	<?php echo $this->getComposit()->getOpenLayer(); ?>
    	return layers;
	};
	<?php endif; ?>
</script>

<div id="virtualgeo">
<?php
$blocks = $this->getBlocksFromComponents();
foreach ($blocks AS $blockname) {
    $block = $this->getComponentsBlock($blockname);
	if($block) {
        echo $block->toHtml();
	}
}
?>
<h3>
Map
</h3>
<div class="virtualgeo-map" id="virtualgeo-openlayer">
</div>
</div>

<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
