<?php

/**
 * Infoblock für Zahlungen per Vorkasse
 *
 * @category   	Egovs
 * @package    	Egovs_BankPayment
 * @author 		Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright  	Copyright (c) 2011-2019 B3 IT Systeme GmbH - http://www.b3-it.de
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @see Mage_Payment_Block_Info
 */
/** @var $this Egovs_BankPayment_Block_Info */
?>
<div class="block-content">
    <?php echo $this->getMethod()->getTitle(); ?><br />
    <?php if ($this->showBankDetails()): ?>
	    <?php if ($this->getAccountHolder()
	    		  || $this->getAccountNumber()
	    		  || $this->getSortCode()
	    		  || $this->getBankName()
	    		  || $this->getIBAN()
	     ): ?>
	    	<div id="bankpayment_account_info" style="font-style: italic;"><?php echo $this->__('Account info'); ?></div>
	    <?php endif;?>
	    <table>
	        <tbody>
	        <?php if ($this->getBankName()): ?>
	            <?php echo '<tr id="bankpayment_bank_name"><td><label>' . $this->__('Bank name') . '</label>:</td><td>' . $this->getBankName() . '</td></tr>'; ?>
	        <?php endif; ?>
	        <?php if ($this->getAccountHolder()): ?>
	            <?php echo '<tr id="bankpayment_account_holder"><td><label>' . $this->__('Account holder') . '</label>:</td><td>' . $this->getAccountHolder() . '</td></tr>'; ?>
	        <?php endif; ?>
	        <?php if ($this->getAccountNumber()): ?>
	            <?php echo '<tr id="bankpayment_account_number"><td><label>' . $this->__('Account number') . '</label>:</td><td>' . $this->getAccountNumber() . '</td></tr>'; ?>
	        <?php endif; ?>
	        <?php if ($this->getSortCode()): ?>
	            <?php echo '<tr id="bankpayment_sort_code"><td><label>' . $this->__('Sort code') . '</label>:</td><td>' . $this->getSortCode() . '</td></tr>'; ?>
	        <?php endif; ?>
	        <?php if ($this->getIBAN()): ?>
		        <?php echo '<tr id="bankpayment_iban"><td><label>' . $this->__('IBAN') . '</label>:</td><td>' . $this->getIBAN() . '</td></tr>'; ?>
		    <?php endif; ?>
		    <?php if ($this->getBIC()): ?>
		        <?php echo '<tr id="bankpayment_bic"><td><label>' . $this->__('BIC') . '</label>:</td><td>' . $this->getBIC() . '</td></tr>'; ?>
			<?php endif; ?>
	        </tbody>
	    </table>
    <?php endif; ?>
    <?php if ($this->getMethod()->getCustomText()): ?>
        <br />
        <div id="bankpayment_custom_text"><?php echo $this->getMethod()->getCustomText(); ?></div>
    <?php endif; ?>
</div>
