<h4><?php echo $this->__('Change your PIN (Debit Payment)') ?></h4>
<?php 
if($this->getIsActivated())
{ ?>
<br><br>
<form method="post" action="<?php echo $this->getActionUrl()?>">
<table>
<tr>
	<td width="250">
		<?php echo $this->__('ENTER_OLD_PIN') ?>
		
	</td>
	<td>
		<input type="password" maxlength="4" id="old_pin" value=""></input><br><br>
	</td>
</tr>
<tr>
	<td>
		<?php echo $this->__('ENTER_NEW_PIN') ?>
		
	</td>
	<td>
		<input type="password" maxlength="4" id="new_pin" value=""></input><br><br>
	</td>
</tr>
<tr>
	<td>
		<?php echo $this->__('REPEAT_NEW_PIN') ?>
		
	</td>
	<td>
		<input type="password" maxlength="4" id="new_pin_wdh" value=""></input>
	</td>
</tr>
<tr>
	<td>&nbsp;</td>
	<td style="text-align:right;">
		<br>
		<button type="submit"><?php echo $this->__('PIN ändern') ?></button>
	</td>
</tr>
</table>
</form>
<?php
}else{?>
<br>
<?php echo $this->__('REGISTER_FIRST') ?>
 <a href="<?php echo $this->getUrl('')?>debitpin/index">hier</a>
<?php 
}
?> 
