<div class="block block-links">
	<div class="block-title">
		<h2>
			<?php echo $this->helper('infobox')->__('Informations')?>
		</h2>
	</div>
	<div class="block-content">
		<ul class="links" <?php if($this->getName()): ?> id="<?php echo $this->getName() ?>" <?php endif;?>>
			<li class="last">
				<a href="<?php echo $this->getUrl("zahlung");?>"><?php echo Mage::helper('infobox')->__('Methods of payment')?></a>
			</li>
			<li class="last">
				<a href="<?php echo $this->getUrl("lieferung");?>"><?php echo Mage::helper('infobox')->__('Shipping costs')?></a>
			</li>
			<li class="last">
				<a href="<?php echo $this->getUrl("hinweise-dateikauf");?>"><?php echo Mage::helper('infobox')->__('Notes for buying files')?></a>
			</li>
			<li class="last">
				<a href="<?php echo $this->getUrl("downloadbedingungen-klassi");?>"><?php echo Mage::helper('infobox')->__('Download conditions classification')?></a>
			</li>
			<li class="last">
				<a href="<?php echo $this->getUrl("downloadbedingungen-arzneimittelinfo");?>"><?php echo Mage::helper('infobox')->__('Download conditions drug info')?></a>
			</li>
			<li class="last">
				<a href="http://www.dimdi.de/dynamic/de/newsletter.html" target="_blank"><?php echo Mage::helper('infobox')->__('DIMDI Newsletter')?></a>
			</li>
		</ul>
	</div>

</div>


