<?php $urls = $this->getContentUrls(); ?>
<?php if($urls != null):?>
    <div id="context-help-popup" style="left:-100000px;">
        <div id="context-help-popup-head">
            <?php echo $this->__('Contexthelp'); ?>
            <a href="javascript:void(0)" onclick="hidePopup()">
                <span class="icon egov-delete2" title="<?php echo $this->__('Close'); ?>"> </span>
            </a>
        </div>
        <div id="context-help-popup-body"></div>
    </div>
    <input type="hidden" name="showBlocks" id="showBlocks" value="0" />

    <script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>egovs/jquery.context.helper.popup.js"></script>
	<script type="text/javascript">
        $j(document).ready(function(){
            // Declared in js/egovs/jquery.context.helper.popup.js
        <?php foreach($urls as $url):?>
            ajaxUrls.push("<?php echo $url; ?>?showblocks=" + $j('#showBlocks').val());
        <?php endforeach;?>
        });
	</script>
<?php endif;?>
