<?php
/**
 * 
 *-- TODO:: kurze Beschreibung --
 *
 *
 *
 * @category		Egovs
 * @package			Egovs_Ready
 * @name			Egovs_Ready_Block_Catalog_Product_Price
 * @author 			Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright		Copyright (c) 2010 - 2015 B3 IT Systeme GmbH - http://www.b3-it.de
 * @license			http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 *
 */
?>

<?php echo $this->getCompanyFirst() ?><br />
<?php echo $this->getCompanySecond() ?><br />
<?php echo $this->getStreet() ?><br />
<?php echo $this->getZip() ?> <?php echo $this->getCity() ?>
