<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * 
 * @var $this Egovs_Checkout_Block_Multipage_Login
 */
?>
<?php
$_use_ssl_logo  = Mage::getStoreConfig('design/login/ssl_logo_use', Mage::app()->getStore());
$_ssl_image     = Mage::getStoreConfig('design/login/ssl_logo', Mage::app()->getStore());
$_ssl_image_css = Mage::getStoreConfig('design/login/ssl_logo_style', Mage::app()->getStore());
$_ssl_alt       = $this->__( Mage::getStoreConfig('design/login/ssl_logo_alt', Mage::app()->getStore()) );
$_ssl_title     = $this->__( Mage::getStoreConfig('design/login/ssl_logo_title', Mage::app()->getStore()) );

$_is_https   = Mage::app()->getFrontController()->getRequest()->isSecure();
$_show_image = ( strlen($_ssl_image) ? Mage::getBaseUrl('media') . 'ssl_logo/' . $_ssl_image : $this->getSkinUrl('images/litessl_tl_trans.gif') );

$_show_ssl = false;
if ( ($_use_ssl_logo == 0) || ($_use_ssl_logo == 2 && $_is_https) ) {
    $_show_ssl = true;
}
$show_css = '';
if ( strlen($_ssl_image_css) && !empty($_ssl_image_css) ) {
    $show_css = ' style="' . $this->htmlEscape($_ssl_image_css) . '"';
}
?>

<div class="col2-set egov-account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	  <!--Sprungziel Tastatursteuerung -->
	  <div id="jumptarget<?php echo $this->getNameInLayout();?>"></div>
	  <div class="col-1 new-users">
	  	  <form id="register-form" class="scaffold-form" action="<?php echo $this->getRegisterAction() ?>" method="post">
            <h2>
             <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
               <?php echo $this->__('Checkout as a Guest or Register') ?>
            <?php else: ?>
               <?php echo $this->__('New Customers') ?>
            <?php endif; ?>
            </h2>
	        <div class="content">
			    <fieldset>
		    	  <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
		        	<p><?php echo $this->__('Register to Create an Account or Checkout as a Guest:') ?></p>
		    	  <?php else: ?>
		          	<p>
		          		<strong><?php echo $this->__('Register and save time!') ?></strong><br />
		          		<?php echo $this->__('Register with us for future convenience:') ?>
					</p>
		            <ul class="info">
		                <li><?php echo $this->__('Fast and easy check out') ?></li>
		                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
		            </ul>
		          <?php endif; ?>
		          <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
		          	<ul class="form-list">
		              <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
		                <li>
		                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
		                    <label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
		                </li>
		              <?php endif; ?>
		                <li>
		                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
		                    <label for="login:register"><?php echo $this->__('Register') ?></label>
		                </li>
		            </ul>
		            <p><?php echo $this->__('Registration is free and easy!'); ?></p>
		          <?php else: ?>
		            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
		          <?php endif; ?>
                    <p class="secureInfo">
		    			<?php echo $this->getDatenschutztext()?>
				    </p>
			    </fieldset>
		        </div>
		 	      <div class="buttons-set">
		            <button type="submit" class="button" >
		                <span>
		                    <?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?>
		                </span>
		            </button>
		        </div>
		    </form>
	  </div>

		<div class="col-2 registered-users">
		    <form id="login-form" class="scaffold-form" action="<?php echo $this->getPostAction() ?>" method="post">
		    <?php echo $this->getBlockHtml('formkey'); ?>
		    <?php $_secure = Mage::app()->getFrontController()->getRequest()->isSecure(); ?>
		        <h2><?php echo $this->__('Login') ?></h2>
		        <div class="content">
		            <div class="securityLabel"<?php echo $show_css; ?>>
			              <span>
				                <strong><?php echo $this->__('Already registered?') ?></strong><br />
				                <?php echo $this->__('If you have an account with us, please log in.') ?>
			              </span>
    		            <?php if ($_show_ssl): ?>
                            <img src="<?php echo $_show_image; ?>" alt="<?php echo $this->__($_ssl_alt); ?>" title="<?php echo $this->__($_ssl_title); ?>" />
                        <?php endif; ?>
		            </div>
			          <fieldset<?php if( $_secure != true ): ?> class="width"<?php endif; ?>>
				            <ul class="form-list">
		                    <li>
		                        <div class="input-box">
		                            <label for="login-email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
		                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
		                        </div>
		                    </li>
		                    <li>
		                        <div class="input-box">
		                            <label for="login-password"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
		                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
		                        </div>
		                    </li>
		                </ul>
		                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
		            </fieldset>
	          </div>
    	      <div class="buttons-set">
    	          <a class="button" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" >
    	              <?php echo $this->__('Forgot your password?') ?>
    	          </a>
    	          <button type="submit" class="button" >
    	              <span><?php echo $this->__('Login') ?></span>
    	          </button>
    	      </div>
		    </form>
	  </div>
</div>
