<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Shopping cart template
 *
 * @var $this Mage_Checkout_Block_Cart
 */


$_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price';
$mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1);
?>
<div class="cart <?php echo $_priceDisplay; ?>" id="jumptarget<?php echo $this->getNameInLayout();?>">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="cart-table data-table">
            <col class="product-cart-image" width="50" />
            <col class="roduct-cart-info" />
            <col class="product-cart-price" />
            <col class="product-cart-price" />
            <col class="product-cart-total" />
            <col class="product-cart-remove" width="20" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col class="" />
            <col class="" />
        <?php endif; ?>
            <thead>
                <tr>
                    <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    <th rowspan="<?php echo $mergedCells; ?>">
                        <span class="nobr product-name"><?php echo $this->__('Product Name') ?></span>
                    </th>
                    <th class="a-center cart-price-head" colspan="<?php echo $mergedCells; ?>">
                        <span class="nobr"><?php echo $this->__('Price') ?></span>
                    </th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center">
                        <?php echo $this->__('Qty') ?>
                    </th>
                    <th class="a-center cart-total-head" colspan="<?php echo $mergedCells; ?>">
                        <?php echo $this->__('Subtotal') ?>
                    </th>
                    <th class="a-center cart-remove-head" rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="50" class="a-right cart-footer-actions">
                    <?php if($this->getContinueShoppingUrl()): ?>
                        <button class="button btn-continue egov-float-left" type="button" title="<?php echo $this->quoteEscape($this->__('Continue Shopping')) ?>" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')">
                            <?php echo $this->__('Continue Shopping') ?>
                        </button>
                    <?php endif; ?>

                        <button class="button btn-empty egov-float-left" type="submit" name="update_cart_action" data-cart-empty value="empty_cart" title="<?php echo $this->quoteEscape($this->__('Empty Cart')); ?>" id="empty_cart_button">
                            <?php echo $this->__('Empty Cart'); ?>
                        </button>
                        <button class="button btn-update" type="submit" name="update_cart_action" data-cart-item-update value="update_qty" title="<?php echo $this->quoteEscape($this->__('Update Shopping Cart')); ?>">
                            <?php echo $this->__('Update Shopping Cart'); ?>
                        </button>

                        <!--[if lt IE 8]>
                        <input type="hidden" id="update_cart_action_container" data-cart-item-update />
                        <script type="text/javascript">
                        //<![CDATA[
                            Event.observe(window, 'load', function()
                            {
                                // Internet Explorer (lt 8) does not support value attribute in button elements
                                $emptyCartButton = $('empty_cart_button');
                                $cartActionContainer = $('update_cart_action_container');
                                if ($emptyCartButton && $cartActionContainer) {
                                    Event.observe($emptyCartButton, 'click', function()
                                    {
                                        $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                        $cartActionContainer.setAttribute('name', 'update_cart_action');
                                        $cartActionContainer.setValue('empty_cart');
                                    });
                                }

                            });
                        //]]>
                        </script>
                        <![endif]-->
                    </td>
                </tr>
            </tfoot>
            <tbody>
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('shopping-cart-table')</script>
    </form>

    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
    <div class="cart-forms">
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout_cart_widget') ?>
        <?php echo $this->getChildHtml('checkout.cart.extra') ?>
        <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
    </div>
    <div class="cart-totals-wrapper">
        <!--Sprungziel Tastatursteuerung -->
        <div class="cart-totals" id="jumptarget<?php echo $this->getNameInLayout();?>">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <button class="button btn-proceed-checkout btn-checkout"
                    onclick="window.location='<?php echo $this->helper('mpcheckout/url')->getCheckoutUrl();?>';"
                    title="<?php echo $this->__('Proceed to checkout'); ?>"
                    type="button" style="font-weight:bold;">
                <div id="proceed-button-first" style="display:none;">
                    <?php echo $this->__('Order now'); ?>
                </div>
                <?php echo $this->__('Checkout'); ?>
            </button>
            <?php echo $this->getChildHtml('cartinfo') ?>
            <?php endif; ?>
        </div>

        <?php echo $this->getChildHtml('coupon') ?>

    </div>
    <?php echo $this->getChildHtml('crosssell') ?>
</div>
