<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
</div>
<div class="cart-empty">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    <p class="block-info"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <div class="buttons-set">
    	<a href="<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()); ?>" class="button">
    		<?php echo $this->__('Continue Shopping'); ?>
    	</a>
    </div>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
