<script type="text/javascript">
//<![CDATA[

</script>

<div class="entry-edit">
	<div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('eventbundle')->__('Personal Settings') ?></h4>
    </div>
    <fieldset class="a-right">
        <div><?php echo $this->getAddButtonHtml() ?></div>
        
        <div id="personal_content">
            <?php echo $this->getFieldsHtml()?>
        </div>
    </fieldset>
</div>
