<?php
/**
 * @category    design
 * @package     lhdd_default
 * @copyright   Copyright (c) 2019 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php echo $this->getChildHtml('bitvmenu') ?>
<?php echo $this->getChildHtml('currency_switcher') ?>
<?php echo $this->getChildHtml('loadingMask') ?>

<header id="header" class="page-header">
    <div class="page-header-container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>

        <!-- Skip Links -->
        <div class="skip-links">
            <!-- Home-Link -->
            <a href="<?php echo Mage::getBaseUrl(); ?>" class="skip-link skip-egov" id="home-link" data-target-element="" onclick="window.location.href='<?php echo Mage::getBaseUrl(); ?>';">
                <span class="icon egov-home"> </span>
                <span class="label"><?php echo $this->__('Startup Page'); ?></span>
            </a>
            <!-- mobiles Kunden-Manü -->
            <a href="javascript:void(0);" class="skip-link skip-nav" data-target-element="#egov-nav">
                <span class="icon egov-list"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>
            <!-- Benutzer-Konto -->
            <div class="skip-link nospace">
                <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" class="skip-link skip-account" id="egov-account-menu" data-target-element="#header-account">
       	            <span class="icon egov-user"></span>
           	        <span class="label"><?php echo $this->__('Account'); ?></span>
               	</a>
            </div>
            <!-- Cart -->
            <div class="skip-link nospace">
	            <?php echo $this->getChildHtml('minicart_head'); ?>
            </div>
            <!-- Suche -->
          <?php $_searchField = trim($this->getChildHtml('topSearch') ); ?>
          <?php if ( strlen($_searchField) ): ?>
            <div class="skip-link nospace skip-search">
                <?php echo $_searchField; ?>
            </div>
          <?php endif; ?>
	        <!-- Language-Switcher -->
	        <?php $_storeViewSwitcher = $this->getChildHtml('store_language'); ?>
	      <?php if( strlen($_storeViewSwitcher) ): ?>
	        <div class="skip-link nospace store-language-container" id="store-view-switcher">
    	        <?php echo $this->getChildHtml('store_language') ?>
        	</div>
          <?php endif; ?>

       		<?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here. See app.js for details ?>
        </div>

        <div class="welcome-header">
            <h1 class="header-position"><?php echo Mage::getStoreConfig('general/store_information/name'); ?></h1>
            <span class="welcome-msg">
                <?php echo $this->getChildHtml('welcome') ?>
                <?php echo $this->getChildHtml('accountLinks') ?>
            </span>
        </div>

        <!-- Account-Menü -->
        <div id="header-account" class="skip-content">
        	<?php echo $this->getChildHtml('topLinks') ?>
        </div>

        <!-- Navigation -->
        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
    </div>
</header>

<?php echo $this->getChildHtml('topContainer'); ?>
