<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
$_product = $this->getProduct(); ?>
<?php if ($this->displayProductStockStatus()): ?>
        <p class="availability">
        <?php if ($_product->isAvailable()): ?>
            <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value in-stock"><?php echo $this->helper('catalog')->__('In stock') ?></span>
        <?php else: ?>
            <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
            <span class="value out-of-stock"><?php echo $this->helper('catalog')->__('Out of stock') ?></span>
        <?php endif; ?>
        </p>
<?php endif; ?>
