<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title title-buttons">
    <h2><?php echo $this->__('Change Billing Address') ?></h2>
    <a href="<?php echo $this->getAddNewUrl() ?>" class="egovsbutton"><span><?php echo $this->__('Add New Address') ?></span></a>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="multiple-checkout">
    <?php foreach ($this->getAddressCollection() as $_index => $_address): ?>
        <?php if($_index%3==0): ?><div class="col3-set"><?php endif; ?>
        <div class="col-<?php echo ($_index%3+1) ?>">
                <p class="actions">
                    <a href="<?php echo $this->getEditAddressUrl($_address) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> 
                    <a href="<?php echo $this->getSetAddressUrl($_address) ?>"><?php echo $this->__('Select Address') ?></a>
                </p>
                <address>
                    <?php echo $_address->format('html') ?>
                    <?php if($this->isAddressDefaultBilling($_address)): ?>
                        <br /><strong><?php echo $this->__('Default Billing') ?></strong>
                    <?php endif; ?>
                    <?php if($this->isAddressDefaultShipping($_address)): ?>
                        <br /><strong><?php echo $this->__('Default Shipping') ?></strong>
                    <?php endif; ?>
                </address>
        </div>
        <?php if($_index && $_index%3==0): ?></div><?php endif; ?>
    <?php endforeach; ?>
    <?php if(!$_index || $_index%3!=0): ?></div><?php endif; ?>
</div>
<div class="buttons-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="button"><?php echo $this->__('Back to Billing Information') ?></a>
</div>
