<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_params = $this->escapeHtml(json_encode(array('form_key' => $this->getFormKey())));
    $name_limit = 500;
    $sku_limit = 24;
    $desc_limit = 1000;
    $_imgSize_list = 500;
    $_imgSize_grid = 210;
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <div class="product-list-left-col">
                <?php /* Product Image */ ?>
                <?php $_imageAlt = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_imageAlt; ?>" class="product-image">
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize_list); ?>"
                         alt="<?php echo $_imageAlt; ?>" />
                    <span class="image-copyright-box"><span><?php echo $_imageAlt; ?></span></span>
                </a>

                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <?php // More-Link ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn">
                    <?php echo $this->__('Learn More') ?>
                </a>

                <?php // Links for Wishlist and Compare ?>
                <div class="product-add-links">
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <?php $_wishlistUrl = $this->helper('wishlist')->getAddUrlWithCustomParams($_product, array(), false); ?>
                            <li>
                                <a href="#"
                                   data-url="<?php echo $_wishlistUrl ?>"
                                   data-params="<?php echo $_params ?>"
                                   class="link-wishlist egov-star egov-float-left"
                                   title="<?php echo $this->__('Add to Wishlist') ?>"
                                   onclick="customFormSubmit('<?php echo $_wishlistUrl ?>', '<?php echo $_params ?>', 'post')">
                                </a>
                            </li>
                        <?php endif; ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)): ?>
                            <li>
                                <a href="#"
                                   class="link-compare egov-float-right"
                                   title="<?php echo $this->__('Add to Compare') ?>"
                                   onclick="customFormSubmit('<?php echo $_compareUrl ?>', '<?php echo $_params ?>', 'post')">
                                    <span class="egov-compare"> </span>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>

            <?php // Product description ?>
            <div class="product-shop">
                <div class="product-primary">
                    <?php
                    //$_productNameStripped = $this->stripTags($_product->getName(), null, true);
                    $_productPrefix = $_product->getNamePrefix();
                    $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');

                    $_isorder = Mage::getModel('catalog/product')->load($_product->getId())->getShowOrderability();
                    if ( is_null($_isorder) || $_isorder == '1' ) {
                        $_isorder = true;
                    }
                    else {
                        $_isorder = false;
                    }

                    if ( strlen($_productName) > $name_limit ) {
                        $_productName = substr($_productName, 0, $name_limit) . '...';
                    }
                    ?>
                    <h2 class="product-name">
                        <?php if (strlen($_productPrefix)) : ?><span class="name-prefix"><?php echo $_productPrefix ?></span><?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                            <?php echo $_productName; ?>
                        </a>
                    </h2>
                    <div class="product_sku">
                        <?php
                        $_sku = $_sku_full = $this->escapeHtml($_product->getSku());

                        if ( strlen($_sku) > $sku_limit ) {
                            $_sku = substr($_sku, 0, $sku_limit) . '...';
                        }
                        echo $this->__('Sku').': <span title="'.$_sku_full.'">'.$_sku.'</span>';
                        ?>
                    </div>
                    <div class="desc std">
                        <?php
                        $_short_description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                        echo "<div class=\"full\">$_short_description<div class=\"shorter\"></div></div>\n";

                        if ( strlen($_short_description) > $desc_limit ) {
                            $_short_description = substr($_short_description, 0, $desc_limit) . '...';
                        }
                        echo "<div class=\"short\">$_short_description<div class=\"shorter\"></div></div>\n";
                        ?>
                    </div>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                </div>
              <?php if ($_isorder): ?>
                <div class="product-price">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>

                <div class="product-action">
                    <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                        <button type="button"
                                title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                class="button btn-cart egov-cart"
                                onclick="customFormSubmit(
                                        '<?php echo $this->getAddToCartUrlCustom($_product, array(), false) ?>',
                                        '<?php echo $_params ?>',
                                        'post')">
                            <span>
                                <?php echo $this->__('Add to Cart') ?>
                            </span>
                        </button>
                    <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                        <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>"
                           class="button egov-view"
                           href="<?php echo $_product->getProductUrl() ?>">
                            <span>
                                <?php echo $this->__('View Details') ?>
                            </span>
                        </a>
                    <?php else: ?>
                        <p class="action availability out-of-stock"><span><?php echo $this->__('Event not available') ?></span></p>
                    <?php endif; ?>
                </div>
              <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <?php $_imageAlt = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_imageAlt; ?>" class="product-image">
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize_list); ?>"
                         alt="<?php echo $_imageAlt; ?>" />
                    <span class="image-copyright-box"><span><?php echo $_imageAlt; ?></span></span>
                </a>
                <div class="product-info">
                    <?php
                    $_productNameStripped = $this->stripTags($_product->getName(), null, true);
                    $_productPrefix = $_product->getNamePrefix();
                    $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                    if ( strlen($_productName) > $name_limit ) {
                        $_productName = substr($_productName, 0, $name_limit) . '...';
                    }

                    $_isorder = Mage::getModel('catalog/product')->load($_product->getId())->getShowOrderability();
                    if ( is_null($_isorder) || $_isorder == '1' ) {
                        $_isorder = true;
                    }
                    else {
                        $_isorder = false;
                    }
                    ?>
                    <h2 class="product-name">
                        <?php if (strlen($_productPrefix)) : ?><span class="name-prefix"><?php echo $_productPrefix ?></span><?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                            <?php echo $_productName; ?>
                        </a>
                    </h2>
                    <div class="product_sku">
                        <?php
                        $_sku = $_sku_full = $this->escapeHtml($_product->getSku());

                        if ( strlen($_sku) > $sku_limit ) {
                            $_sku = substr($_sku, 0, $sku_limit) . '...';
                        }
                        echo $this->__('Sku').': <span title="'.$_sku_full.'">'.$_sku.'</span>';
                        ?>
                    </div>
                    <?php
                    // Provides extra blocks on which to hang some features for products in the list
                    // Features providing UI elements targeting this block will display directly below the product name
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <?php if ($_isorder): ?>
                    <div class="actions">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <button type="button"
                                    title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                    class="button btn-cart egov-cart"
                                    onclick="customFormSubmit(
                                            '<?php echo $this->getAddToCartUrlCustom($_product, array(), false) ?>',
                                            '<?php echo $_params ?>',
                                            'post')">
                                <span><?php echo $this->__('Add to Cart') ?></span>
                            </button>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>"
                               class="button egov-view"
                               href="<?php echo $_product->getProductUrl() ?>">
                                <span><?php echo $this->__('View Details') ?></span>
                            </a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <?php $_wishlistUrl = $this->helper('wishlist')->getAddUrlWithCustomParams($_product, array(), false); ?>
                                <li>
                                    <a href="#"
                                       data-url="<?php echo $_wishlistUrl ?>"
                                       data-params="<?php echo $_params ?>"
                                       class="link-wishlist egov-star egov-float-left"
                                       title="<?php echo $this->__('Add to Wishlist') ?>"
                                       onclick="customFormSubmit('<?php echo $_wishlistUrl ?>', '<?php echo $_params ?>', 'post')">
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrlCustom($_product, false)): ?>
                                <li>
                                    <a href="#"
                                       class="link-compare egov-float-right"
                                       title="<?php echo $this->__('Add to Compare') ?>"
                                       onclick="customFormSubmit('<?php echo $_compareUrl ?>', '<?php echo $_params ?>', 'post')">
                                        <span class="egov-compare"> </span>
                                        <!-- <span class="egov-compare-1"> </span>/<span class="egov-compare-2"> </span> -->
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
