<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
$_helper  = $this->helper('catalog/output');
$_product = $this->getProduct();

$_isorder = $_helper->productAttribute($_product, $_product->getShowOrderability(), 'show_orderability');
if ( is_null($_isorder) ) {
    $_isorder = true;
}
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div id="product-base-block">
                <div class="product-img-box">
                    <?php echo $this->getChildHtml('thumbnail'); ?>
                </div>

                <div class="product-shop">
                    <div class="product-name">
                        <span class="name-prefix"><?php echo $_product->getNamePrefix() ?></span>
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h1>
                    </div>

                    <div id="details-block">
                        <div class="product-sku">
                            <?php echo $this->__('SKU') . ': ' . $_helper->productAttribute($_product, $this->htmlEscape($_product->getSku()), 'sku'); ?>
                        </div>
                      <?php if ( $_isorder ): ?>
                        <div class="price-info">
                            <?php echo $this->getPriceHtml($_product); ?>
                            <?php echo $this->getChildHtml('bundle_prices'); ?>
                            <?php echo $this->getTierPriceHtml(); ?>
                        </div>
                      <?php endif; ?>

                        <div class="extra-info">
                            <?php echo $this->getReviewsSummaryHtml($_product, 'default', false); ?>
                            <?php echo $this->getChildHtml('product_type_availability'); ?>
                        </div>

                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php echo $this->getChildHtml('extrahint') ?>

                      <?php if ($_product->getShortDescription()):?>
                        <div class="short-description">
                            <div class="std">
                                <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                            </div>
                        </div>
                      <?php endif;?>

                    <?php if ( $_isorder ): ?>
                      <?php if (!$this->hasOptions()):?>
                        <?php if($_product->isSaleable()): ?>
                          <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                      <?php elseif (!$_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addto') ?>
                      <?php endif; ?>
                    <?php endif;?>

                      <?php /* echo $this->getChildHtml('sharing'); */ ?>
                    </div>
                </div>
            </div>

            <?php echo $this->getChildHtml('media'); ?>

            <div class="product-additional-information">
                <?php echo $this->getChildHtml('other');?>

              <?php if ( $_isorder ): ?>
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>
              <?php endif;?>
            </div>

            <?php echo $this->getChildHtml('related_products') ?>

            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>

            <div class="product-collateral toggle-content tabs">
              <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                <dl id="collateral-tabs" class="collateral-tabs">
                  <?php foreach ($detailedInfoGroup as $alias => $html):?>
                    <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
                    <dd class="tab-container">
                        <div class="tab-content"><?php echo $html; ?></div>
                    </dd>
                  <?php endforeach;?>
                </dl>
              <?php endif; ?>
            </div>

        </form>
    </div>

    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>

    <?php echo $this->getChildHtml('addto') ?>
    <?php echo $this->getChildHtml('extra_buttons') ?>

</div>

<script type="text/javascript">
//<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
               form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
//]]>
</script>
