<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Billing $this */
?>
<form id="co-billing-form" action="">
    <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
    <div class="fieldset wide">
        <ul class="form-list">
          <?php if ($this->customerHasAddresses()): ?>
            <li class="fields">
                <div class="field">
                    <label for="billing-address-select">
                        <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
                    </label>
                    <?php echo $this->getAddressesHtmlSelect('billing') ?>
                </div>
            </li>
          <?php endif; ?>
            <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?> class="scaffold-form">

                <div class="fieldset wide">
                    <ul class="form-list">
                        <li class="fields">
                            <?php echo $this->getLayout()->createBlock('egovsbase/customer_widget_name')
                                            ->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())
                                            ->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())
                                            ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')
                                            ->toHtml() ?>
                        </li>
                     </ul>
                </div>

                <div class="fieldset">
                    <ul class="form-list">
                      <?php if(!$this->isCustomerLoggedIn()): ?>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:email"><?php echo $this->getFieldRequiredHtml('email')?>
                                    <?php echo $this->getFieldRequiredHtml('email')?>
                                    <?php echo $this->__('Email Address') ?>
                                </label>
                                <input type="email" spellcheck="false" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                            </div>
                        </li>
                      <?php endif; ?>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:company">
                                    <?php echo $this->getFieldRequiredHtml('company')?>
                                    <?php echo $this->__('Company') ?>
                                </label>
                                <div class="input-box">
                                    <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                </div>
                            </div>
                        </li>
                        <li class="field">
                            <div class="field">
                                <label for="billing:telephone">
                                    <?php echo $this->getFieldRequiredHtml('telephone')?>
                                    <?php echo $this->__('Telephone') ?>
                                </label>
                                <input type="tel" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="fieldset">
                    <ul class="form-list">
                      <?php if(!$this->isCustomerLoggedIn()): ?>
                        <li class="fields dummy"><!-- Customer Login --></li>
                      <?php endif; ?>
                      <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:vat_id">
                                    <?php echo $this->__('VAT Number') ?>
                                </label>
                                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->quoteEscape($this->__('VAT Number')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                      <?php else : ?>
                        <li class="fields dummy"><!-- VAT Number disable --></li>
                      <?php endif; ?>
                        <li class="field">
                            <div class="field">
                                <label for="billing:fax">
                                    <?php echo $this->getFieldRequiredHtml('fax')?>
                                    <?php echo $this->__('Fax') ?>
                                </label>
                                <input type="tel" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->quoteEscape($this->__('Fax')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                            </div>
                        </li>
                    </ul>
                </div>

                <div class="fieldset wide">
                    <ul class="form-list">
                        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:street1">
                                    <?php echo $this->getFieldRequiredHtml('street')?>
                                    <?php echo $this->__('Address') ?>
                                </label>
                                <input type="text" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                              <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                <!--<label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>-->
                                <input type="text" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                              <?php endfor; ?>
                            </div>
                        </li>
                    </ul>
                </div>

                <div class="fieldset">
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="billing:postcode">
                                    <?php echo $this->getFieldRequiredHtml('postcode')?>
                                    <?php echo $this->__('Zip/Postal Code') ?>
                                </label>
                                <input type="text" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:region_id">
                                    <?php echo $this->getFieldRequiredHtml('region')?>
                                    <?php echo $this->__('State/Province') ?>
                                </label>
                                <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="fieldset">
                    <ul class="form-list">
                        <li class="fields">
                            <div class="field">
                                <label for="billing:city">
                                    <?php echo $this->getFieldRequiredHtml('city')?>
                                    <?php echo $this->__('City') ?>
                                </label>
                                <input type="text" title="<?php echo $this->quoteEscape($this->__('City')) ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="billing:city" />
                            </div>
                        </li>
                        <li class="fields">
                            <div class="field">
                                <label for="billing:country_id">
                                    <?php echo $this->getFieldRequiredHtml('country_id')?>
                                    <?php echo $this->__('Country') ?>
                                </label>
                                <?php echo $this->getCountryHtmlSelect('billing') ?>
                            </div>
                        </li>
                        <li class="fields" id="register-customer-password-confirm">
                        </li>
                    </ul>
                </div>

                <div class="fieldset wide">
                    <ul class="form-list">
                        <li class="fields" id="register-customer-password">
                            <div class="field">
                                <label for="billing:customer_password">
                                    <span>*</span>
                                    <?php echo $this->__('Password') ?>
                                </label>
                                <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
                            </div>
                            <div class="field">
                                <label for="billing:confirm_password">
                                    <span>*</span>
                                    <?php echo $this->__('Confirm Password') ?>
                                </label>
                                <input type="password" name="billing[confirm_password]" title="<?php echo $this->quoteEscape($this->__('Confirm Password')) ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                            </div>
                        </li>
                    </ul>
                </div>

            </li>
        </ul>
    </div>

    <p class="required"><?php echo $this->__('* Required Fields') ?></p>

    <div class="buttons-set" id="billing-buttons-container">
        <button type="button" title="<?php echo $this->quoteEscape($this->__('Continue')) ?>" class="button" onclick="billing.save()">
            <?php echo $this->__('Continue') ?>
        </button>
        <span class="please-wait" id="billing-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                 alt="<?php echo $this->quoteEscape($this->__('Loading next step...')) ?>"
                 title="<?php echo $this->quoteEscape($this->__('Loading next step...')) ?>"
                 class="v-middle" />
            <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
    <?php echo $this->getBlockHtml('formkey') ?>
</form>

<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->jsQuoteEscape($this->__('Select State/Province...')) ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
//]]>
</script>
