<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<?php echo $this->getChildHtml('login_before') ?>

<!--Sprungziel Tastatursteuerung -->
<div id="jumptarget<?php echo $this->getNameInLayout();?>"></div>

<div class="col2-set egov-account-login<?php if (!$this->helper('customer')->isRegistrationAllowed() && !$this->getQuote()->isAllowedGuestCheckout()) echo ' login-only' ?>">
    <div class="col-1 new-users">
        <h2>
          <?php if( $this->getQuote()->isAllowedGuestCheckout() && $this->helper('customer')->isRegistrationAllowed() ): ?>
            <?php echo $this->__('Checkout as a Guest or Register') ?>
          <?php elseif ( $this->getQuote()->isAllowedGuestCheckout() && !$this->helper('customer')->isRegistrationAllowed() ): ?>
            <?php echo $this->__('Checkout as a Guest') ?>
          <?php else: ?>
            <?php echo $this->__('Register to Create an Account') ?>
          <?php endif; ?>
        </h2>
        <div class="content">
            <fieldset>
		    		  <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
		        	  <p><?php echo $this->__('Register to Create an Account or Checkout as a Guest:') ?></p>
		    		  <?php else: ?>
		            <p>
		          	    <strong><?php echo $this->__('Register and save time!') ?></strong><br />
		          	    <?php echo $this->__('Register with us for future convenience:') ?>
					      </p>
		            <ul class="info">
		                <li><?php echo $this->__('Fast and easy check out') ?></li>
		                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
		            </ul>
		    		  <?php endif; ?>
		    		  <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <ul class="form-list">
                  <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()!=Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                    </li>
                  <?php endif; ?>
                  <?php if( $this->helper('customer')->isRegistrationAllowed() ): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
                        <label for="login:register"><?php echo $this->__('Register and Checkout') ?></label>
                    </li>
                  <?php endif; ?>
                </ul>
                <br />
					      <p>
		               <strong><?php echo $this->__('Register and save time!') ?></strong><br />
		               <?php echo $this->__('Register with us for future convenience:') ?>
					      </p>
		            <ul class="info">
		                <li><?php echo $this->__('Fast and easy check out') ?></li>
		                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
		            </ul>
		    		  <?php else: ?>
		    		    <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
		    		  <?php endif; ?>
		    		    <br />
                <p class="secureInfo">
		    			      <?php echo $this->getDatenschutztext()?>
				        </p>
            </fieldset>
        </div>
        <div class="buttons-set">
          <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
            <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();">
                <?php echo $this->__('Continue') ?>
            </button>
          <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
            <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'">
                <?php echo $this->__('Register') ?>
            </button>
          <?php else: ?>
            <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                <button id="onepage-guest-register-button" type="submit" class="button">
                    <?php echo $this->__('Register') ?>
                </button>
            </form>
          <?php endif; ?>
        </div>
    </div>

    <div class="col-2 registered-users">
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <h2><?php echo $this->__('Returning Customers') ?></h2>
            <div class="content">
		            <div class="securityLabel">
			              <span>
				                <strong><?php echo $this->__('Already registered?') ?></strong><br />
				                <?php echo $this->__('If you have an account with us, please log in.') ?>
			              </span>
			            <?php if( Mage::app()->getFrontController()->getRequest()->isSecure() ): ?>
			              <img src="<?php echo $this->getSkinUrl('images/litessl_tl_trans.gif'); ?>" alt="<?php echo $this->__('Certified safety - Positive SSL Label'); ?>" title="<?php echo $this->__('Positive SSL'); ?>" />
		              <?php endif; ?>
		            </div>
                <fieldset>
                    <?php echo $this->getMessagesBlock()->toHtml() ?>
				            <ul class="form-list">
		                    <li>
		                        <div class="input-box">
		                            <label for="login-email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
		                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
		                        </div>
		                    </li>
		                    <li>
		                        <div class="input-box">
		                            <label for="login-password"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
		                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
		                        </div>
		                    </li>
		                </ul>
		                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </fieldset>
            </div>
    	      <div class="buttons-set">
    	          <a class="button" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" >
    	              <?php echo $this->__('Forgot your password?') ?>
    	          </a>
    	          <button type="submit" class="button" onclick="onepageLogin(this)" >
    	              <span><?php echo $this->__('Login') ?></span>
    	          </button>
    	      </div>
        </form>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }

    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        });
<?php endif; ?>
//]]>
</script>
