<?php
/**
 * @category    design
 * @package     lhdd_default
 * @copyright   Copyright (c) 2019 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="form-search">^
        <label for="search"><?php echo $this->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Search')) ?>" class="button">
            <?php echo $this->__('Search') ?>
        </button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm(
                                     'search_mini_form',
                                     'search',
                                     '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Search entire store here...')) ?>'
                                 );
            searchForm.initAutocomplete(
                '<?php echo $catalogSearchHelper->getSuggestUrl() ?>',
                'search_autocomplete'
            );
        //]]>
        </script>
    </div>
</form>
