<?php
/**
 * @category    design
 * @package     lhdd_default
 * @copyright   Copyright (c) 2019 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Popular Search Terms') ?></h1>
</div>
<?php if( sizeof($this->getTerms()) > 0 ): ?>
    <ul class="tags-list">
        <?php foreach ($this->getTerms() as $_term): ?>
            <li><a href="<?php echo $this->getSearchUrl($_term) ?>" style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;"><?php echo $this->escapeHtml($_term->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p class="note-msg block-info"><?php echo $this->__('There are no search terms available.'); ?></p>
<?php endif; ?>
