<script type="text/javascript">


var Product = Class.create();
Product.prototype = {
  initialize: function(id, sku, name) {
    this.id = id;
    this.sku = sku;
    this.name = name;
  }
};

var products=new Array();
<?php echo $this->getProducts();?>

if (!window.Quick)
    var Quick = new Object();

Quick.searchForm = Class.create();
Quick.searchForm.prototype = {
    initialize : function(form, field, emptyText){
        this.form   = $(form);
        this.field  = $(field);
        this.emptyText = emptyText;

        Event.observe(this.form,  'submit', this.submit.bind(this));
        Event.observe(this.field, 'focus', this.focus.bind(this));
        Event.observe(this.field, 'blur', this.blur.bind(this));
        Event.observe(this.field, 'keyup', this.onkeyup.bind(this));
        this.blur();
    },

    submit : function(event){
        if (this.field.value == this.emptyText || this.field.value == ''){
            Event.stop(event);
            return false;
        }
        return true;
    },

    focus : function(event){
        if(this.field.value==this.emptyText){
            this.field.value='';
        }

    },

    blur : function(event){
        if(this.field.value==''){
            this.field.value=this.emptyText;
        }
    },

    onkeyup : function(event){

    	if($('quick_autocomplete') != null)
    	{
    		//$('quick_autocomplete').descendants().remove();
            $('quick_autocomplete').hide();
    	}

        if(this.field.value==''){
            this.field.value=this.emptyText;
            $('_quicksuggest_id').value = 0; 
        	
        }else
        {
        
            var n = 0;
            var found = new Array();
            for(i=0; i < products.length; i++)
            {
                if((products[i].sku.toLowerCase().indexOf(this.field.value.toLowerCase())==0) || (products[i].name.toLowerCase().match(this.field.value.toLowerCase())))
                {
                	found[n]=products[i];
                	n++; 
                }
            }

            if(found.length == 1)
            {
            	this.field.value=found[0].name;
                $('_quicksuggest_id').value =found[0].id;
            }
            else if (found.length > 1)
            {
            	//Element.replace('quick_autocomplete', '<p>Bar</p>')
            	var content ="<ul>";
            	for(i=0; i < found.length; i++)
            	{
                	if(i%2==0) classname = 'even';
                	else classname = 'odd';
            		content = content + '<li id=\"'+found[i].id+'\" class=\"'+classname+'\" title=\"'+found[i].name+'\" onclick=\"_selectAutocompleteItem(this);\"><span class=\"sku\">'+found[i].sku+',</span>'+found[i].name+'</li>';
            	}
            	content += "</ul>";
                $('quick_autocomplete').update(content);
                $('quick_autocomplete').show();
            }
        }
       
        
    }

}

function _selectAutocompleteItem(element){
    	$('_quicksuggest_id').value = 0;
    	$('quick_autocomplete').hide();
        if(element.title){
        	$('quicksearch').value = element.title;
            $('_quicksuggest_id').value = element.id;
        }
        $('quicksearch').focus();
        //this.form.submit();
    }
function addCart()
{
	new Ajax.Updater('quick.card','<?php echo $this->getAddUrl();?>',{parameters:{id: $('_quicksuggest_id').value}});
	$('quicksearch').value = '';
	
}

</script>
<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="quick_form" action="#" method="post" onsubmit="addCart(); return;">

<fieldset class="form-search">
    <legend>Search Site</legend>
    <label for="search"></label>

    <input id="quicksearch" type="text" class="input-text" name="quicksuggest" value="" autocomplete="off"/>
    <input type="hidden" name="quicksuggest_id" id="_quicksuggest_id" value="0" />
    <button type="button" class="form-button-alt" id="bt_addCart" onclick="addCart();">
		<span>Hinzuf&uuml;gen</span>
	</button>
    <div id="quick_autocomplete" class="search-autocomplete" style="display:none;"></div>
    
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Quick.searchForm('quick_form', 'quicksearch', '');
        //searchForm.initAutocomplete('<?php echo $this->getSuggestUrl();?>', 'quick_autocomplete');
    //]]>
    </script>

</fieldset>

</form>


<div id="quick.card">
	<?php echo $this->getCart();?>
</div>

