                <tr>
                    <td>
                        <div class="grid">
                            <table cellspacing="0" class="data border" id="table-<?php echo $this->getHtmlId() ?>_grid" width="100%">
                                <colgroup>
                                    <col style="" />
                                    <col style="width: 150px;" />
                                    <col style="width: 100px;" />
                                    <col style="width: 100px;" />
                                    <col style="width: 110px;" />
                                </colgroup>
                                <thead>
                                    <tr class="headings">
                                        <th><?php echo $this->__('Original Filename'); ?></th>
                                        <th><?php echo $this->__('Created At'); ?></th>
                                        <th><?php echo $this->__('Downloadlink'); ?></th>
                                        <th><?php echo $this->__('Deletelink'); ?></th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody id="<?php echo $this->getHtmlId() ?>_list">
                                    <tr id="<?php echo $this->getHtmlId() ?>_template" class="template no-display">
                                        <td class="cell-label">
                                            __filename__
                                            <select id="doctype-__id__" name="doctype" class="doctype-select">
                                              <?php foreach ($this->getDocTypes() as $k=>$v):?>
                                                <option value="<?php echo $k?>"><?php echo $v?></option>
                                              <?php endforeach;?>
                                            </select>
                                        </td>
                                        <td class="cell-date">__created__</td>
                                        <td class="cell-download"><a href="__download__"><?php echo $this->__('Download'); ?></a></td>
                                        <td class="cell-delete"><a href="__delete__"><?php echo $this->__('Delete'); ?></a></td>
                                        <td class="position-sorting">
                                            <button class="scalable add-widget position-up" type="button" title="<?php echo $this->__('Up'); ?>" disabled="disabled"><span></span></button>
                                            <button class="scalable add-widget position-down" type="button" title="<?php echo $this->__('Down'); ?>" disabled="disabled"><span></span></button>
                                        </td>
                                    </tr>
                                  <?php foreach ($this->getFiles() AS $key => $file):?>
                                    <tr id="row-<?php echo $this->getHtmlId() ?>-<?php echo $file->getId(); ?>" data-id="<?php echo $file->getId(); ?>" data-table="<?php echo $this->getHtmlId() ?>">
                                        <td class="cell-label">
                                            <?php echo $file->getOrigFilename();?>
                                            <select id="doctype-<?php echo $file->getId(); ?>" name="doctype" class="doctype-select">
                                              <?php foreach ($this->getDocTypes() as $k=>$v):?>
                                                <option value="<?php echo $k?>"><?php echo $v?></option>
                                              <?php endforeach;?>
                                            </select>
                                        </td>
                                        <td class="cell-date"><?php echo $file->getCreated();?></td>
                                        <td class="cell-download"><a href="<?php echo $file->getDownloadUrl();?>"><?php echo $this->__('Download'); ?></a></td>
                                        <td class="cell-delete"><a href="<?php echo $file->getDeleteUrl();?>"><?php echo $this->__('Delete'); ?></a></td>
                                        <td class="position-sorting">
                                            <button class="scalable add-widget position-up" type="button" title="<?php echo $this->__('Up'); ?>" disabled="disabled"><span></span></button>
                                            <button class="scalable add-widget position-down" type="button" title="<?php echo $this->__('Down'); ?>" disabled="disabled"><span></span></button>
                                        </td>
                                    </tr>
                                  <?php endforeach;?>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="100" class="last" style="padding:8px">
                                            <?php echo $this->getUploaderHtml(); ?>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                            <input type="hidden"
                                   id="<?php echo $this->getHtmlId() ?>_save"
                                   name="<?php echo $this->getElement()->getName() ?>[images]"
                                   value="<?php echo $this->htmlEscape($this->getImagesJson()) ?>" />
                            <input type="hidden"
                                   id="<?php echo $this->getHtmlId() ?>_save_image"
                                   name="<?php echo $this->getElement()->getName() ?>[values]"
                                   value="<?php echo $this->htmlEscape($this->getImagesValuesJson()) ?>" />
                            <script type="text/javascript">
                                $j('#<?php echo $this->getHtmlId() ?>_list').LicenseCopy({
                                    'templateId': '#<?php echo $this->getHtmlId() ?>_template',
                                    'newRowId'  : '<?php echo $this->getHtmlId() ?>'
                                });
                            </script>
                        </div>
                    </td>
                </tr>
