                <tr>
                    <td>
                        <div class="grid">
                            <table cellspacing="0" class="data border" id="table-<?php echo $this->getHtmlId() ?>_grid" width="100%">
                                <colgroup>
                                    <col style="" />
                                    <col style="width: 150px;" />
                                    <col style="width: 100px;" />
                                    <col style="width: 100px;" />
                                    <col style="width: 110px;" />
                                </colgroup>
                                <thead>
                                    <tr class="headings">
                                        <th><?php echo $this->__('Original Filename'); ?></th>
                                        <th><?php echo $this->__('Document Type'); ?></th>
                                        <th><?php echo $this->__('Created At'); ?></th>
                                        <th><?php echo $this->__('Download'); ?></th>
                                        <th><?php echo $this->__('Delete'); ?></th>
                                    </tr>
                                </thead>
                                <tbody id="<?php echo $this->getHtmlId() ?>_list">
                                <template id="<?php echo $this->getHtmlId() ?>_template">
                                   
                                        <td class="cell-label">
                                            __filename__
                                            </td>
                                            <td>
                                            <select id="doctype-__id__" name="doctype[__id__]" class="doctype-select">
                                              <?php foreach ($this->getDocTypes() as $k=>$v):?>
                                                <option value="<?php echo $k?>"><?php echo $v?></option>
                                              <?php endforeach;?>
                                            </select>
                                        </td>
                                        <td class="cell-date">__created__</td>
                                        <td class="cell-download"><a href="__download__"><?php echo $this->__('Download'); ?></a></td>
                                        <td class="cell-delete">
                                        <button class="scalable delete add-widget position-delete" type="button" onclick="LicenseCopyInstance<?php echo $this->getHtmlId()?>.deleteRow(__id__)"><span></span></button>
                                        	<input name="file_deleted[__id__]" id="file-deleted-__id__" value="0" type="hidden" />
                                        </td>
                                    </template>
                                  <?php foreach ($this->getFiles() AS $key => $file):?>
                                    <tr id="row-<?php echo $this->getHtmlId() ?>-<?php echo $file->getId(); ?>" data-id="<?php echo $file->getId(); ?>" data-table="<?php echo $this->getHtmlId() ?>">
                                        <td class="cell-label">
                                            <?php echo $file->getOrigFilename();?>
                                        </td>
                                        <td class="cell-label">
                                            <select id="doctype-<?php echo $file->getId(); ?>" name="doctype[<?php echo $file->getId(); ?>]" class="doctype-select">
                                              <?php foreach ($this->getDocTypes() as $k=>$v):?>
                                              <?php if($k == $file->getUsage()):?>
                                              	<option selected="selected" value="<?php echo $k?>"><?php echo $v?></option>
                                              <?php else:?>
                                                <option value="<?php echo $k?>"><?php echo $v?></option>
                                               <?php endif;?>
                                              <?php endforeach;?>
                                            </select>
                                        </td>
                                        <td class="cell-date"><?php echo $file->getCreated();?></td>
                                        <td class="cell-download"><a href="<?php echo $file->getDownloadUrl();?>"><?php echo $this->__('Download'); ?></a></td>
                                        <td class="cell-delete">
                                        	<button class="scalable delete add-widget position-delete" type="button" onclick="LicenseCopyInstance<?php echo $this->getHtmlId()?>.deleteRow(<?php echo $file->getId(); ?>)"><span></span></button>
                                        	<input name="file_deleted[<?php echo $file->getId()?>]" id="file-deleted-<?php echo $file->getId()?>" value="0" type="hidden" />
                                        </td>
                                    </tr>
                                  <?php endforeach;?>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="100" class="last" style="padding:8px">
                                            <?php echo $this->getUploaderHtml(); ?>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                            <input type="hidden"
                                   id="<?php echo $this->getHtmlId() ?>_save"
                                   name="<?php echo $this->getElement()->getName() ?>[images]"
                                   value="<?php echo $this->htmlEscape($this->getImagesJson()) ?>" />
                            <input type="hidden"
                                   id="<?php echo $this->getHtmlId() ?>_save_image"
                                   name="<?php echo $this->getElement()->getName() ?>[values]"
                                   value="<?php echo $this->htmlEscape($this->getImagesValuesJson()) ?>" />
                            <script type="text/javascript">
                                var LicenseCopyInstance<?php echo $this->getHtmlId()?> = new LicenseCopy({
                                    'templateId': '#<?php echo $this->getHtmlId() ?>_template',
                                    'newRowId'  : '<?php echo $this->getHtmlId() ?>',
                                    'containerId': '<?php echo $this->getHtmlId() ?>'
                                });

                                document.on('uploader:fileSuccess', function(event) {
                                    var memo = event.memo;
                                    LicenseCopyInstance<?php echo $this->getHtmlId()?>.UploadComplete([{response: memo.response}]);
                                });
                            </script>
                        </div>
                    </td>
                </tr>
