<table class="data" id="table-file" cellspacing="0">
    <colgroup>
        <col>
        <col style="width: 110px;">
    </colgroup>
    <thead>
    <tr class="headings">
        <th>Block</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody data-up-down="0">
    <tr id="row-agreement-0" data-id="0" data-table="agreement"><td>Fusszeile<input id="value-agreement-0" name="agreement[value][]" value="footer_links" type="hidden"><input id="pos-agreement-0" name="agreement[pos][]" value="0" type="hidden"><input id="delete-agreement-0" name="agreement[delete][]" value="0" type="hidden"></td><td class="position-sorting"><button class="scalable add-widget position-up" type="button" title="Up" disabled="disabled"><span></span></button><button class="scalable add-widget position-down" type="button" title="Down" disabled="disabled"><span></span></button><button class="scalable delete add-widget position-delete" type="button" title="Entfernen"><span></span></button></td></tr></tbody>
</table>