<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_option = $this->getOption() ?>
<?php $_optionId = $_option->getId() ?>
<dt class="option-block type-<?php echo $_option->getType(); ?>">
    <div class="option-block-label">
        <label>
            <?php if ($_option->getIsRequire()) echo '<em class="required">*</em>' ?>
            <?php echo  $this->escapeHtml($_option->getTitle()) ?>
        </label>
        <?php echo $this->getFormatedPrice() ?>
    </div>
    <div class="option-block-elements">
    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
        || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE): ?>

        <?php echo $this->getDateHtml() ?>

        <?php if (!$this->useCalendar()): ?>
        <script type="text/javascript">
        //<![CDATA[
            Event.observe('options_<?php echo $_optionId ?>_month', 'change', dateOption.reloadMonth.bind(dateOption));
            Event.observe('options_<?php echo $_optionId ?>_year', 'change', dateOption.reloadMonth.bind(dateOption));
        //]]>
        </script>
        <?php endif; ?>

    <?php endif; ?>

    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
        || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_TIME): ?>
        <span class="time-picker"><?php echo $this->getTimeHtml() ?></span>
    <?php endif; ?>

        <input type="hidden" name="validate_datetime_<?php echo $_optionId ?>" class="validate-datetime-<?php echo $_optionId ?>" value="" />
        <script type="text/javascript">
        //<![CDATA[
    <?php if ($_option->getIsRequire()): ?>
            Validation.addAllThese(
            [
                   ['validate-datetime-<?php echo $_optionId ?>', '<?php echo $this->jsQuoteEscape( Mage::helper('catalog')->__('This is a required option') )?>', function(v) {
                       var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                       for (var i=0; i < dateTimeParts.length; i++) {
                           if (dateTimeParts[i].value == "") return false;
                       }
                       return true;
                    }]
            ]
            );
    <?php else: ?>
            Validation.add(
                'validate-datetime-<?php echo $_optionId ?>',
                '<?php echo $this->jsQuoteEscape( Mage::helper('catalog')->__('Field is not complete') )?>',
                function(v) {
                    var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                    var hasWithValue = false, hasWithNoValue = false;
                    var pattern = /day_part$/i;
                    for (var i=0; i < dateTimeParts.length; i++) {
                       if (! pattern.test(dateTimeParts[i].id)) {
                           if (dateTimeParts[i].value === "") {
                               hasWithValue = true;
                           } else {
                               hasWithNoValue = true;
                           }
                       }
                    }
                    return hasWithValue ^ hasWithNoValue;
                }
            );
    <?php endif; ?>
        //]]>
        </script>
    </div>
</dt>
