<?php
/**
 * Created by PhpStorm.
 * User: Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * Date: 23.10.2018
 *
 */

/**
 * Class Egovs_Captcha_Model_Icon
 *
 * @category  Egovs
 * @package   Egovs_Captcha
 * @author    Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright Copyright (c) 2018 B3 IT Systeme GmbH - https://www.b3-it.de
 * @license   http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
class Egovs_Captcha_Model_Icon extends Egovs_Captcha_Model_Abstract
    implements Mage_Captcha_Model_Interface
{
    /**
     * Generates captcha
     *
     * @return void
     */
    public function generate() {
        // TODO: Implement generate() method.
    }

    /**
     * Checks whether word entered by user corresponds to the one generated by generate()
     *
     * @param string $word
     *
     * @return void
     */
    public function isCorrect($word) {
        // TODO: Implement isCorrect() method.
    }

    /**
     * Get Block Name
     *
     * @return string
     */
    public function getBlockName() {
        // TODO: Implement getBlockName() method.
    }
}
