<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2017 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Calendar localization script. Should be put into page header.
 * Replaced with jQueryMobile-Datepicker
 *
 * @see Mage_Core_Block_Html_Calendar
 */
?>
