<?php if($this->show()){?>
<fieldset id="product-options-wrapper" class="product-options">
<?php // Auswählen von Zeiträumen?>
<?php if($this->showSelect()){?>
    <dl class="last">
            <dt><label><?php echo $this->__('Select Periode')?><span class="required">&nbsp;*</span></label></dt>
	<dd class="last">
    <select  title="" class=" required-entry product-custom-option" id="periode" id="periode">
    	<option price="" value="">-- Bitte wählen --</option>
    	<?php foreach($this->getPerioden() as $periode) {?>
    		<option price="<?php echo $this->getPrice($periode)?>" finalprice="<?php echo $this->getFormatedFinalPrice($periode)?>" value="<?php echo $periode->getEntityId()?>"><?php echo $periode->getLabel()?>&nbsp; +<?php echo $this->getFormatedPeriodePrice($periode)?></option>
    	<?php }?>
    
    	</select>
    	</dd>
        </dl>
            <p class="required">* <?php echo $this->__('required Fields')?></p>
<?php }?>



<?php // Anzeigen von Zeiträumen?>
<?php if($this->showInfo()){?>
	<dl class="last">
            <dt><label><?php echo $this->__('Periode')?></label></dt>
	<dd class="last">
    
    	<?php foreach($this->getPerioden() as $periode) {?>
    		<input id="periode" type="hidden" value="<?php echo $periode->getEntityId()?>"/><?php echo $periode->getLabel()?>&nbsp; <?php echo $this->getFormatedFinalPrice($periode)?>
    	<?php }?>
    	</dd>
        </dl>
         
    
<?php }?>


</fieldset>
<?php }?>
