<?php
/**
 * @category   design
 * @package    Egov
 * @copyright  Copyright (c) 2018 B3 IT Systeme GmbH (http://www.b3-it.de)
 */
?>
<?php if ($this->getTotals()): ?>
    <?php !$_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
	<tbody>
    <?php echo $this->renderTotals(null, $_colspan); // Zwischensumme, Versand, MwSt. ?>
	</tbody>
	<tfoot>
    <?php echo $this->renderTotals('footer', $_colspan); // Grand-Totals ?>
	</tfoot>
<?php endif; ?>
