<?php
/**
 * SEPA Lastschriftverfahren Form-Block
 * 
 * @category	Egovs
 * @package    	Egovs_SepaDebit
 * @author		Frank Rochlitzer <f.rochlitzer@trw-net.de>
 * @copyright	Copyright (c) 2013 EDV Beratung Hempel
 * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
/* @var $this Egovs_SepaDebitBund_Block_Form */
?>
<?php if($this->hasMandate()):?>
		<div class="box-content">
            <div class="col-1">
                <h4><?php echo $this->__('Existing SEPA Mandate') ?></h4>
                <?php echo $this->getChildHtml('info'); ?>
                </div>
            </div>
            <br/>
<?php endif;?>
<form id="multishipping-billing-form" method="post" action="<?php echo $this->getActionUrl() ?>">      
         <div class="box-content">
            <div class="col-1">
                <h4><?php echo $this->__('Change SEPA Mandate') ?></h4>
                <?php echo $this->getChildHtml('form'); ?>
                </div>
            </div>

<div class="buttons-set">
    <a class="button" href="<?php echo $this->getUrl('customer/account/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a>
    <button type="submit" class="button"><span><span><?php echo $this->__('Save Mandate') ?></span></span></button>
</div>
</form>   


