<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if( Mage::getSingleton("customer/session")->isLoggedIn() ) : ?>
    <a href="<?php echo Mage::getUrl('customer/account/logout'); ?>"
       id="egov-account-logout"
       class="skip-link skip-logout"
       onclick="window.location.href='<?php echo Mage::getUrl('customer/account/logout'); ?>';">
        <span class="icon egov-logout"></span>
        <span class="label"><?php echo $this->__('Logout'); ?></span>
    </a>
<?php else : ?>
    <a href="<?php echo Mage::getUrl('customer/account/login'); ?>"
       id="egov-account-login"
       class="skip-link skip-login"
       onclick="window.location.href='<?php echo Mage::getUrl('customer/account/login'); ?>';">
        <span class="icon egov-login"></span>
        <span class="label"><?php echo $this->__('Login'); ?></span>
    </a>
<?php endif; ?>