<?php
/**
 * Created by PhpStorm.
 * User: Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * Date: 14.09.2018
 *
 */

/**
 * Class Egovs_Paymentbase_Block_Adminhtml_Sales_IncomingPayments_View_Tabs
 *
 * @category  Egovs
 * @package   Egovs_Paymentbase
 * @author    Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright Copyright (c) 2018 B3 IT Systeme GmbH - https://www.b3-it.de
 * @license   http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
class Egovs_Paymentbase_Block_Adminhtml_Sales_IncomingPayments_View_Form extends Mage_Adminhtml_Block_Widget_Form
{
    protected function _construct()
    {
        parent::_construct();
    }

    protected function _prepareForm() {
        $form = new Varien_Data_Form(array(
                'id' => 'sales_incomingpayments_view_form',
                'action' => $this->getUrl('*/*/save', array('order_id' => $this->getRequest()->getParam('order_id'))),
                'method' => 'post',
                'enctype' => 'multipart/form-data'
            )
        );

        $form->setUseContainer(true);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}