<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();

// Anpassen der Start-Ebene, da die Kategorie-Nav eine Hard geschrieben Ober-Navigation hat
$childLevel = is_null($parentLevel) ? 1 : $parentLevel + 1;

$show_all_link = TRUE;

$counter = 1;
$childrenCount = $children->count();

$parentPositionClass = $menuTree->getPositionClass();
$itemPositionClassPrefix = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

foreach ($children as $child) {
    $child->setLevel($childLevel);
    $child->setIsFirst($counter == 1);
    $child->setIsLast($counter == $childrenCount);
    $child->setPositionClass($itemPositionClassPrefix . $counter);

    $file_name = $child->getUrl();
    $file_info = pathinfo($file_name);
    $file_id   = strtolower( basename( $file_name, '.' . $file_info['extension'] ) );

    $outermostClassCode = 'level'. $childLevel;
    $_hasChildren = ($child->hasChildren()) ? 'has-children' : '';

    if ( $childLevel == 1 ) {
        // First Level => Arrow append
        $_cssAppend = ' egov-arrow-main-closed';
    }
    else {
        // First Level => Arrow first
        $_cssAppend = ' egov-arrow-sub-closed';
    }

    $html .= '<li id="' . $file_id . '" '. $this->_getRenderedMenuItemAttributes($child) .'>';

    $html .= '<a href="'. $child->getUrl() .'" data-category-count="" class="'. $outermostClassCode .' '. $_hasChildren . $_cssAppend .'">'.
             $this->escapeHtml($this->__($child->getName())) .'</a>';

    if (!empty($childrenWrapClass)) {
        $html .= '<div class="'. $childrenWrapClass .'">';
    }

    $nextChildLevel = $childLevel + 1;

    if (!empty($_hasChildren)) {
        $html .= '<ul id="sub-' . $file_id . '" class="level'. $childLevel .'">';

        if ($show_all_link == TRUE) {
            $html .= '<li id="all-' . $file_id . '" class="level'. $nextChildLevel .' view-all">';
            $html .=     '<a class="level'. $nextChildLevel .'" href="'. $child->getUrl() .'">';
            $html .=         $this->__('View All') . ' ' . $this->escapeHtml($this->__($child->getName()));
            $html .=     '</a>';
            $html .= '</li>';
        }

        $html .=     $this->render($child, $childrenWrapClass);
        $html .= '</ul>';
    }

    if (!empty($childrenWrapClass)) {
        $html .= '</div>';
    }

    $html .= '</li>';

    $counter++;
}

return $html;
