<?php
/**
 * Template für IconCaptcha Plugin - jQuery & PHP
 * https://github.com/fabianwennink/IconCaptcha-Plugin-jQuery-PHP
 *
 * @category   	Egovs
 * @package    	Egovs_Captcha
 * @author 		Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright  	Copyright (c) 2011-2018 B3 IT Systeme GmbH - http://www.b3-it.de
 * @license		http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$_store = Mage::app()->getStore();
?>
<div id="captcha-holder" class="captcha-holder"></div>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>egovs/captcha/icon-captcha.min.js" type="text/javascript"></script>
<script async type="text/javascript">
    $j('.captcha-holder').iconCaptcha({
        "captchaAjaxFile"       : "<?php echo $this->helper('egovscaptcha')->getIconCaptchaUrl(); ?>",
        "captchaTheme"          : "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_theme' , $_store); ?>",
        "captchaFontFamily"     : "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_fontfamily' , $_store); ?>",
        "captchaClickDelay"     : <?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_clickdelay' , $_store); ?>,
        "captchaHoverDetection" : <?php echo (Mage::getStoreConfig('customer/captcha/iconcaptcha_hoverdetection' , $_store) == '1' ? 'true' : 'false'); ?>,
        "enableLoadingAnimation": <?php echo (Mage::getStoreConfig('customer/captcha/iconcaptcha_loadinganimation' , $_store) == '1' ? 'true' : 'false'); ?>,
        "loadingAnimationDelay" : <?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_animationdelay' , $_store); ?>,
        "showCredits"           : "disabled",
        "requestIconsDelay"     : <?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_requesticonsdelay' , $_store); ?>,
        "captchaMessages": {
            "header" : "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_captchaheader' , $_store); ?>",
            "correct": {
                "top"   : "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_correcttitle' , $_store); ?>",
                "bottom": "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_correctsubtitle' , $_store); ?>"
            },
            "incorrect": {
                "top"   : "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_incorrecttitle' , $_store); ?>",
                "bottom": "<?php echo Mage::getStoreConfig('customer/captcha/iconcaptcha_incorrectsubtitle' , $_store); ?>"
            }

        }
    })
    .bind('init.iconCaptcha', function(e, id) {
    })
    .bind('refreshed.iconCaptcha', function(e, id) {
    })
    .bind('success.iconCaptcha', function(e, id) {
    })
    .bind('error.iconCaptcha', function(e, id) {
    });
</script>