<?php
/**
 * @category    design
 * @package     gka_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
        <div class="col2-set egov-account-login">

            <div class="page-title">
                <h1><?php echo $this->__('Login'); ?></h1>
            </div>

            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="col-2 registered-users">
                <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
                    <?php echo $this->getBlockHtml('formkey'); ?>
                    <h2><?php echo $this->__('Registered Editors') ?></h2>
                    <div class="content fieldset">
                        <p class="form-instructions">
                            <?php echo $this->__('Please log in!') ?>
                        </p>
			            
                        <ul class="form-list">
                            <li>
                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="email" autocapitalize="none" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
                                </div>
                            </li>
                            <li>
                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <li>
                            </li>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        <span class="required">
                            <?php echo $this->__('* Required Fields') ?>
                        </span>
                        <span class="securityLabel">
			              <?php if( Mage::app()->getFrontController()->getRequest()->isSecure() ): ?>
				            <img src="<?php echo $this->getSkinUrl('images/litessl_tl_trans.gif'); ?>" alt="<?php echo $this->__('Certified safety - Positive SSL Label'); ?>" title="<?php echo $this->__('Positive SSL'); ?>" />
			              <?php endif; ?>
			            </span>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2">
                            <?php echo $this->__('Login') ?>
                        </button>
                        <a class="button" href="<?php echo $this->getForgotPasswordUrl() ?>">
                            <?php echo $this->__('Forgot Your Password?') ?>
                        </a>
                    </div>
                </form>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
