<?php
/**
 * SEPA Lastschriftverfahren Form-Block
 *
 * @category	Egovs
 * @package    	Egovs_SepaDebitsax
 * @author		Frank Rochlitzer <f.rochlitzer@trw-net.de>
 * @copyright	Copyright (c) 2013-2014 EDV Beratung Hempel
 * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
/* @var $this Egovs_SepaDebitSax_Block_Form */
?>

<fieldset class="form-list" style="min-width:660px;">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" >
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getCustomText()): ?>
                    <?php echo $this->getMethod()->getCustomText() ?><br />
                <?php endif; ?>
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="iban"><?php echo $this->__('IBAN') ?> <span class="required">*</span></label><br />
                <input type="text" id="iban" name="payment[cc_number]" title="<?php echo $this->__('IBAN') ?>" class="input-text required-entry validate-debit-iban" value="<?php echo $this->getIban()?>" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="bic"><?php echo $this->__('BIC') ?> <?php if (!$this->getIbanOnly()) echo '<span class="required">*</span>'; ?></label><br />
                <input type="text" id="bic" name="payment[cc_type]" title="<?php echo $this->__('BIC') ?>" class="input-text <?php if (!$this->getIbanOnly()) echo "required-entry"; ?> validate-alphanum validate-debit-bic" value="<?php echo $this->getBic()?>" />
            </div>
        </li>

        <li>
            <div class="input-box">
                <label for="custom_owner"><?php echo $this->__('Debitor differs from banking account holder?') ?> </label>
                <?php if($this->getAccountholderDiffers()):?>
                	<input type="checkbox" id="custom_owner" name="payment[additional_information][custom_owner]" checked="checked" onchange="toggleFields(this)"/>
                <?php else :?>
                	<input type="checkbox" id="custom_owner" name="payment[additional_information][custom_owner]"  onchange="toggleFields(this)"/>
                <?php endif;?>
            </div>
        </li>

        <li>
            <div id="custom_accountholder_box" style="float:left;">
                <div class="block" style="width:277px; height:340px; margin-right:10px;">
	                  <div class="block-title">
	                      <h2><?php echo $this->__('Deviation account holder'); ?></h2>
	                  </div>
	                  <div class="block-content">
                        <div class="input-box">
                            <label for="custom_accountholder_name"><?php echo $this->__('account holder name/company authorised signatory') ?> <span class="required">*</span></label><br />
                            <input type="text" id="custom_accountholder_name" name="payment[additional_information][custom_accountholder_name]" title="<?php echo $this->__('account holder name/company name') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderFirstName()?>" maxlength="23" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_surname"><?php echo $this->__('account holder surname/company name') ?> <span class="required">*</span></label><br />
                            <input type="text" id="custom_accountholder_surname" name="payment[additional_information][custom_accountholder_surname]" title="<?php echo $this->__('account holder surname/company authorised signatory') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderSurname()?>" maxlength="23" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_street"><?php echo $this->__('account holder street') ?> <span class="required">*</span></label><br />
                            <input type="text" id="custom_accountholder_street" name="payment[additional_information][custom_accountholder_street]" title="<?php echo $this->__('account holder street') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderStreet()?>" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_city"><?php echo $this->__('account holder city') ?> <span class="required">*</span></label><br />
                            <input type="text" id="custom_accountholder_city" name="payment[additional_information][custom_accountholder_city]" title="<?php echo $this->__('account holder city') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderCity()?>" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_zip"><?php echo $this->__('account holder zip') ?> <span class="required">*</span></label><br />
                            <input type="text" id="custom_accountholder_zip" name="payment[additional_information][custom_accountholder_zip]" title="<?php echo $this->__('account holder zip') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderZip()?>" />
                        </div>
            	          <div class="input-box">
	                              <label for="custom_accountholder_postbox"><?php echo $this->__('account holder postbox') ?> </label><br />
	                              <input type="text" id="custom_accountholder_postbox" name="payment[additional_information][custom_accountholder_postbox]]" class="input-text" value="<?php echo $this->getAccountholderPostofficeBox()?>" />
	                      </div>
                        <div class="input-box">
                            <label for="custom_accountholder_land"><?php echo $this->__('account holder land') ?> <span class="required">*</span></label><br />
                            <?php //echo $this->getCountriesHtmlSelect('custom_accountholder_land', 'payment[additional_information][custom_accountholder_land]'); ?>
                            <input type="text" id="custom_accountholder_land" name="payment[additional_information][custom_accountholder_land]" class="input-text" value="<?php echo $this->getAccountholderCountry()?>" />
                        </div>
                    </div>
	              </div>
            </div>

            <div id="debitor_box" style="float:left;">
                <div class="block" style="width:277px; height:360px;">
	                  <div class="block-title">
	                      <h2><?php echo $this->__('Details Debitor'); ?></h2>
	                  </div>
	                  <div class="block-content">
            	          <div class="input-box">
	                          <label for="debitor_firstname"><?php echo $this->__('Debitor Firstname/company authorised signatory') ?> <span class="required">*</span></label><br />
	                          <input type="text" id="debitor_firstname" name="payment[additional_information][debitor_firstname]" class="input-text required-entry" value="<?php echo $this->getDebitorFirstName()?>" />
	                      </div>
            	          <div class="input-box">
	                          <label for="debitor_surname"><?php echo $this->__('Debitor Surname/company name') ?> <span class="required">*</span></label><br />
	                          <input type="text" id="debitor_surname" name="payment[additional_information][debitor_surname]" class="input-text required-entry" value="<?php echo $this->getDebitorSurName()?>" />
	                      </div>
            	          <div class="input-box">
	                          <label for="debitor_street"><?php echo $this->__('Debitor Street') ?><span class="required">*</span> </label><br />
	                          <input type="text" id="debitor_street" name="payment[additional_information][debitor_street]" class="input-text required-entry" value="<?php echo $this->getDebitorStreet()?>" />
	                      </div>
            	          <div class="input-box">
	                          <label for="debitor_city"><?php echo $this->__('Debitor City') ?> <span class="required">*</span></label><br />
	                          <input type="text" id="debitor_city" name="payment[additional_information][debitor_city]" class="input-text required-entry" value="<?php echo $this->getDebitorCity()?>" />
	                      </div>
	                      <div class="input-box">
	                          <label for="debitor_zip"><?php echo $this->__('Debitor ZIP') ?> <span class="required">*</span></label><br />
	                          <input type="text" id="debitor_zip" name="payment[additional_information][debitor_zip]" class="input-text required-entry" value="<?php echo $this->getDebitorZip()?>" />
	                      </div>
	                      <div class="input-box">
	                          <label for="debitor_postbox"><?php echo $this->__('Debitor Postbox') ?> </label><br />
	                          <input type="text" id="debitor_postbox" name="payment[additional_information][debitor_postbox]" class="input-text" value="<?php echo $this->getDebitorPostofficeBox()?>" />
	                      </div>
	                      <div class="input-box">
	                          <label for="debitor_country"><?php echo $this->__('Debitor Country') ?> <span class="required">*</span></label><br />
	                          <?php //echo $this->getCountriesHtmlSelectValue('debitor_country', 'payment[additional_information][debitor_country]', $this->getDebitorCountry()); ?>
	                          <input type="text" id="debitor_country" name="payment[additional_information][debitor_country]" class="input-text" value="<?php echo $this->getDebitorCountry()?>" />
	                      </div>
                    </div>
	              </div>
            </div>
        </li>

		<!-- <li>
            <div class="input-box">
                <label for="abweichender_kontoinhaber"><?php echo $this->__('Deviation from account holder') ?> </label><br />
                <input type="text" id="abweichender_kontoinhaber" name="payment[additional_information][abweichender_kontoinhaber]" title="<?php echo $this->__('Deviation from account holder') ?>" class="input-text " value="" />
            </div>
		</li> -->

		<li>
            <div class="input-box">
                <label for="sequence_type_frst"><?php echo $this->__('Use mandate multiple times') ?> </label>
                <input type="radio" style="width: 25px; float: right" id="sequence_type_frst" name="payment[additional_information][sequence_type]" title="<?php echo $this->__('Use mandate multiple times') ?>" class="input-text " value="<?php echo Egovs_Paymentbase_Model_Webservice_Types_SepaMandat::SEQUENCE_TYPE_FRST ?>" checked="checked" <?php if (!$this->getAllowOneoff()): ?>disabled="disabled"<?php endif; ?>/>
            </div>
            <br />
            <div class="input-box">
                <label for="sequence_type_ooff"><?php echo $this->__('Use mandate one times') ?> </label>
                <input type="radio" style="width: 25px; float: right" id="sequence_type_ooff" name="payment[additional_information][sequence_type]" title="<?php echo $this->__('Use mandate one times') ?>" class="input-text " value="<?php echo Egovs_Paymentbase_Model_Webservice_Types_SepaMandat::SEQUENCE_TYPE_OOFF ?>" <?php if (!$this->getAllowOneoff()): ?>disabled="disabled"<?php endif; ?> />
            </div>
		</li>
		<li>
			<div><?php echo $this->getAgreementText(); ?></div>
		</li>
	</ul>
		<?php if ($this->getMethod()->getEmailSettings()): ?>
    	<?php echo $this->getMethod()->getEmailSettings(); ?>
    	<br /><br />
    <?php endif; ?>

    <?php if ($this->getMethod()->getCustomText()): ?>
        <?php echo $this->getMethod()->getCustomText() ?><br />
    <?php endif; ?>
</fieldset>

<script type="text/javascript">
<!--
	/*
	 * http://stackoverflow.com/questions/15027613/magento-prototype-custom-validation
	 */
	var lngg = 1;
	var baseUrl = '<?php echo Mage::getBaseUrl('js').'egovs/sepa'; ?>';
	if(Validation) {
		Validation.addAllThese([
			['validate-debit-bic', '<?php echo Mage::helper('paymentbase')->__('BIC must be either 8 or 11 characters long') ?>', function(v, r) {
				return v.length == 8 || v.length == 11 || v.length == 0;
			}],
			['validate-debit-iban', '<?php echo Mage::helper('paymentbase')->__('IBAN not valid.') ?>', function(v, r) {
				res = checkibancore(v);
				return res == 0 ? false : true;
			}],
			['validate-alphanum_ws', '<?php echo Mage::helper('paymentbase')->__('Please use only letters (a-z or A-Z), numbers (0-9) or whitespaces in this field. No other characters are allowed.') ?>', function(v) {
                return Validation.get('IsEmpty').test(v) ||  /^[a-zA-Z0-9 ]+$/.test(v) /*!/\W/.test(v)*/
            }],
		])
	}
//-->
</script>
<?php
/*
 * http://www.tbg5-finance.org/?ibandocs.shtml
 */
?>
<script charset="utf-8" src="<?php echo Mage::getBaseUrl('js').'egovs/sepa'?>/checkiban.js" type="text/javascript"></script>
<script type="text/javascript">
<!--
	var sepaDebitForm = new VarienForm('multishipping-billing-form');

function toggleFields(element) {
	$('custom_accountholder_box').toggle();
	$('account_holder').toggle();
}

document.observe("dom:loaded", function() {
	toggleFields(null);
});
//-->
</script>

 <?php if($this->getAccountholderDiffers()):?>
	                	<script type="text/javascript">
	                	toggleFields(this);
	                	</script>
	                <?php endif;?>
