<?php
/**
 * SEPA Lastschriftverfahren Form-Block
 *
 * @category	Egovs
 * @package    	Egovs_SepaDebitsax
 * @author		Frank Rochlitzer <f.rochlitzer@trw-net.de>
 * @copyright	Copyright (c) 2013-2014 EDV Beratung Hempel
 * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
/* @var $this Egovs_SepaDebitSax_Block_Form */

if(Mage::getStoreConfig('checkout/options/checkout_type') == Egovs_Checkout_Model_Checkouttype::TYPE_ONEPAGE) {
    $ul_status = ' style="display:none;"';
}
else {
    $ul_status = '';
}
?>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>"<?php echo $ul_status; ?>>
        <li class="single-line">
            <div class="input-box">
                <?php if ($this->getMethod()->getCustomText()): ?>
                    <?php echo $this->getMethod()->getCustomText() ?><br />
                <?php endif; ?>
            </div>
        </li>

        <li class="double-line">
            <div class="input-box">
                <label for="iban"><span class="required">*</span><?php echo $this->__('IBAN') ?> </label>
                <input type="text" id="iban" name="payment[cc_number]" title="<?php echo $this->__('IBAN') ?>" class="input-text required-entry validate-debit-iban" value="<?php echo $this->getIban()?>" onkeyup="cleanupIbanChars()" onblur="cleanupIbanChars()" />
            </div>
        </li>
        <li class="double-line no-right-space">
            <div class="input-box">
                <label for="bic"><?php echo $this->__('BIC') ?> <?php if (!$this->getIbanOnly()) echo '<span class="required">*</span>'; ?></label><br />
                <input type="text" id="bic" name="payment[cc_type]" title="<?php echo $this->__('BIC') ?>" class="input-text <?php if (!$this->getIbanOnly()) echo "required-entry"; ?> validate-alphanum validate-debit-bic" value="<?php echo $this->getBic()?>" />
            </div>
        </li>

        <li class="single-line">
            <div class="input-box">
                <?php
                  if($this->getAccountholderDiffers()) {
                      $checked = ' checked="checked"';
                  }
                  else {
                      $checked = '';
                  }
                ?>
                <input type="checkbox"
                       id="custom-owner"
                       name="payment[additional_information][custom_owner]"
                       onclick="toggleFields();"
                       <?php echo $checked; ?> />
                <label for="custom-owner"><?php echo $this->__('Debtor differs from bank account holder?') ?> </label>
            </div>
        </li>

        <li class="single-line">
            <div id="custom-accountholder-box">
                <div class="block">
	                  <div class="block-title">
	                      <h2><?php echo $this->__('Deviation account holder'); ?></h2>
	                  </div>
	                  <div class="block-content">
                        <div class="input-box">
                            <label for="custom_accountholder_name"><span class="required">*</span><?php echo $this->__('account holder name/company authorised signatory') ?></label>
                            <input type="text" id="custom_accountholder_name" name="payment[additional_information][custom_accountholder_name]" title="<?php echo $this->__('account holder name/company name') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderFirstName()?>" maxlength="23" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_surname"><span class="required">*</span><?php echo $this->__('account holder surname/company name') ?></label>
                            <input type="text" id="custom_accountholder_surname" name="payment[additional_information][custom_accountholder_surname]" title="<?php echo $this->__('account holder surname/company authorised signatory') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderSurname()?>" maxlength="23" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_street"><span class="required">*</span><?php echo $this->__('account holder street') ?></label>
                            <input type="text" id="custom_accountholder_street" name="payment[additional_information][custom_accountholder_street]" title="<?php echo $this->__('account holder street') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderStreet()?>" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_city"><span class="required">*</span><?php echo $this->__('account holder city') ?></label>
                            <input type="text" id="custom_accountholder_city" name="payment[additional_information][custom_accountholder_city]" title="<?php echo $this->__('account holder city') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderCity()?>" />
                        </div>
                        <div class="input-box">
                            <label for="custom_accountholder_zip"><span class="required">*</span><?php echo $this->__('account holder zip') ?></label>
                            <input type="text" id="custom_accountholder_zip" name="payment[additional_information][custom_accountholder_zip]" title="<?php echo $this->__('account holder zip') ?>" class="input-text required-entry" value="<?php echo $this->getAccountholderZip()?>" />
                        </div>
            	          <div class="input-box">
	                              <label for="custom_accountholder_postbox"><?php echo $this->__('account holder postbox') ?></label>
	                              <input type="text" id="custom_accountholder_postbox" name="payment[additional_information][custom_accountholder_postbox]]" class="input-text" value="<?php echo $this->getAccountholderPostofficeBox()?>" />
	                      </div>
                        <div class="input-box">
                            <label for="custom_accountholder_land"><span class="required">*</span><?php echo $this->__('account holder land') ?></label>
                            <?php //echo $this->getCountriesHtmlSelect('custom_accountholder_land', 'payment[additional_information][custom_accountholder_land]'); ?>
                            <input type="text" id="custom_accountholder_land" name="payment[additional_information][custom_accountholder_land]" class="input-text" value="<?php echo $this->getAccountholderCountry()?>" />
                        </div>
                    </div>
	              </div>
            </div>

            <div id="debitor-box">
                <div class="block">
	                  <div class="block-title">
	                      <h2><?php echo $this->__('Details Debitor'); ?></h2>
	                  </div>
	                  <div class="block-content">
            	          <div class="input-box">
	                          <label for="debitor_firstname"><span class="required">*</span><?php echo $this->__('Debitor Firstname/company authorised signatory') ?> </label>
	                          <input type="text" id="debitor_firstname" name="payment[additional_information][debitor_firstname]" class="input-text required-entry" value="<?php echo $this->getDebitorFirstName()?>" />
	                      </div>
            	          <div class="input-box">
	                          <label for="debitor_surname"><span class="required">*</span><?php echo $this->__('Debitor Surname/company name') ?> </label>
	                          <input type="text" id="debitor_surname" name="payment[additional_information][debitor_surname]" class="input-text required-entry" value="<?php echo $this->getDebitorSurName()?>" />
	                      </div>
            	          <div class="input-box">
	                          <label for="debitor_street"><span class="required">*</span><?php echo $this->__('Debitor Street') ?> </label>
	                          <input type="text" id="debitor_street" name="payment[additional_information][debitor_street]" class="input-text required-entry" value="<?php echo $this->getDebitorStreet()?>" />
	                      </div>
            	          <div class="input-box">
	                          <label for="debitor_city"><span class="required">*</span><?php echo $this->__('Debitor City') ?> </label>
	                          <input type="text" id="debitor_city" name="payment[additional_information][debitor_city]" class="input-text required-entry" value="<?php echo $this->getDebitorCity()?>" />
	                      </div>
	                      <div class="input-box">
	                          <label for="debitor_zip"><span class="required">*</span><?php echo $this->__('Debitor ZIP') ?> </label>
	                          <input type="text" id="debitor_zip" name="payment[additional_information][debitor_zip]" class="input-text required-entry" value="<?php echo $this->getDebitorZip()?>" />
	                      </div>
	                      <div class="input-box">
	                          <label for="debitor_postbox"><?php echo $this->__('Debitor Postbox') ?> </label>
	                          <input type="text" id="debitor_postbox" name="payment[additional_information][debitor_postbox]" class="input-text" value="<?php echo $this->getDebitorPostofficeBox()?>" />
	                      </div>
	                      <div class="input-box">
	                          <label for="debitor_country"><span class="required">*</span><?php echo $this->__('Debitor Country') ?> </label>
	                          <?php //echo $this->getCountriesHtmlSelectValue('debitor_country', 'payment[additional_information][debitor_country]', $this->getDebitorCountry()); ?>
	                          <input type="text" id="debitor_country" name="payment[additional_information][debitor_country]" class="input-text" value="<?php echo $this->getDebitorCountry()?>" />
	                      </div>
                    </div>
	              </div>
            </div>
        </li>

		    <!--
		    <li>
            <div class="input-box">
                <label for="abweichender_kontoinhaber"><?php echo $this->__('Deviation from account holder') ?> </label>
                <input type="text" id="abweichender_kontoinhaber" name="payment[additional_information][abweichender_kontoinhaber]" title="<?php echo $this->__('Deviation from account holder') ?>" class="input-text " value="" />
            </div>
		    </li>
		    -->

		    <li class="single-line option-line">
            <div class="input-box option-field">
                <input type="radio" id="sequence_type_frst" name="payment[additional_information][sequence_type]" title="<?php echo $this->__('Use mandate multiple times') ?>" class="input-text " value="<?php echo Egovs_Paymentbase_Model_Webservice_Types_SepaMandat::SEQUENCE_TYPE_RCUR ?>" checked="checked" <?php if (!$this->getAllowOneoff()): ?>disabled="disabled"<?php endif; ?>/>
                <label for="sequence_type_frst"><?php echo $this->__('Use mandate multiple times') ?> </label>
            </div>
            <div class="input-box option-field">
                <input type="radio" id="sequence_type_ooff" name="payment[additional_information][sequence_type]" title="<?php echo $this->__('Use mandate one times') ?>" class="input-text " value="<?php echo Egovs_Paymentbase_Model_Webservice_Types_SepaMandat::SEQUENCE_TYPE_OOFF ?>" <?php if (!$this->getAllowOneoff()): ?>disabled="disabled"<?php endif; ?> />
                <label for="sequence_type_ooff"><?php echo $this->__('Use mandate one times') ?> </label>
            </div>
		    </li>
		  <?php if(strlen($this->getAgreementText())): ?>
		    <li>
			      <div id="sepa-agreement-text">
			          <?php echo $this->getAgreementText(); ?>
			      </div>
		    </li>
		  <?php endif ?>
	  </ul>
        <p class="required">
            <?php echo $this->__('* Required Fields') ?>
        </p>
		<?php if ($this->getMethod()->getEmailSettings()): ?>
    	<?php echo $this->getMethod()->getEmailSettings(); ?>
    	<br /><br />
    <?php endif; ?>

    <?php if ($this->getMethod()->getCustomText()): ?>
        <?php echo $this->getMethod()->getCustomText() ?><br />
    <?php endif; ?>
</fieldset>

<script type="text/javascript">
//<![CDATA[
	Translator.add('BIC must be either 8 or 11 characters long','<?php echo Mage::helper('paymentbase')->__('BIC must be either 8 or 11 characters long') ?>');
	Translator.add('IBAN not valid.','<?php echo Mage::helper('paymentbase')->__('IBAN not valid.') ?>');
	Translator.add('Please use only letters (a-z or A-Z), numbers (0-9) or whitespaces in this field. No other characters are allowed.','<?php echo Mage::helper('paymentbase')->__('Please use only letters (a-z or A-Z), numbers (0-9) or whitespaces in this field. No other characters are allowed.') ?>');

	/*
	 * http://stackoverflow.com/questions/15027613/magento-prototype-custom-validation
	 */
	var lngg = 1;
	var baseUrl = '<?php echo Mage::getBaseUrl('js').'egovs/sepa'; ?>';
	if(Validation) {
		Validation.addAllThese([
			['validate-debit-bic', '<?php echo Mage::helper('paymentbase')->__('BIC must be either 8 or 11 characters long') ?>', function(v, r) {
				return v.length == 8 || v.length == 11 || v.length == 0;
			}],
			['validate-debit-iban', '<?php echo Mage::helper('paymentbase')->__('IBAN not valid.') ?>', function(v, r) {
				res = checkibancore(v);
				return res == 0 ? false : true;
			}],
			['validate-alphanum_ws', '<?php echo Mage::helper('paymentbase')->__('Please use only letters (a-z or A-Z), numbers (0-9) or whitespaces in this field. No other characters are allowed.') ?>', function(v) {
                return Validation.get('IsEmpty').test(v) ||  /^[a-zA-Z0-9 ]+$/.test(v) /*!/\W/.test(v)*/
            }],
		])
	}
	// http://www.tbg5-finance.org/?ibandocs.shtml
	var sepaDebitForm = new VarienForm('multishipping-billing-form');

    function cleanupIbanChars() {
        var inputIban = $j('#iban').val();
        inputIban = inputIban.replace(/[^0-9A-Za-z]+/g, '');
        $j('#iban').val(inputIban);
    }

    $j(document).ready(function(){
        opcToggle();
        toggleFields();
    });

//document.observe("dom:loaded", function() {
//    toggleFields();
//});
//]]>
</script>

<?php if($this->getAccountholderDiffers()):?>
<script type="text/javascript">
//<![CDATA[
$j(document).ready(function(){
    toggleFields();
});
//]]>
</script>
<?php endif;?>
