<div class="egovs_agreement_text">
<ol class="checkout-agreements">
<?php foreach($this->getItems() as $item){?>
<li><div class="agreement-content"><?php echo $item['content'] ?></div></li>
<li><input class="checkbox" type="checkbox" id="agreementtext[<?php echo $item['value']?>]" id="agreementtext[<?php echo $item['value']?>]"value="">
<label for="agreementtext[<?php echo $item['value']?>]">
<?php echo $this->__('I agree') ?><span class="required">*</span></label> </li>

<?php }?>
</ol>
</div>
