<form id="solr_clear_form" action="<?php echo $this->helper('b3it_solr')->getSolrClearUrl() ?>" method="get">
    <fieldset class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Remove from Search'); ?></h4>
        </div>
        <div class="fieldset">
            <table class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Choose Store View'); ?></td>
                    <td class="value">
                        <select id="solr_clear_store" name="store">
                            <?php foreach($this->getStoreViews() as $store): ?>
                                <option value="<?php echo $store['value']; ?>"><?php echo $this->__($store['label']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Choose Type'); ?></td>
                    <td class="value">
                        <select id="solr_clear_type" name="type">
                            <?php foreach($this->getTypes() as $type): ?>
                                <option value="<?php echo $type['value']; ?>"><?php echo $this->__($type['label']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <button type="submit" class="button">
                            <span><?php echo $this->__('Remove'); ?></span>
                        </button>
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
</form>