<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php echo $this->getChildHtml('bitvmenu') ?>

<?php echo $this->getChildHtml('currency_switcher') ?>


<header id="header" class="page-header">

    <?php echo $this->getChildHtml('loadingMask') ?>

    <div class="page-header-container">
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>

        <div id="store-view-switcher" class="store-language-container">
            <?php echo $this->getChildHtml('store_language') ?>
        </div>

        <?php // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
              // See app.js for details ?>
        <!-- <div id="disabled-small-view-switcher" class="store-language-container"></div> -->

        <!-- Skip Links -->

        <div class="skip-links">
            <a href="#header-nav" class="skip-link skip-nav" data-target-element="#egov-nav" id="header-nav-menu" name="header-nav-menu">
                <span class="icon egov-list"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>

            <a href="#header-search" class="skip-link skip-search" id="header-nav-search" name="header-nav-search">
                <span class="icon egov-search"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>

            <div id="jumptargetheader" class="account-cart-wrapper">
              <?php if( Mage::helper('core')->isModuleEnabled('Egovs_ContextHelp') ): ?>
                <a href="javascript:void(0)" id="context-help" name="context-help" class="skip-link skip-help" onclick="showPopup()">
                    <span class="icon egov-help" title="<?php echo $this->__('Contexthelp'); ?>"> </span>
                </a>
              <?php endif; ?>
                <a href="<?php echo Mage::getBaseUrl(); ?>" id="home-link" name="home-link" class="skip-link skip-egov" onclick="window.location.href='<?php echo Mage::getBaseUrl(); ?>';">
                    <span class="icon egov-home"> </span>
                    <span class="label"><?php echo $this->__('Startup Page'); ?></span>
                </a>
                <!--
                <a href="javascript:void(0);" data-target-element="#egov-menu" class="skip-link skip-egov">
                    <span class="icon egov-home"> </span>
                    <span class="label">eGov-Menu</span>
                </a>
                -->

                <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" id="egov-account-menu" name="egov-account-menu" data-target-element="#header-account" class="skip-link skip-account">
                    <span class="icon egov-user"></span>
                    <span class="label"><?php echo $this->__('Account'); ?></span>
                </a>

                <!-- Cart -->
                <div class="header-minicart">
                    <?php echo $this->getChildHtml('minicart_head'); ?>
                </div>
            </div>
            <div class="welcome-header">
                <h1 class="header-position"><?php echo Mage::getStoreConfig('general/store_information/name'); ?></h1>
                <span class="welcome-msg">
                    <?php echo $this->getChildHtml('welcome') ?>
                    <?php echo $this->getChildHtml('accountLinks') ?>
                </span>
            </div>
        </div>

        <!-- Navigation -->
        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>

        <!-- Search -->
        <div id="header-search" class="skip-content">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>

        <!-- Account -->
        <div id="header-account" class="skip-content">
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>

        <!-- eGov-Menu -->
        <!--
        <div id="egov-menu" class="skip-content">
            <?php echo $this->getChildHtml('topEgovmenu') ?>
        </div>
        -->
    </div>
</header>
<?php echo $this->getChildHtml('topContainer'); ?>
