<div class="block block-links">
	<div class="block-title">
	 	<h2><?php echo $this->helper('infobox')->__('Informations')?></h2>
	</div>
	<div class="block-content">
		<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
			<li class="last"><a href="<?php echo $this->getUrl("bereitstellung");?>"><?php echo Mage::helper('infobox')->__('Allocation')?></a></li>
			<li class="last"><a href="<?php echo $this->getUrl("bestellbedingungen");?>"><?php echo Mage::helper('infobox')->__('Order Conditions')?></a></li>
			<li class="last"><a href="<?php echo $this->getUrl("contact");?>"><?php echo Mage::helper('infobox')->__('Contact')?></a></li>
			<li class=""><a href="<?php echo $this->getUrl("impressum");?>"><?php echo $this->helper('infobox')->__('Impress')?></a></li>
		</ul> 
	</div>
</div>
