<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php  $_order = $this->getOrder() ?>
<div id="order-buttons">
<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
    <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>"
       class="link-rss f-none">
        <?php echo $this->__('Subscribe to Order Status') ?>
    </a>
    <span class="separator">|</span>
<?php endif; ?>
<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
    <a href="<?php echo $this->getReorderUrl($_order) ?>"
       class="egov-reorder"
       title="<?php echo $this->__('Reorder') ?>"> </a>
    <span class="separator">|</span>
<?php endif ?>
    <a href="<?php echo $this->getPrintUrl($_order) ?>"
       class="egov-print"
       onclick="this.target='_blank';"
       title="<?php echo $this->__('Print Order') ?>"> </a>
<?php echo $this->getChildHtml(); ?>
</div>