<div class="block block-links">
	<div class="block-title">
		<h2><?php echo $this->helper('herausgeberbox')->__('Publisher')?></h2>
	</div>
	<div class="block-content">
		<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
			<li class=""><a href="<?php echo $this->getUrl("impressum");?>"><?php echo $this->helper('herausgeberbox')->__('Impress')?></a></li>
			<li class=""><a href="<?php echo $this->getUrl("contact");?>"><?php echo Mage::helper('herausgeberbox')->__('Contact')?></a></li>
			<li class=""><a href="<?php echo $this->getUrl("esignatur");?>"><?php echo Mage::helper('herausgeberbox')->__('eSignature')?></a></li>
			<li class=""><a href="<?php echo $this->getUrl("rechtlichehinweise");?>"><?php echo Mage::helper('herausgeberbox')->__('Legal Informations')?></a></li>
			<li class="last"><a href="<?php echo $this->getUrl("behoerdenwegweiser");?>"><?php echo Mage::helper('herausgeberbox')->__('Authority Finder')?></a></li>
		</ul> 
	</div>
</div>
