<?php
/**
 * 
 *-- TODO:: kurze Beschreibung --
 *
 *
 *
 * @category		Egovs
 * @package			Egovs_Ready
 * @name			Egovs_Ready_Block_Catalog_Product_Price
 * @author 			Frank Rochlitzer <f.rochlitzer@b3-it.de>
 * @copyright		Copyright (c) 2010 - 2015 B3 IT Systeme GmbH - http://www.b3-it.de
 * @license			http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 *
 */
?>
<?php
/**
 * @var $this Mage_Catalog_Block_Product_View_Abstract
 */
?>
<?php if ($this->getProduct()->getDeliveryTime() && Mage::getStoreConfigFlag('catalog/price/display_delivery_time_on_categories')): ?>
	<p class="delivery-time">
		<?php echo $this->__('Delivery Time') ?>: <?php echo $this->getProduct()->getDeliveryTime() ?>
	</p>
<?php endif ?>
