<div class="block block-links">
	 <div class="block-title">
		<h2><?php echo $this->helper('infobox')->__('Informations')?></h2>
	 </div>
	 <div class="block-content">
		<ul>
			<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
				<li class="last"><a href="<?php echo $this->getUrl("order_conditions");?>"><?php echo Mage::helper('infobox')->__('Order Conditions')?></a></li>
				<li class="last"><a href="<?php echo $this->getUrl("contacts");?>"><?php echo Mage::helper('infobox')->__('Contact')?></a></li>
				<li class=""><a href="<?php echo $this->getUrl("impressum");?>"><?php echo $this->helper('infobox')->__('Legal info')?></a></li>
			</ul>
		</ul>
	 </div>
 </div>
  <a class="back-button" href="http://www.gasification-freiberg.com/en/">
  <span class="backbuttonhead">Back to Conference</span>
  <span class="backbuttonlink">click to leave Shopsite</span>
 </a>

