<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * Ship to multiple address template
 *
 * @see Mage_Checkout_Block_Multishipping_Addresses
 */
?>
<?php $_egov_helper = Mage::helper('egovsbase/config'); ?>
<?php $_checkout_method = 'register' ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<!--Sprungziel Tastatursteuerung -->
<div id="jumptarget<?php echo $this->getNameInLayout();?>"></div>

<div class="checkout-newaddress">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Enter New Address') ?></h1>
    </div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
    	<?php echo $this->getBlockHtml('formkey'); ?>
        <input type="hidden" name="billing[address_id]" value="new" id="billing:address_id" />
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
        <input type="hidden" name="method" value="register" />

        <div class="fieldset wide no-space">
            <ul class="form-list">
                <li class="fields fullwide">
                    <?php echo $this->getBillingtext()?>
                </li>
                <li class="fields fullwide">
                    <?php
                        echo $this->getLayout()->createBlock('egovsbase/customer_widget_name')
                                  ->setMethod($_checkout_method)
                                  ->setObject($this->getFormData())
                                  ->setForceUseCustomerAttributes(true)->toHtml();
                    ?>
	   		    </li>
              <?php if(!$this->isCustomerLoggedIn()):?>
                <li class="fields halfwide">
                    <div class="field validate-email ">
                        <label for="email">
                            <span class="required">*</span>
                            <?php echo $this->__('Email Address') ?>
                        </label>
                        <input tabindex="5" type="text" id="billing:email" name="billing[email]" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry" maxlength="64" />
                    </div>
                </li>
              <?php endif ?>
              <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
    		  <?php if ($_dob->isEnabled()): ?>
				<li class="fields fullwide">
    		    	<?php echo $_dob->setDate ( $this->getQuote ()->getCustomerDob () )->setFieldIdFormat ( 'billing:%s' )->setFieldNameFormat ( 'billing[%s]' )->toHtml ()?>
    		    </li>
			  <?php endif; ?>

              <?php if($this->isFieldVisible('company')):?>
                <li class="fields fullwide">
                    <div class="field name-company">
                        <label for="company">
                            <?php echo $_egov_helper->getFieldRequiredHtml('company', $_checkout_method) ?>
                            <?php echo $this->__('Company') ?>
                        </label>
                        <input tabindex="6" type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $_egov_helper->isFieldRequired('company', $_checkout_method) ? 'required-entry' : ''; ?>" maxlength="27" />
                      	<?php if($this->isAdditionalCompanyVisible()):?>
	                        <input tabindex="6" type="text" id="billing:company2" name="billing[company2]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany2()) ?>" title="<?php echo $this->__('Company 2') ?>" class="input-text" maxlength="27" />
	                        <input tabindex="6" type="text" id="billing:company3" name="billing[company3]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany3()) ?>" title="<?php echo $this->__('Company 3') ?>" class="input-text" maxlength="27" />
                      	<?php endif; ?>
                    </div>
                </li>
              <?php endif; ?>

  		    	<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
	  	    	<?php if ($_taxvat->isEnabled()): ?>
                <li class="fields halfwide">
                    <div class="field">
                        <label for="vat_id">
                            <?php echo $_egov_helper->getFieldRequiredHtml('taxvat', $_checkout_method) ?>
                            <?php echo $this->__('VAT Number') ?>
                        </label>
                        <input tabindex="7" type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>" id="vat_id" class="input-text <?php echo $this->isFieldRequired("taxvat", $_checkout_method) ? 'required-entry' : ''?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
				<?php endif; ?>

              <?php if($this->isFieldVisible('street')):?>
                <li class="fields fullwide">
                    <div class="field">
                        <label for="billing:street1">
                            <?php echo $_egov_helper->getFieldRequiredHtml('street', $_checkout_method) ?>
                            <?php echo $this->__('Street Address') ?>
                        </label>
	                      <input tabindex="8" type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_egov_helper->isFieldRequired('street', $_checkout_method) ? 'required-entry' : ''; ?>" maxlength="22" />
                    <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
		    		            <input tabindex="8" type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text" maxlength="21" />
		                <?php endfor ?>
                    </div>
		    		    </li>
              <?php endif ?>
            </ul>
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
      		    <?php if($this->isFieldVisible('postcode')):?>
		    		    <li class="fields">
		    		        <div class="field">
		    		            <label for="billing:postcode">
		    		                <?php echo $_egov_helper->getFieldRequiredHtml('postcode', $_checkout_method) ?>
		    		                <?php echo $this->__('Zip/Postal Code') ?>
		    		            </label>
		    		            <input tabindex="9" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $_egov_helper->isFieldRequired('postcode', $_checkout_method) ? 'required-entry' : ''; ?>" maxlength="10" />
		    		        </div>
		    		    </li>
	    		    <?php endif ?>
		    		  <?php if($this->isFieldVisible('region')):?>
		    		    <li class="fields">
		    		        <div class="field" id="block-region">
		    		            <label for="billing:region">
		    		                <?php echo $_egov_helper->getFieldRequiredHtml('region', $_checkout_method) ?>
		    		                <?php echo $this->__('State/Province') ?>
		    		            </label>
		    		            <?php echo $this->getRegionHtmlSelect('billing') ?>
		    		        </div>
		    		    </li>
		    		  <?php endif ?>
              <?php if($this->isFieldVisible('telephone')):?>
                <li class="fields">
                    <div class="field">
                        <label for="billing:telephone">
                            <?php echo $_egov_helper->getFieldRequiredHtml('telephone', $_checkout_method) ?>
                            <?php echo $this->__('Telephone') ?>
                        </label>
                        <input tabindex="13" type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $_egov_helper->isFieldRequired('telephone', $_checkout_method) ? 'required-entry' : ''; ?>" id="billing:telephone" maxlength="32" />
                    </div>
                </li>
              <?php endif ?>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
		    		  <?php if($this->isFieldVisible('city')):?>
		    		    <li class="fields">
		    		        <div class="field">
		    		            <label for="billing:city">
		    		                <?php echo $_egov_helper->getFieldRequiredHtml('city', $_checkout_method) ?>
		    		                <?php echo $this->__('City') ?>
		    		            </label>
		    		            <input tabindex="10" type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text <?php echo $_egov_helper->isFieldRequired('city', $_checkout_method) ? 'required-entry' : ''; ?>" id="billing:city" maxlength="22" />
		    		        </div>
		    		    </li>
		    		  <?php endif ?>
		    		  <?php if($this->isFieldVisible('country_id')):?>
		    		    <li class="fields">
		    		        <div id="block-country" class="field">
		    		            <label for="billing:country_id">
		    		                <?php echo $_egov_helper->getFieldRequiredHtml('country_id', $_checkout_method) ?>
		    		                <?php echo $this->__('Country') ?>
		    		            </label>
		    		            <?php echo $this->getCountryHtmlSelect('billing') ?>
		    		        </div>
		    		    </li>
		    		  <?php endif ?>
              <?php if($this->isFieldVisible('fax')):?>
                <li class="fields">
                    <div class="field">
                        <label for="billing:fax">
                            <?php echo $_egov_helper->getFieldRequiredHtml('fax', $_checkout_method) ?>
                            <?php echo $this->__('Fax') ?>
                        </label>
                        <input tabindex="14" type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $_egov_helper->isFieldRequired('fax', $_checkout_method) ? 'required-entry' : ''; ?>" id="billing:fax" maxlength="32" />
                    </div>
                </li>
              <?php endif ?>
             </ul>
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
            <?php if(!$this->isCustomerLoggedIn()): ?>
              <?php if (!$this->isGuest()): ?>
                <li class="fields">
		    		        <div class="field">
		    		            <!-- Autocomplete-Bug von Firefox verhindern -> sonst wird ZIP als Username verwendet. -->
		    		            <input type="text" name="username" value="-" style="display: none"/>
		    		            <label for="billing:customer_password">
		    		                <span class="required">*</span>
		    		                <?php echo $this->__('Password') ?>
		    		            </label>
		    		            <input tabindex="15" type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" autocomplete="off" />
		    		        </div>
		    		    </li>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
                <li class="fields">
		    		        <div class="field">
		    		            <label for="billing:confirm_password">
		    		                <span class="required">*</span>
		    		                <?php echo $this->__('Confirm Password') ?>
		    		            </label>
	                      <input tabindex="16" type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" autocomplete="off" />
		    		        </div>
		    		    </li>
              <?php endif ?>
            <?php endif ?>
            </ul>
        </div>

        <div class="fieldset wide">
            <ul class="form-list">
		    		  <?php if ($this->canShip()): ?>
		    		    <li class="fields" id="new-address-use-for-shipping">
		    		        <div class="field">
		    		            <input tabindex="17" type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> class="radio" />
		    		            <label for="billing:use_for_shipping_yes">
		    		                <?php echo  $this->__('Ship to this address') ?>
		    		            </label>
		    		        </div>
		    		    </li>
		    		    <li class="fields" id="new-address-use-for-shipping-no">
		    		        <div class="field">
		    		            <input tabindex="18" type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no" value="0"<?php if (!$this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> class="radio" />
		    		            <label for="billing:use_for_shipping_no">
		    		                <?php echo $this->__('Ship to different address') ?>
		    		            </label>
		    		        </div>
		    		    </li>
  	            <?php if($this->isStorePickupAvailable()):?>
		    		    <li class="fields" id="new-address-use-for-shipping-option">
		    		        <div class="field">
		    		            <input tabindex="19" type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_option" value="2"<?php if ($this->isStorePickup()) {?> checked="checked"<?php }?>  class="radio" />
		    		            <label for="billing:use_for_shipping_option">
		    		                <?php echo $this->__('Store Pickup') ?>
		    		            </label>
		    		        </div>
		    		    </li>
		    		    <?php endif; ?>
		    		  <?php endif; ?>

		    		  <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
		    		    <li class="fields">
		    		        <div class="field">
		    		            <input tabindex="20" type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
		    		            <input type="hidden" name="billing[save_in_address_book]" value="1" />
		    		            <label for="billing:save_in_address_book">
		    		                <?php echo $this->__('Save in address book') ?>
		    		            </label>
		    		        </div>
		    		    </li>
		    		  <?php endif ?>

            </ul>
        </div>

        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    
        <div class="buttons-set">
            <a class="button" href="<?php echo $this->getBackUrl() ?>" tabindex="21">
                <span><?php echo $this->__('Back') ?></span>
            </a>
            <a class="button" href="<?php echo $this->getUrl() ?>" tabindex="22">
                <span><?php echo $this->__('Continue Shopping') ?></span>
            </a>
            <button  class="button" type="submit" tabindex="23">
                <span><?php echo $this->__('Continue') ?></span>
            </button>
        </div>
    
    </form>
</div>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    var billingForm = new VarienForm('co-billing-form');

    var TabData = {'block-region select': 11, 'block-country select': 12};
    setTabIndex(TabData);

    $j(document).ready(function(){
        $j('.name-firstname input').focus();
    });

//]]>
</script>