<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Multishipping checkout shipping template
 *
 * @see Mage_Checkout_Block_Multishipping_Shipping
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Please select your shipping address') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="shipping_method_form">
    <input type="hidden" name="shipping[address_id]" value="new" id="shipping:address_id" />
    <div>
        <div class="fieldset wide">
            <ul class="form-list">
                <li class="fields fullwide">
                    <?php echo $this->getLayout()->createBlock('egovsbase/customer_widget_name')
                                    ->setObject($this->getAddress())
                                    ->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')
                                    ->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml();
                    ?>
                </li>

              <?php if(false): ?>
                <li class="fields halfwide">
                    <div class="input-box">
                        <label for="shipping:email">
                            <span class="required">*</span>
                            <?php echo $this->__('Email Address') ?>
                        </label>
                        <input tabindex="5" type="text" name="shipping[email]" id="shipping:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
              <?php endif ?>
            </ul>
        </div>

        <div class="fieldset wide no-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('company')):?>
                <li class="fields">
                    <div class="input-box">
                        <label for="shipping:company">
                            <?php echo $this->getFieldRequiredHtml('company')?>
                            <?php echo $this->__('Company') ?>
                        </label>
                        <input tabindex="6" type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->isFieldRequired('company') ? 'required-entry' : ''?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                </li>
              <?php endif ?>

              <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li class="fields halfwide">
                    <div class="input-box">
                        <label for="shipping:taxvat">
                            <?php echo $this->getFieldRequiredHtml('taxvat')?>
                            <?php echo $this->__('Taxvat') ?>
                        </label>
                        <input tabindex="7" type="text" id="shipping:taxvat" name="shipping[taxvat]" value="<?php echo $this->htmlEscape($this->getAddress()->getTaxvat()) ?>" title="<?php echo $this->__('Taxvat') ?>" class="input-text <?php echo $this->isFieldRequired("taxvat") ? 'required-entry' : ''?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                </li>
              <?php endif ?>
            </ul>
        </div>

        <div class="fieldset wide">
            <ul class="form-list">
              <?php if($this->isFieldVisible('street')):?>
                <li class="fields street-field">
                    <div class="field">
                        <label for="billing:street1">
                            <?php echo $this->getFieldRequiredHtml('street')?>
                            <?php echo $this->__('Street Address') ?>
                        </label>
	                      <input tabindex="8" type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $this->isFieldRequired('street') ? 'required-entry' : ''?>" maxlength="22" />
                    <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
		    		            <input tabindex="8" type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i+1)) ?>" class="input-text" maxlength="21" />
		                <?php endfor ?>
                    </div>
		    		    </li>
              <?php endif; ?>
            </ul>
        </div>

        <div class="fieldset">
            <ul class="form-list">
              <?php if($this->isFieldVisible('postcode')):?>
                <li class="fields">
                    <div class="input-box">
                        <label for="shipping:postcode">
                            <?php echo $this->getFieldRequiredHtml('postcode')?>
                            <?php echo $this->__('Zip/Postal Code') ?>
                        </label>
                        <input tabindex="9" type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->isFieldRequired('postcode') ? 'required-entry' : ''?>" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                </li>
              <?php endif; ?>
              <?php if($this->isFieldVisible('region')):?>
                <li class="fields">
                    <div class="input-box" id="block-region">
                        <label for="shipping:region">
                            <?php echo $this->getFieldRequiredHtml('region')?>
                            <?php echo $this->__('State/Province') ?>
                        </label>
                        <?php echo $this->getRegionHtmlSelect('shipping') ?>
                    </div>
                </li>
              <?php endif; ?>
             	<?php if($this->isFieldVisible('telephone')):?>
                <li class="fields">
                    <div class="input-box">
                        <label for="shipping:telephone">
                            <?php echo $this->getFieldRequiredHtml('telephone')?>
                            <?php echo $this->__('Telephone') ?>
                        </label>
                        <input tabindex="13" type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->isFieldRequired('telephone') ? 'required-entry' : ''?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>
        <div class="fieldset">
            <ul class="form-list">
              <?php if($this->isFieldVisible('city')):?>
                <li class="fields">
                    <div class="input-box">
                        <label for="shipping:city">
                            <?php echo $this->getFieldRequiredHtml('city')?>
                            <?php echo $this->__('City') ?>
                        </label>
                        <input tabindex="10" type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->isFieldRequired('city') ? 'required-entry' : ''?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                </li>
              <?php endif; ?>
              <?php if($this->isFieldVisible('country_id')):?>
                <li class="fields">
                    <div class="input-box" id="block-country">
                        <label for="shipping:country_id">
                            <?php echo $this->getFieldRequiredHtml('country_id')?>
                            <?php echo $this->__('Country') ?>
                        </label>
                        <?php echo $this->getCountryHtmlSelect('shipping') ?>
                    </div>
                </li>
              <?php endif; ?>
              <?php if($this->isFieldVisible('fax')):?>
                <li class="fields">
                    <div class="input-box">
                        <label for="shipping:fax">
                            <?php echo $this->getFieldRequiredHtml('fax')?>
                            <?php echo $this->__('Fax') ?>
                        </label>
                        <input tabindex="14" type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->isFieldRequired('fax') ? 'required-entry' : ''?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                    </div>
                </li>
              <?php endif ?>
            </ul>
        </div>

        <div class="fieldset wide">
            <ul class="form-list">
              <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                <li class="fields">
                    <input tabindex="15" type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                    <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                </li>
              <?php else:?>
                <li class="no-display">
                    <input type="hidden" name="shipping[save_in_address_book]" value="1" />
                </li>
              <?php endif;?>
            </ul>
        </div>
    </div>

    <p class="required"><?php echo $this->__('* Required Fields') ?></p>

    <div class="buttons-set">
        <a class="back-link egovslistbutton" href="<?php echo $this->getBackUrl() ?>" tabindex="16">
            <?php echo $this->__('Back') ?>
        </a>
        <a class="break-link egovslistbutton" href="<?php echo $this->getUrl() ?>" tabindex="17">
            <?php echo $this->__('Continue Shopping') ?>
        </a>
        <button  class="button" type="submit" tabindex="18">
            <span><?php echo $this->__('Continue') ?></span>
        </button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var TabData = {'name-prefix select': 1, 'name-firstname input': 2, 'name-middlename input': 3,
                   'name-lastname input': 4, 'block-region select': 11, 'block-country select': 12};
    setTabIndex(TabData);

    $j(document).ready(function(){
        $j('#name-firstname input').focus();
    });
//]]>
</script>