<?php
/**
 * @category   design_blank
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Your order has been received') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<h3>
    <span class="order_pre"><?php echo $this->__('Your order # is:') ?></span>
    <span class="order_number"><?php echo $this->getOrderId() ?></span>
</h3>

<?php if ($this->getKassenzeichen()): ?>
<h3>
    <span class="order_pre"><?php echo $this->__('Your Transaction Number is:') ?></span>
    <span class="order_number"><?php echo $this->getKassenzeichen() ?></span>
</h3>
<?php endif; ?>

<fieldset class="multiple-checkout">
    <div class="col2-set">
        <h3><?php echo $this->__('Billing Information') ?></h3>
        <div class="col-1">
            <?php $_address=$this->getBillingAddress() ?>
            <h4><?php echo $this->__('Billing Address') ?></h4>
            <address>
                <?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
            </address>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Payment Method') ?> </h4>
            <?php echo $this->getPaymentHtml() ?>
        </div>
    </div>
<?php if(!$this->isVirtual()):?>
    <h3><?php echo $this->__('Shipping Information') ?></h3>
    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <?php  $_address = $this->getShippingAddress() ?>
    <div class="col2-set">
        <div class="col-1">
            <h4><?php echo $this->__('Shipping to') ?></h4>
            <address>
                <?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
            </address>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Shipping Method') ?> </h4>
        <?php if($_rate=$this->getShippingAddressRate($_address)): ?>
            <div class="successview_shipping">
	              <?php echo $_rate->getCarrierTitle() ?> (<?php echo $_rate->getMethodTitle() ?>)
	              <?php $_excl = $this->getShippingPriceExclTax($_address); ?>
	              <?php $_incl = $this->getShippingPriceInclTax($_address); ?>
	          <?php if ($this->helper('tax')->displayShippingPriceExcludingTax()):?>
						    <?php echo sprintf('%s (%s)', $_excl, $this->__('Excl. Tax')); ?>
					  <?php endif;?>
					  <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()):?>
						    <?php echo sprintf('%s (%s)', $_incl, $this->__('Incl. Tax')); ?>
					  <?php endif;?>
					  <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
						    <?php echo sprintf('%s (%s %s)', $_excl, $this->__('Incl. Tax'), $_incl); ?>
					  <?php endif; ?>
            </div>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

    <div class="col1-wide">
        <table class="data-table" id="checkout-review-table">
            <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
			      <col />
			      <col width="80" />
			      <col width="80" />
			      <col width="10" />
			  <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			      <col width="80" />
			      <col width="80" />
			  <?php endif; ?>
			      <thead>
			          <tr>
			              <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
			              <th colspan="<?php echo $colspan ?>" class="a-center">
                              <?php echo $this->__('Price') ?><br />
                              <?php if ($_address->getTaxAmount() <= 0.009): ?>
                                  <?php echo sprintf('(%s)', $this->__('Tax Free')); ?>
                              <?php elseif( Mage::getStoreConfig('tax/cart_display/price') == 1 ): ?>
                                  <?php echo sprintf('(%s)', $this->__('Excl. Tax')); ?>
                              <?php elseif( Mage::getStoreConfig('tax/cart_display/price') == 2 ): ?>
                                  <?php echo sprintf('(%s)', $this->__('Incl. Tax')); ?>
                              <?php endif; ?>
                          </th>
			              <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
			              <th colspan="<?php echo $colspan ?>" class="a-center">
                              <?php echo $this->__('Subtotal') ?>
                              <?php if ($_address->getTaxAmount() <= 0.009): ?>
                                  <?php echo sprintf('(%s)', $this->__('Tax Free')); ?>
                              <?php elseif( Mage::getStoreConfig('tax/cart_display/price') == 1 ): ?>
                                  <?php echo sprintf('(%s)', $this->__('Excl. Tax')); ?>
                              <?php elseif( Mage::getStoreConfig('tax/cart_display/price') == 2 ): ?>
                                  <?php echo sprintf('(%s)', $this->__('Incl. Tax')); ?>
                              <?php endif; ?>
                          </th>
			          </tr>
			      <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			          <tr>
			              <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
			              <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			              <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
			              <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			          </tr>
			      <?php endif; ?>
			      </thead>
			      <tbody>
			      <?php foreach($this->getItems() as $_item): ?>
			          <?php echo $this->getItemHtml($_item)?>
			      <?php endforeach ?>
			      </tbody>
			  </table>

        <table id="checkout-review-totals-table" class="data-table">
            <?php echo $this->getChildHtml('totals'); ?>
        </table>
    </div>
</fieldset>

<div class="buttons-set">
    <a href="<?php echo $this->getUrl() ?>" class="button">
        <?php echo $this->__('Continue Shopping') ?>
    </a>
</div>
