<fieldset>
<h3>Customer</h3>
<p><?php echo $this->getCustomerTitle()?></p>
<input type="hidden" id="create_contract[customer_id]" value="<?php echo $this->getCustomer()->getId()?>"/>

<div id="create_contract_billing_adr">
<h3>Billing Address</h3>
<select id="create_contract[billing_adr]">
	<?php foreach ($this->getCustomerAddresses() as $adr):?>
	<option value="<?php echo $adr->getId()?>"><?php echo trim($adr->getCompany() ." ".$adr->getFirstname() ." ". $adr->getLastname())?></option>
	<?php endforeach;?>
</select>
</div>


<div id="create_contract_shipping_adr">
<h3>Shipping Address</h3>
<select id="create_contract[shipping_adr]">
	<?php foreach ($this->getCustomerAddresses() as $adr):?>
	<option value="<?php echo $adr->getId()?>"><?php echo trim($adr->getCompany() ." ".$adr->getFirstname() ." ". $adr->getLastname())?></option>
	<?php endforeach;?>
</select>
</div>

</fieldset>