<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>

<?php
$_use_ssl_logo  = Mage::getStoreConfig('design/login/ssl_logo_use', Mage::app()->getStore());
$_ssl_image     = Mage::getStoreConfig('design/login/ssl_logo', Mage::app()->getStore());
$_ssl_image_css = Mage::getStoreConfig('design/login/ssl_logo_style', Mage::app()->getStore());
$_ssl_alt       = $this->__( Mage::getStoreConfig('design/login/ssl_logo_alt', Mage::app()->getStore()) );
$_ssl_title     = $this->__( Mage::getStoreConfig('design/login/ssl_logo_title', Mage::app()->getStore()) );

$_is_https   = Mage::app()->getFrontController()->getRequest()->isSecure();
$_show_image = ( strlen($_ssl_image) ? Mage::getBaseUrl('media') . 'ssl_logo/' . $_ssl_image : $this->getSkinUrl('images/litessl_tl_trans.gif') );

$_show_ssl = false;
if ( ($_use_ssl_logo == 0) || ($_use_ssl_logo == 2 && $_is_https) ) {
    $_show_ssl = true;
}
$show_css = '';
if ( strlen($_ssl_image_css) && !empty($_ssl_image_css) ) {
    $show_css = ' style="' . $this->htmlEscape($_ssl_image_css) . '"';
}
?>

<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
<div class="col2-set dwd-account-login">

     <div class="page-title">
         <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                 <?php echo $this->__('Login or Create an Account') ?>
             <?php else: ?>
                 <?php echo $this->__('Login'); ?>
        <?php endif; ?></h1>
    </div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	  <!--Sprungziel Tastatursteuerung -->
	  <div id="jumptarget<?php echo $this->getNameInLayout();?>"></div>
	  <div class="col-1 new-users">
	  	  <form id="register-form" class="scaffold-form" action="<?php echo $this->getRegisterAction() ?>" method="post">
            <h2><?php echo $this->__('New Here?') ?></h2>
                <div class="content">
                    <p><?php echo $this->__("Mage_Customer::By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.") ?></p>
                </div>
                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send">
                        <?php echo $this->__('Create an Account') ?>
                    </button>
                </div>
                <input type="hidden" name="checkout_method" id="login:register" value="register" />
		    </form>
	  </div>
		<div class="col-2 registered-users">
		    <form id="login-form" class="scaffold-form" action="<?php echo $this->getPostAction() ?>" method="post">
		    <?php echo $this->getBlockHtml('formkey'); ?>
		        <h2><?php echo $this->__('Registered Customers') ?></h2>
		        <div class="content">
		            <p class="form-instructions">
                        <?php echo $this->__('If you have an account with us, please log in.') ?>
                    </p>
		            <div class="securityLabel"<?php echo $show_css; ?>>
                      <?php if ($_show_ssl): ?>
                        <img src="<?php echo $_show_image; ?>" alt="<?php echo $this->__($_ssl_alt); ?>" title="<?php echo $this->__($_ssl_title); ?>" />
                      <?php endif; ?>
                    </div>
			          <fieldset<?php if( $_secure != true ): ?> class="width"<?php endif; ?>>
				            <ul class="form-list">
		                    <li>
		                        <div class="input-box">
		                            <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label><br />
		                            <input type="email" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
		                        </div>
		                    </li>
		                    <li>
		                        <div class="input-box">
		                            <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label><br />
		                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
		                        </div>
		                    </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
		                </ul>
		                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
		            </fieldset>
	          </div>
    	      <div class="buttons-set">
    	          <a class="button" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" >
    	              <?php echo $this->__('Forgot your password?') ?>
    	          </a>
    	         <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2">
                     <?php echo $this->__('Login') ?>
                 </button>
    	      </div>
		    </form>
	  </div>
</div>
</div>