<div>
	<input id="periode_product" type="hidden" name="periode_product" value="<?php echo $this->getProduct()->getId();?>" />
	<table>
		<tr>
			<td><?php echo $this->__('Label')?><input id="periode_label" type="text" class="input-text" name="periode_label" value="" autocomplete="off"/></td>
			<td><?php echo $this->__('Type')?><input id="periode_type" type="text" class="input-text" name="periode_type" value="" autocomplete="off"/></td>
			<td><?php echo $this->__('From')?><input id="periode_from" type="text" class="input-text" name="periode_from" value="" autocomplete="off"/></td>
			<td><?php echo $this->__('To')?><input id="periode_to" type="text" class="input-text" name="periode_to" value="" autocomplete="off"/></td>
			<td><?php echo $this->__('Duration')?><input id="periode_duration" type="text" class="input-text" name="periode_duration" value="" autocomplete="off"/></td>
			<td><?php echo $this->__('Unit')?><input id="periode_unit" type="text" class="input-text" name="periode_unit" value="" autocomplete="off"/></td>
			<td><?php echo $this->__('Price')?><input id="periode_unit" type="text" class="input-text" name="periode_unit" value="" autocomplete="off"/></td>
			<td></td>
		</tr>
	</table>
</div>
<?php echo $this->getInputToDate();?>
