<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$_links = $this->getLinks();
$_index = 1;
$_count = count($_links);
?>
<div class="block block-account">
    <div class="block-title account-block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
        <?php foreach ($_links as $_link): ?>
            <?php $_last = ($_index++ >= $_count); ?>
            <?php if ($this->isActive($_link)): ?>
            <li class="current<?php echo ($_last ? ' last' : '') ?>">
                <a href="<?php echo $_link->getUrl() ?>">
                    <strong><?php echo $_link->getLabel() ?></strong>
                </a>
            </li>
            <?php else: ?>
            <li<?php echo ($_last ? ' class="last"' : '') ?>>
                <a href="<?php echo $_link->getUrl() ?>">
                    <?php echo $_link->getLabel() ?>
                </a>
            </li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
</div>


<script type="text/javascript">
    $j(document).ready(function(){
        $j('.account-block-title').toggleSingle();
    });
</script>