		<table class="massaction">
			<tbody style="background:none;">
				<tr>
					<td>
						<div class="right" style="width:auto;">
							<div class="entry-edit">
								<select style="width:auto;">
									<?php foreach($this->getValues() as $opt):?>
										<option value="<?php echo $opt['value']?>"><?php echo $opt['label']?></option>
									<?php endforeach;?>
								</select>
								<button class="scalable" onclick="addTableRow( $j(this) );" type="button" title="<?php echo Mage::helper('bkg_license')->__('Add')?>">
									<?php echo Mage::helper('bkg_license')->__('Add')?>
								</button>
							</div>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
