<?php
/**
 *  @var Bkg_MapSeries_Block_Product_View_Type_Mapseries_Map $this
 */
?>
<div id="map">

</div>
   <?php 
   //var_dump($this->getComposit());
   //$this->getComposit()->getOpenLayer();
   //die();
   ?>
   <script>
   $j(function() {
     <?php echo $this->getComposit()->getOpenLayer(); ?>

     // set style
      vector.setStyle(function(feature, resolution) {
          j = $j('#qty-' + feature.get('sku'));
          return new ol.style.Style({
              stroke: new ol.style.Stroke({
                  color: 'rgba(0, 0, 0, 1.0)',
                  width: 1
              }),
              fill: new ol.style.Fill({
                  color: j.length == 0 ? 'rgba(255, 0, 0, 0.25)' : j.val() == 0 ? 'rgba(0, 0, 255, 0.25)' : 'rgba(0, 255, 0, 0.25)',
              }),
          });
      });

      var map = new ol.Map({
        layers: layers,
        controls: ol.control.defaults(),
        target: document.getElementById('map'),
        view: new ol.View({
          center: ol.proj.fromLonLat([13.73836, 51.049259]),
          //projection: ol.proj.get("EPSG:31467"),
          //maxZoom: 19,
          zoom: 6
        })
      });

      var dialogFunction = function(list) {
    	  str = "<table title='Füge hinzu?'>";
          list.forEach( function(f) {
        	  var sku = f.get('sku');
        	  var price = $j("#price-" + sku + " .price").text();
        	  var name = $j("#name-" + sku).text();
              str += "<tr>";

              str += "<td><label><input id='confirm-chk-"+ sku +"' type='checkbox' checked='checked' name='ids' value='" + sku + "' />" + name + "</td>";
              str += "<td>" + price + "</td>";
              str += "<td><input id='confirm-qty-" + sku + "' type='number' value='1' min='0' /></td>";
              
              str += "</tr>";
          });
          str += "</table>";
          $j(str).dialog({
              resizable: false,
              height: "auto",
              width: 400,
              modal: true,
              buttons: {
                Confirm: function() {
                  $j( this ).find(":checked").each(function(index) {
                      sku = $j(this).val();

                      v = $j('#confirm-qty-' + sku).val();
                      qty = $j('#qty-' + sku);
                      qty.val(function(i, oldval) {
                          return parseInt(oldval, 10) + parseInt(v, 10);
                      });
                      // call changed so the map get updated
                      qty.change();
                  });

                  // need to destroy so it is removed from code
                  $j( this ).dialog( "destroy" ).remove();
                },
                Cancel: function() {
                  // need to destroy so it is removed from code
                  $j( this ).dialog( "destroy" ).remove();
                }
              }
            });
      };
      
       var select = new ol.interaction.Select({
    	   multi: true
       });
       
       select.on('select', function(e) {
    	   var list = [];
    	   e.target.getFeatures().forEach(function(f) {
    		   var sku = f.get('sku');
               var j = $j("#qty-" + sku);
               if (j.length != 0) {
                 list.push(f);
               }
           });
    	   e.target.getFeatures().clear();
    	   if (list.length <= 0) {
               return;
           }
    	   dialogFunction(list);
       });

      map.addInteraction(select);
      
      var dragBox = new ol.interaction.DragBox();
      map.addInteraction(dragBox);
      dragBox.on('boxend', function(e) {

          var extent = e.target.getGeometry().getExtent();
          var list = [];
          vector.getSource().forEachFeatureIntersectingExtent(extent, function(f) {
        	  var sku = f.get('sku');
              var j = $j("#qty-" + sku);
              if (j.length != 0) {
              	list.push(f);
              }
          });

          if (list.length <= 0) {
              return;
          }
          dialogFunction(list);
      });
      // clear selection when drawing a new box and when clicking on the map
      dragBox.on('boxstart', function() {
        //selectedFeatures.clear();
      });

      map.addControl(new ol.control.OverviewMap()); // TODO lol? 
      map.addControl(new ol.control.ZoomSlider());
      map.addControl(new ol.control.ScaleLine());

      map.addControl(new buttonCtrl({
    	  text: "+",
    	  classname: "ol-addall",
    	  callback: function(b) {
        	  qty = $j('#super-product-table .qty');
        	  qty.val(function(i, oldval) {
            	  // increase value by one
                  return parseInt(oldval, 10) + 1;
              });
              qty.change();
    	  }
      }));
      map.addControl(new buttonCtrl({
    	  text: "C",
    	  classname: "ol-clearall",
    	  callback: function(b) {
        	  qty = $j('#super-product-table .qty');
        	  qty.val('0');
              qty.change();
    	  }
      }));
      //map.addControl(new ol.control.MousePosition({
      //  coordinateFormat: function(coord) { return ol.coordinate.toStringHDMS(ol.proj.toLonLat(coord),1); }
      //}));

      $j('#super-product-table').delegate('input.qty', 'change', function( e ) {
          sku = e.target.id.slice(4);
    	  vector.getSource().forEachFeature(function(f) {
        	  if (f.get("sku") == sku) {
            	  f.changed(); // invalidate to redraw again
            	  return true;
        	  }
        	  return false;
    	  });
      });
    });
    </script>