<div class="block block-links">
	 <div class="block-title">
	 <h2>Herausgeberbox</h2>
	 </div>
	 <div class="block-content">

	 <ul>


<?php $_links = $this->getLinks(); ?>

<?php if(count($_links)>0): ?>
<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>

<li class=""><a href="<?php echo $this->getUrl("impressum");?>">Impressum</a></li>
<li class="last"><a href="<?php echo $this->getUrl("contact");?>">Kontakt</a></li>
<li class="last"><a href="<?php echo $this->getUrl("esignatur");?>">eSignatur</a></li>
<li class="last"><a href="<?php echo $this->getUrl("rechtlichehinweise");?>">Rechtliche Hinweise</a></li>
<li class="last"><a href="<?php echo $this->getUrl("behoerdenwegweiser");?>">Beh&ouml;rdenwegweiser</a></li>

<!--
<li class=""><a href="<?php echo $this->getUrl("agb");?>">AGB</a></li>
<li class=""><a href="<?php echo $this->getUrl("versandkosten");?>">Versandkosten</a></li>
<li class=""><a href="<?php echo $this->getUrl("rabatt");?>">Rabattregelungen</a></li>

<li class=""><a href="<?php echo $this->getUrl("widerruf");?>">Widerruf</a></li>
<li class=""><a href="<?php echo $this->getUrl("lieferung");?>">Lieferung</a></li>
<li class=""><a href="<?php echo $this->getUrl("zahlung");?>">Zahlungsarten</a></li>
<li class=""><a href="<?php echo $this->getUrl("datenschutz");?>">Datenschutz</a></li>
<li class=""><a href="<?php echo $this->getUrl("bestellung");?>">Bestellvorgang</a></li>
-->
<?php 
/*
foreach($_links as $_link): ?>
        <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
    <?php endforeach; 
*/
?>



</ul>
<?php endif; ?>


	 
	 </ul>
	 </div>

 </div>


