<?php
/**
 * Merzettel - Anlegen - Block
 *
 * @category   	Sid
 * @package    	Sid_Wishlist
 * @author 		Frank Rochlitzer <f.rochlitzer@trw-net.de>
 * @copyright  	Copyright (c) 2012 - 2016 B3 IT Systeme GmbH - http://www.b3-it.de
 * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
?>
<?php
/**
 * Template zum erstellen eines neuen Merkzettels
 *
 * @see Sid_Wishlist_Block_Wishlist_New
 */
/** @var $this Sid_Wishlist_Block_Wishlist_New */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<!--Sprungziel Tastatursteuerung -->

<div class="page-title title-buttons">
	<h2><?php echo $this->__('Create New Collector List') ?></h2>
</div>

<div class="std default-form" id="jumptarget<?php echo $this->getNameInLayout();?>">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="wishlist-new-form">
        <input type="hidden" name="wishlist[id]" value="new" id="wishlist:id" />
      <?php if (!$this->customerHasWishlists()): ?>
        <input type="hidden" name="wishlist[is_default]" value="1" />
      <?php endif; ?>

        <h2 class="legend"><?php echo $this->__('New Collector List') ?></h2>

        <div class="field">
            <label for="wishlist:name">
                <?php echo $this->__('Name') ?>
            </label>
            <?php echo $this->getFieldRequiredHtml('name')?>
            <input type="text" id="wishlist:name" name="wishlist[name]"
                   value="<?php echo $this->escapeHtml($this->getWishlist()->getName()) ?>"
                   title="<?php echo $this->__('Name') ?>"
                   class="input-text"
                   maxlength="27" />
        </div>
        <div class="field">
            <input type="checkbox"
                   name="wishlist[is_default]"
                   id="wishlist:is_default"
                   value="1"
                   <?php if (!$this->customerHasWishlists()) : ?>
                       checked="checked"
                       disabled="disabled"
                   <?php endif; ?>
                   class="checkbox" />
            <label for="wishlist:is_default"><?php echo  $this->__('Is default') ?></label>
    	 </div>
    	 <div class="field">
    	     <label for="wishlist:description">
    	         <?php echo $this->__('Description') ?>
    	     </label>
    	     <?php echo $this->getFieldRequiredHtml('description')?>
    	     <textarea id="wishlist:description" name="wishlist[description]" title="<?php echo $this->__('Description') ?>">
    	         <?php echo $this->escapeHtml($this->getWishlist()->getDescription()); ?>
    	     </textarea>
    	 </div>

    	 <p class="required"><?php echo $this->__('* Required Fields') ?></p>

    	 <div class="buttons-set">
    	     <button class="button egov-float-left" onclick="setLocation('<?php echo $this->getBackUrl() ?>'); return false;">
    	         <?php echo $this->__('Back') ?>
    	     </button>
    	     <button class="button" type="submit">
    	         <span><?php echo $this->__('Continue') ?> </span>
    	     </button>
    	 </div>
    </form>
</div>
