<?php
/**
 *
 */
?>
<?php
/**
 * Merkzettel View Template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>

<script type="text/javascript">
//<![CDATA[
function deleteAll(url)
{
	q = confirm("<?php echo Mage::helper('sidwishlist')->__('Delete All Items'); ?>?");
	if(q == true)
	{
		window.location.href = url;
	}
}
//]]>

</script>


<!--Sprungziel Tastatursteuerung -->
<div id="jumptarget<?php echo $this->getNameInLayout();?>">
	<div class="page-title">
		<h2>
			<?php echo $this->__('Collector List: %s', $this->getQuote()->getName()) ?>
		</h2>
	</div>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if ($this->hasItems()): ?>
	<form id="collection-list-view-form" action="<?php echo $this->getUpdateUrl() ?>" method="post">
		<table cellspacing="0" border="0" id="collection-list-table"
			class="data-table box-table shopping-cart">
			<col width="40" />
			<col width="75" />
			<col />
			<col />
			<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<col width="80" />
			<?php endif; ?>
			<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<col width="80" />
			<?php endif; ?>
			<col width="1" />
			<?php if ($this->isAuthorizedOrderer() || $this->hasQtyGranted()): ?>
				<col width="1" />
			<?php endif; ?>
			<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<col width="80" />
			<?php endif; ?>
			<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<col width="80" />
			<?php endif; ?>
			<?php if ($this->isAuthorizedOrderer()): ?>
				<col width="1" />
			<?php endif ?>	
	
			<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
			<thead>
				<tr>
					<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Remove') ?></th>
					<th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
					<th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Name') ?></th>
					<th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Description') ?></th>
					<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Unit Price') ?></th>
					<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty Requested') ?>	</th>
					<?php if ($this->isAuthorizedOrderer() || $this->hasQtyGranted()): ?>
						<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty Granted') ?></th>
					<?php endif; ?>
					<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
					<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Status') ?></th>
					<?php if ($this->isAuthorizedOrderer()): ?>
						<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Add to cart') ?></th>
					<?php endif; ?>
				</tr>
				<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
				<tr>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
					</th>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?>
					</th>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
					</th>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?>
					</th>
				</tr>
				<?php endif; ?>
			</thead>
			<tbody>
				<?php foreach($this->getItems() as $_item): ?>
					<?php echo $this->getItemHtml($_item) ?>
				<?php endforeach ?>
			</tbody>
		</table>
		<div class="buttons-set-shopping-cart">
			<a href="<?php echo $this->getDeleteAllUrl(); ?>" class="egovslistbutton fll">
				<span><?php echo $this->__('Delete All Items') ?> </span>
			</a>
			<?php if($this->getContinueShoppingUrl()): ?>
				<a href="<?php echo $this->getContinueShoppingUrl() ?>" class="egovslistbutton fll">
					<span><?php echo $this->__('Continue Collecting') ?> </span>
				</a>
			<?php endif; ?>
			
			<!--  <a href="<?php echo $this->getShareUrl(); ?>" class="egovslistbutton fll">
				<span><?php echo $this->__('Share this list') ?> </span>
			</a> -->
			
			<button type="submit" onclick="this.name='save_and_share'" title="<?php echo $this->__('Share Collection List') ?>" class="button btn-share">
				<span><span><?php echo $this->__('Share Collection List') ?></span></span>
			</button>
	
			<button class="form-button-alt" type="submit">
				<span><?php echo $this->__('Update Collection List') ?> </span>
			</button>
			
			<?php if($this->getAddAllToCartUrl() && $this->hasSaleableItems()): ?>
				<a href="<?php echo $this->getAddAllToCartUrl() ?>" class="egovslistbutton fll">
					<span><?php echo $this->__('Add All to Cart') ?> </span>
				</a>
			<?php endif; ?>
	
		</div>	
	
		<script type="text/javascript">
			//<![CDATA[
			decorateTable('collection-list-table');
			//document.getElementById('_idDeleteAll').innerHTML = '<?php echo $this->getDeleteAllUrl();?>';
			
			function focusComment(obj) {
		        if( obj.value == '<?php echo $this->helper('sidwishlist')->defaultCommentString() ?>' ) {
		            obj.value = '';
		        } else if( obj.value == '' ) {
		            obj.value = '<?php echo $this->helper('sidwishlist')->defaultCommentString() ?>';
		        }
		    }

			function addWItemToCart(itemId) {
		        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
		        url = url.gsub('%item%', itemId);
		        var form = $('collection-list-view-form');
		        if (form) {
		            var input = form['qty[' + itemId + ']'];
		            if (input) {
		                var separator = (url.indexOf('?') >= 0) ? '&' : '?';
		                url += separator + input.name + '=' + encodeURIComponent(input.value);
		            }
		        }
		        setLocation(url);
		    }
			//]]>
		</script>
	
	</form>
	
	<div class="shopping-cart-collaterals">
		<div class="col2-set">	
			<div class="col-2">
				<div class="shopping-cart-totals">
					<?php echo $this->getChildHtml('totals'); ?>
	
					<?php echo $this->getChildHtml('methods') ?>
	
				</div>
			</div>
		</div>
	</div>

<?php else: ?>
	<p><?php echo $this->__('This list is empty.'); ?></p>
	<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
<?php endif;?>

<div class="clear"></div>

