<?php
/**
 * Merkzettel - Auswahl - Block
 *
 * @category   	Sid
 * @package    	Sid_Wishlist
 * @author 		Frank Rochlitzer <f.rochlitzer@trw-net.de>
 * @copyright  	Copyright (c) 2012 EDV Beratung Hempel - http://www.edv-beratung-hempel.de
 * @copyright  	Copyright (c) 2012 TRW-NET - http://www.trw-net.de
 * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
/**
 * @var \Sid_Wishlist_Block_Wishlists $this
 */
?>
<div class="page-title title-buttons">
    <h2><?php echo $this->__('Collector List') ?></h2>
</div>
<div class="std">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-sidwishlists">
        <input type="hidden" name="continue" value="0" id="can_continue_flag" />
    	<input type="hidden" name="new_wishlist" value="0" id="add_new_wishlist_flag" />

    	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    	<h3><?php echo $this->__('Select a Collector List') ?></h3>

    	<div class="field">
    		<?php echo $this->getSelectBoxHtml(); ?>
    	</div>

    	<div class="buttons-set">
    		<button class="button egov-float-left" onclick="setLocation('<?php echo $this->getBackUrl() ?>'); return false;">
    		    <?php echo $this->__('Back') ?>
    		</button>
    		<button class="button" type="submit">
    			<span><?php echo $this->__('Continue') ?> </span>
    		</button>
    	</div>
    </form>
</div>
