<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  Copyright (c) 2009 ITABS GbR - Rouven Alexander Rieker
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<?php 
$accountOwner = $this->getInfo()->getMethodInstance()->getAccountName();
$accountNumber = $this->getInfo()->getMethodInstance()->getAccountNumber();
$accountBlz = $this->getInfo()->getMethodInstance()->getAccountBLZ();
$accountBankname = $this->getInfo()->getMethodInstance()->getAccountBankname();
?>

<?php echo $this->getMethod()->getTitle() ?>
{{pdf_row_separator}}
Kontoinhaber: <?php echo $this->htmlEscape($accountOwner) ?>
{{pdf_row_separator}}
Kontonummer: <?php echo $this->htmlEscape($accountNumber) ?>
{{pdf_row_separator}}
BLZ: <?php echo $this->htmlEscape($accountBlz) ?>
{{pdf_row_separator}}
Kreditinstitut: <?php echo $this->htmlEscape($accountBankname) ?>