<?php
/**
 * @category    design
 * @package     lhdd_default
 * @copyright   Copyright (c) 2019 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Page_Block_Html_Header $this
 */

?>
<div id="loading-mask" style="display: none;">
    <div id="loading-mask-loader" class="loader">
        <div id="loading-spinner" class="egov-spinner"></div>
        <div id="loading-msg">
            <?php echo Mage::helper('egovsbase')->__('Loading');?><br />
            <?php echo Mage::helper('egovsbase')->__('Please wait');?>...
        </div>
    </div>
</div>