<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Page_Block_Html_Header $this
 */

?>
<div id="menuesprung">
<?php foreach($this->getJumps() as $jump):
    $_accesskey = "";
    if($jump->getAccesskey()!= null){
        $_accesskey = 'accesskey="'.$jump->getAccesskey().'"';
    }
?>
    <div id="bitv_<?php echo $jump->getAccesskey(); ?>">
        <a href="#<?php echo $this->helper('bitv')->getJumpTarget($jump);?>" <?php echo $_accesskey; ?>>
            <?php echo Mage::helper('bitv')->__($jump->getJumptitle());?>
        </a>
    </div>
<?php endforeach ?>
</div>
