<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Mage_Catalog_Block_Product_Compare_List */
?>
<div class="page-title title-buttons">
    <h1>
        <?php echo $this->__('Compare Products') ?>
        <a href="javascript:void(0);" onclick="window.print(); return false;" class="link-print egov-print">
            <?php echo $this->__('Print This Page') ?>
        </a>
    </h1>
</div>
<?php $_total=$this->getItems()->count() ?>

<?php if($_total): ?>
<table class="data-table compare-table" id="product_comparison">
    <colgroup>
      <?php $_i=0 ?>
      <?php foreach($this->getItems() as $_item): ?>
       <?php if($_i++%10==0): ?>
        <col width="2%" />
       <?php endif; ?>
        <col width="<?php echo floor(98/$_total); ?>%" />
      <?php endforeach; ?>
    </colgroup>
  <?php if ($_total>2): ?>
    <thead>
        <tr>
          <?php $_i=0 ?>
          <?php foreach($this->getItems() as $_item): ?>
           <?php if($_i++%10==0): ?>
            <th>&nbsp;</th>
           <?php endif; ?>
            <td class="remove-list-item">
                <a href="javascript:void(0);"
                   class="btn-remove"
                   onclick="removeItem('<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>');"
                   title="<?php echo $this->quoteEscape($this->__('Remove This Item')) ?>">
                    <?php echo $this->__('Remove This Item') ?>
                </a>
            </td>
          <?php endforeach; ?>
        </tr>
    </thead>
  <?php endif ?>
    <tbody>
        <tr class="product-shop-row top">
          <?php $_i=0 ?>
          <?php foreach($this->getItems() as $_item): ?>
           <?php if($_i++%10==0): ?>
            <th>&nbsp;</th>
           <?php endif; ?>
            <td>
                <a href="javascript:void(0);"
                   class="product-image"
                   onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)"
                   title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>"
                         class="product-compare-image"
                         alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                </a>
                <div class="product-compare-base-details">
                    <h2 class="product-name">
                        <a href="javascript:void(0);"
                           onclick="setPLocation('<?php echo $this->getProductUrl($_item) ?>', true)"
                           title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                            <?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?>
                        </a>
                    </h2>
                    <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                    <?php echo $this->getPriceHtml($_item, true, '-compare-list-top') ?>
                </div>
            </td>
          <?php endforeach; ?>
        </tr>
        <tr class="product-shop-row bottom">
          <?php $_i=0 ?>
          <?php foreach($this->getItems() as $_item): ?>
           <?php if($_i++%10==0): ?>
            <th>&nbsp;</th>
           <?php endif; ?>
            <td>
                <div class="product-action">
              <?php if($_item->isSaleable()): ?>
                    <button type="button"
                            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                            class="button btn-cart egov-cart"
                            onclick="setPLocation('<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>', true)">
                        <span>
                            <?php echo $this->__('Add to Cart') ?>
                        </span>
                    </button>
              <?php else: ?>
                    <p class="availability out-of-stock">
                        <span><?php echo $this->__('Out of stock') ?></span>
                    </p>
              <?php endif; ?>
                </div>
              <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <ul class="add-to-links">
                    <li>
                        <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>"
                           class="link-wishlist"
                           title="<?php echo $this->__('Add to Wishlist') ?>">
                            <?php echo $this->__('Add to Wishlist') ?>
                        </a>
                    </li>
                </ul>
              <?php endif; ?>
            </td>
          <?php endforeach; ?>
        </tr>
      <?php foreach ($this->getAttributes() as $_attribute): ?>
        <tr>
          <?php $_i=0 ?>
          <?php foreach($this->getItems() as $_item): ?>
           <?php if($_i++%10==0): ?>
            <th>
                <span class="nobr"><?php echo $this->__($_attribute->getStoreLabel()) ?></span>
            </th>
           <?php endif; ?>
            <td>
              <?php
              switch ($_attribute->getAttributeCode()) {
                case "price"      :  echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode());
                                     break;
                case "small_image": ?><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                                    <?php break;
                case "date"       : echo substr($this->getProductAttributeValue($_item, $_attribute),0,10);
                                    break;
                default           : ?><div class="std"><?php echo $this->helper('catalog/output')->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?></div>
                                    <?php break;
              } ?>
            </td>
          <?php endforeach; ?>
        </tr>
      <?php endforeach; ?>
    </tbody>
</table>

<div class="buttons-set">
    <button type="button"
            title="<?php echo $this->quoteEscape($this->__('Close Window')) ?>"
            class="button"
            onclick="window.close();">
        <span>
            <?php echo $this->__('Close Window') ?>
        </span>
    </button>
    <span class="please-wait" id="compare-list-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
             alt="<?php echo $this->quoteEscape($this->__('Please wait...')) ?>"
             title="<?php echo $this->quoteEscape($this->__('Please wait...')) ?>"
             class="v-middle" />
        <?php echo $this->__('Please wait...') ?>
    </span>
</div>

<script type="text/javascript">
    decorateTable('product_comparison');

    /**
     * Send remove item request, after that reload windows
     */
    function removeItem(url) {
        new Ajax.Request(url, {
            parameters: {isAjax: 1, method: 'POST'},
            onLoading: function(){$('compare-list-please-wait').show();},
            onSuccess: function(transport) {
                $('compare-list-please-wait').hide();
                window.location.reload();
                window.opener.location.reload();
            }
        });
    }
</script>
<?php else: ?>
<script type="text/javascript">window.close();</script>
<?php endif; ?>
