<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

?>
<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>"
   onclick="return confirmRemoveWishlistItem();"
   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"
   class="remove egov-delete2"> </a>
