
<?php echo $this->getChildHtml('top')?>
<?php echo $this->getChildHtml('grid')?>


<script type="text/javascript">
    var export_csv = true;

    document.observe('dom:loaded', function() {
        function changeDate() {
            if ( export_csv == false ) {
                $('<?php echo $this->getChild('grid')->getButtonId("export_button")?>').disable().addClassName('disabled');
                $('messages').update('');
                $('messages').insert('<ul class="messages"><li class="notice-msg"><ul><li><span><?php echo $this->getRefreshExportMessage(); ?></span></li></ul></li></ul>');
            }

            $$('#<?php echo $this->getChild('grid')->getButtonId("export_button")?>').each(function(elem){
                elem.observe('click', function(event){
                    // onClick-Event des Export abbrechen
                    if ( export_csv == false ){
                        stop();
                        alert('stop');
                    }
                });
            });
        }

        $$('#<?php echo $this->getChild('top')->getButtonId("export_button")?>').each(function(elem){
            elem.observe('click', function(event){
                $('<?php echo $this->getChild('grid')->getButtonId("export_button")?>').enable().removeClassName('disabled');
            });
        });

        $$('#from').each(function(elem){
            export_csv = false;
            elem.observe('change', changeDate);
        });
        $$('#to').each(function(elem){
            export_csv = false;
            elem.observe('change', changeDate);
        });
    });
</script>