<?php if($this->getError()){?>
<h1><?php echo $this->getError();?></h1>
<?php }?>

<div id="periode_items_list" class="grid tier form-list">
    <table style="border:0;">
        <thead>
            <tr class="headings">
                <th><?php echo $this->__('Id')?></th>
                <th><?php echo $this->__('Label')?></th>
                <th><?php echo $this->__('Type')?></th>
                <th><?php echo $this->__('From')?></th>
                <th><?php echo $this->__('To')?></th>
                <th><?php echo $this->__('Duration')?></th>
                <th><?php echo $this->__('Unit')?></th>
                <?php if($this->getProductHasAboOption()):?><th><?php echo $this->__('Cancelation Period [Days]')?></th><?php endif;?>
                <th><?php echo $this->__('Price')?></th>
                <?php if(($this->isAboEnabled()) && ($this->getProductHasAboOption()) ):?><th><?php echo $this->__('Active Abos')?></th><?php endif;?>
                <th class="type-last last">&nbsp;</th>
            </tr>
        </thead>
        <tbody id="period_items">

<?php foreach ( $this->getItems() as $item ){ ?>
             <tr style="cursor:pointer;" onclick="selectRow('<?php echo $item->getId() ?>')">
                <td><?php echo $item->getId()?><input type="hidden" id="rowData<?php echo $item->getId() ?>" value="<?php echo $item->toJson() ?>"/></td>
                <td><?php echo $item->getLabel()?></td>
                <td><?php echo $this->__($this->getPeriodeTypeLabel($item->getType()))?></td>
<?php if($this->isPeriodeTypeDuration($item->getType())){?>
                <td>---</td>
                <td>---</td>
                <td><?php echo $this->__($item->getDuration())?></td>
                <td><?php echo $this->getPeriodeUnitLabel($item->getUnit())?></td>
                <?php if($this->getProductHasAboOption()):?><td>---</td><?php endif;?>
<?php }elseif($this->isPeriodeTypeDurationAbo($item->getType())){?>
                <td>---</td>
                <td>---</td>
                <td><?php echo $this->__($item->getDuration())?></td>
                <td><?php echo $this->getPeriodeUnitLabel($item->getUnit())?></td>
                <?php if($this->getProductHasAboOption()):?><td><?php echo $item->getCancelationPeriod();?></td><?php endif;?>
<?php }else{?>
                <td><?php echo $this->formatPeriodeDate($item->getFrom())?></td>
                <td><?php echo $this->formatPeriodeDate($item->getTo())?></td>
                <td>---</td>
                <td>---</td>
                <?php if($this->getProductHasAboOption()):?><td>---</td><?php endif;?>
<?php }?>

                <td><?php echo $this->getPrice($item) ?></td>
                <?php if($this->getProductHasAboOption()):?><td class="abo_count"><?php echo $this->getAboCount($item)?></td><?php endif;?>
                <td class="type-last last action"><?php echo $this->getDeleteButtonHtml($item->getEntityId(), $item->getProductId())?></td>
            </tr>
<?php }?>
        </tbody>
    </table>
    </div>
