<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product list widget
 *
 * @see Mage_Catalog_Block_Product_Widget_New
 */
/* @var $this Mage_Catalog_Block_Product_Widget_New */
?>
<?php
    $name_limit = 30;
    $sku_limit = 24;
    $desc_limit = 110;
    $_imgSize_list = 300;
    $_imgSize_grid = 210;
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="widget-title">
        <h2><?php echo $this->__('New Products') ?></h2>
    </div>
    <div class="widget-products">
        <?php echo $this->getPagerHtml() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_params = $this->escapeHtml(json_encode(array('form_key' => $this->getFormKey()))); ?>
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize_grid) ?>"
                         alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                </a>
              <?php if( Mage::helper('egovsbase/catalog_product_data')->isProductNew($_product) ) : ?>
                <div class="product-new-block">
                    <img src="<?php echo $this->getSkinUrl('images/artikel-neu.png'); ?>" alt="<?php echo $this->__('New Product'); ?>" title="<?php echo $this->__('New Product'); ?>" />
                </div>
              <?php endif; ?>
                <div class="product-info">
                    <?php
                    $_productNameStripped = $this->stripTags($_product->getName(), null, true);
                    $_productName = $_product->getName();
                    if ( strlen($_productName) > $name_limit ) {
                        $_productName = mb_substr($_productName, 0, $name_limit) . '...';
                    }
                    ?>
                    <h2 class="product-name"><?php echo $_productNameStripped; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                            <?php echo $_productName; ?>
                        </a>
                    </h2>
                    <div class="product_sku">
                        <?php
                        $_sku = $_sku_full = $this->escapeHtml($_product->getSku());

                        if ( strlen($_sku) > $sku_limit ) {
                            $_sku = mb_substr($_sku, 0, $sku_limit) . '...';
                        }
                        echo $this->__('Sku').': <span title="'.$_sku_full.'">'.$_sku.'</span>';
                        ?>
                    </div>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                    <div class="actions">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <button type="button"
                                    title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                    class="button btn-cart egov-cart"
                                    onclick="customFormSubmit(
                                            '<?php echo $this->getAddToCartUrlCustom($_product, array(), false) ?>',
                                            '<?php echo $_params ?>',
                                            'post')">
                                <span><?php echo $this->__('Add to Cart') ?></span>
                            </button>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>"
                               class="button egov-view"
                               href="<?php echo $_product->getProductUrl() ?>">
                                <span><?php echo $this->__('View Details') ?></span>
                            </a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif ?>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
