<?php
/**
 * Personalisierungsbox für Veranstaltungsprodukte
 */
?>


<div class="entry-edit">
	<div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo($this->__('Lose'))?></h4>
    <div class="form-buttons"></div>
</div>
    <div id="content_form" class="fieldset ">
    <div class="hor-scroll">
          





<?php echo $this->getChild('add_button')->toHtml();?>

<div id="contract_los_box" class="grid tier form-list">
   <table id="sid-lose-grid">
   <thead>
   <tr class="headings">
      	
    <th class="type-id" style="width:50px;" ><?php echo($this->__('ID'))?></th>
   	<th class="type-title"><?php echo($this->__('Title'))?><span class="required"> *</span></th>
   	<th class="type-note"><?php echo($this->__('Note'))?></th>
   	<th class="type-status"><?php echo($this->__('Status'))?></th>
   	<th class="type-link">Link erneuern</th>
   	<th class="type-send">Link versenden</th>
   	<th class="type-button"/>
   	</tr>
   </thead>
   <tbody>
   <tr id="contract_los_container_bottom"/>    
   </tbody>
    </table>
</div>


            </div>
        </div>
</div>
</div>


<script type="text/javascript">
//<![CDATA[
var firstLosTemplate = '<tr id="contract_los_{{number}}"><td  class="a-center">' +
							'<input type="hidden" id="contract_los_{{number}}_is_delete" name="lose[{{number}}][is_delete]" value="" />'+
							'<input style="width:50px;"  type="text" disabled="disabled" name="lose[{{number}}][los_id]" value="{{los_id}}" />'+
							'</td>'+
							'<td><input class="input-text los-input required-entry" id="contract_los_{{number}}_label" value="{{title}}" name="lose[{{number}}][title]" /></td>'+
							'<td class="a-center"><input class="input-text los-input"  id="contract_los_{{number}}_pos" value="{{note}}" name="lose[{{number}}][note]" /></td>' +
							'<td class="a-center"><select   id="contract_los_{{number}}_field" name="lose[{{number}}][status]">' +
							'	<?php foreach ($this->getStatus() as $key=>$value): ?>' +
							'			<option value="<?php echo($key)?>"><?php echo($value) ?></option>' +
							'	<?php endforeach; ?>' +
							'</select></td>'+
							'<td><input type="checkbox" class="input-text" name="lose[{{number}}][newkey]" /></td>'+
							'<td><input type="checkbox" class="input-text" name="lose[{{number}}][sendlink]" /></td>'+
							'<td class="a-center"><button style="" onclick="" class="scalable delete los-input " type="button" title="löschen" id="contract_los_remove_{{number}}"><span><span><span>Los löschen</span></span></span></button>'+
							'</td></tr>';

var contractLos = {
    div : $('contract_los_container_bottom'),
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : firstLosTemplate,
    itemCount : 1,
    pos : 0,
    add : function(data) {
        this.template = new Template(this.templateText, this.templateSyntax);
		if(!data){
			var data = new Object();
			data.products = 0;
		} 

        data.number = this.itemCount;
		
        if (data.pos) {
        	this.pos = Math.max(data.pos,this.pos);
        }else{
        	this.pos++;
        	data.pos = this.pos;
        }

        Element.insert(this.div, {'before':this.template.evaluate(data)});

        //set selected fieldname
        if (data.status) {
            $A($('contract_los_'+data.number+'_field').options).each(function(option){
                if (option.value==data.status) option.selected = true;
            });
        }

        if(data.products > 0)
        {
            $('contract_los_remove_'+ data.number).hide();
        }

        

        this.itemCount++;
        this.bindRemoveButtons();

    },
    remove : function(event){
        var element = $(Event.findElement(event, 'tr'));
        if(element){
            var id = element.readAttribute('id');
            $(id+'_'+'is_delete').value = '1';
            element.addClassName('no-display');
            element.addClassName('ignore-validate');
            element.hide();
        }
    },
    bindRemoveButtons : function(){
        var buttons = $$('button.los-input');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
                Event.observe(buttons[i], 'click', this.remove.bind(this));
            }
        }

        var inputs = $$('div.delete-personal-option button', 'div.los-input input');
        inputs.each(function(el) { Event.observe(el, 'change', el.setHasChanges.bind(el));  } )

    }
}


<?php foreach ($this->getLose() as $field): ?>
	contractLos.add(<?php echo $field->toJson() ?>);
<?php endforeach; ?>




//]]>
</script>

