<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  Copyright (c) 2009 ITABS GbR - Rouven Alexander Rieker
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php echo $this->getMethod()->getTitle() ?>
<p>
<?php if($this->getMethod()->getAccountBankname() == 'existiert nicht'): ?>
	<span style="color: #cc0000;font-weight:bold;">Fehler! Die eingegebenen Bankdaten k&ouml;nnen fehlerhaft sein!<br />Bitte setzen Sie sich mit dem Kunden in Verbindung!</span><br /><br />
<?php else: ?>
	<div style="font-style: italic;"><?php echo $this->__('Account info'); ?></div>
    <table>
        <tbody>
        <?php if ($this->getMethod()->getAccountName()): ?>
            <?php echo '<tr><td><label>' . $this->__('Account holder') . '</label>:</td><td>' . $this->getMethod()->getAccountName() . '</td></tr>'; ?>
        <?php endif; ?>
        <?php if ($this->getMethod()->getAccountNumber()): ?>
            <?php echo '<tr><td><label>' . $this->__('Account number') . '</label>:</td><td>' . $this->getMethod()->getAccountNumber() . '</td></tr>'; ?>
        <?php endif; ?>
        <?php if ($this->getMethod()->getAccountBLZ()): ?>
            <?php echo '<tr><td><label>' . $this->__('Sort code') . '</label>:</td><td>' . $this->getMethod()->getAccountBLZ() . '</td></tr>'; ?>
        <?php endif; ?>
        <?php if ($this->getMethod()->getAccountBankname()): ?>
            <?php echo '<tr><td><label>' . $this->__('Bank name') . '</label>:</td><td>' . $this->getMethod()->getAccountBankname() . '</td></tr>'; ?>
        <?php endif; ?>
        </tbody>
    </table>
<?php endif; ?>
</p>