<form id="edit_form" method="post" enctype="<?php echo $this->getForm()->getEnctype() ?>" action="<?php echo $this->getForm()->getAction() ?>">
<input type="hidden" value="<?php echo $this->getFormKey() ?>" name="form_key" />
<div id="hidden_navi_menu"></div>
<div class="columns sidcms-columns">
	<div id="page-left" class="sidcms-side-col">
		<?php echo $this->getChildHtml('navigation_tree');?>
        <?php echo $this->getChildHtml('content_tools');?>
	</div>
	<div id="content" class="sidcms-main-col">
    	<div class="main-col-inner">		
	    	<div class="entry-edit">

		        <?php echo $this->getChildHtml('composit_form');?>
    		</div>
	    	<?php echo $this->getChildHtml('form_after');?>
	    </div>
	</div>
</div>
</form>
