<?php
/**
 * @category    design
 * @package     gka_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="footer-container">
    <!--Sprungziel Tastatursteuerung -->
    <div id="jumptarget<?php echo $this->getNameInLayout();?>">
        <h2 style="display:none;"><?php echo $this->__('Service Menue')?></h2>
    </div>

    <div id="footer-wrapper">
        <div class="footer">
            <div class="links" style="height: 100px;"><!-- Dummy --></div>
            <address class="copyright">
            <?php
                if ( $this->canShowVersion() == true ) {
              	    echo $this->__('(Version %s) ', $this->getVersion());
                }    
            
                echo $this->getCopyright();
            ?>
            </address>
        </div>
    </div>
</div>
