<script type="text/javascript">
//<![CDATA[
function addPeriodeData()
{
	  var errors = saveLine( $('periode_type').value );

	  var check_id = $F('periode_id');
	  if ($('rowData'+check_id)) {
		  var item = $('rowData'+check_id).up('tr');
		  var abo_count = $(item).down('.abo_count');
		  if (abo_count && abo_count.innerHTML > 0) {
		  	if (!confirm('<?php echo Mage::helper('periode')->__('This periode has active abonnements! Please contact your customer(s) first! Do you really want to change this item?') ?>')) {
		  		setDefault();
    		  changeArt(1);
		  		return;
		  	}
		  }
	  }

	  if ( errors == false )
	  {
		    var cp = $('cancelation_period') ? $F('cancelation_period') : '';
    		new Ajax.Updater('periode_content',
    		                 '<?php echo $this->getAddRowUrl()?>',
    		                 {
    		                     parameters: {
    		                         periode_label      : $F('periode_label'),
    		                         periode_duration   : $F('periode_duration'),
    		                         periode_product    : $F('periode_product_id'),
    		                         periode_type       : $F('periode_type'),
    		                         periode_from       : $F('periode_from'),
    		                         periode_to         : $F('periode_to'),
    		                         periode_unit       : $F('periode_unit'),
    		                         periode_price      : $F('periode_price'),
    		                         periode_id   	    : $F('periode_id'),
    		                         store_id   	    : $F('store_id'),
    		                         cancelation_period : cp,
    		                         periode_tier_price : getPeriodeTierPrice()
    		                     }
    		                 });

    		setDefault();
    		changeArt(1);
	  }
}

function deletePeriodData(id,product_id) {
	if ($('rowData'+id)) {
		var item = $('rowData'+id).up('tr');
		var abo_count = $(item).down('.abo_count');
		if (abo_count && abo_count.innerHTML > 0) {
			if (!confirm('<?php echo Mage::helper('periode')->__('This periode has active abonnements! Please contact your customer(s) first! Do you really want to delete this item?') ?>')) {
				return;
			}
		}
	}

	new Ajax.Updater('periode_content',
	                 '<?php echo $this->getDeleteRowUrl()?>',
	                 {
		                   parameters: { id        : id,
		             		    	           product_id: product_id
		                   }
                   });
}
//]]>
</script>

<div class="entry-edit">
	<div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('periode')->__('Period Settings') ?></h4>
    </div>
    <fieldset class="a-right">
        <div style="position:relative;top:22px;right:10px;"><?php echo $this->getAllButtons() ?></div>
        <?php echo $this->getInputHtml()?>
        <div id="periode_content">
            <?php echo $this->getContentHtml()?>
        </div>
    </fieldset>
</div>
