<?php
/**
 * Merklisten View Template
 *
 * @var $this Sid_Wishlist_Block_View
 * @see Mage_Checkout_Block_Cart
 */

$_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price';
$mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1);
?>

<script type="text/javascript">
//<![CDATA[
function deleteAll(url)
{
	q = confirm("<?php echo Mage::helper('sidwishlist')->__('Delete All Items'); ?>?");
	if(q == true)
	{
		window.location.href = url;
	}
}
//]]>
</script>

<!--Sprungziel Tastatursteuerung -->
<div class="cart <?php echo $_priceDisplay; ?>" id="jumptarget<?php echo $this->getNameInLayout();?>">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Collector List: %s', $this->getQuote()->getName()) ?></h1>
    </div>
	<?php echo $this->getMessagesBlock()->toHtml() ?>
	<?php echo $this->getChildHtml('form_before') ?>
<?php if ($this->hasItems()): ?>
    <form id="collection-list-view-form" action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="collection-list-table" class="cart-table data-table">
            <col width="50" /> <?php //Bild ?>
            <col />			   <?php //Produktname ?>
            <col width="20" /> <?php //Preis ?>
            <col width="50" /> <?php //Angefragt ?>
		<?php if ($this->isAuthorizedOrderer() || $this->hasQtyGranted()): ?>
			<col width="50" /> <?php //Genehmigt ?>
		<?php endif; ?>
            <col width="20" /> <?php //Zwischensumme ?>
            <col width="50" /> <?php //Status ?>
            <col width="40" /> <?php //Aktionen ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="70" />
            <col width="20" />
        <?php endif; ?>
            <thead>
				<tr>
					<th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
					<th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Name') ?></th>
					<th class="a-center" style="word-break:break-all;word-wrap:break-word" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Unit Price') ?></th>
					<th rowspan="<?php echo $mergedCells; ?>" style="word-break:break-all;word-wrap:break-word" class="a-center"><?php echo $this->__('Qty Requested') ?>	</th>
					<?php if ($this->isAuthorizedOrderer() || $this->hasQtyGranted()): ?>
						<th rowspan="<?php echo $mergedCells; ?>" style="word-break:break-all;word-wrap:break-word" class="a-center"><?php echo $this->__('Qty Granted') ?></th>
					<?php endif; ?>
					<th class="a-center" style="word-break:break-all;word-wrap:break-word" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
					<th class="a-center" rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Status') ?></th>
					<th class="a-center" rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Actions') ?></th>
				</tr>
			  <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
	            <tr>
	                <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
	                <th class="a-center cart-price-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
	                <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
	                <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
	            </tr>
	          <?php endif; ?>
			</thead>
			<tfoot>
                <tr>
                    <td colspan="50" class="a-right cart-footer-actions">
                    	<?php if($this->getContinueShoppingUrl()): ?>
							<a href="<?php echo $this->getContinueShoppingUrl() ?>" class="button egov-float-left">
								<span><?php echo $this->__('Continue Collecting') ?> </span>
							</a>
						<?php endif; ?>

                    	<a href="<?php echo $this->getDeleteAllUrl(); ?>" class="button btn-empty egov-float-left">
							<span><?php echo $this->__('Delete All Items') ?> </span>
						</a>

						<button type="submit" onclick="this.name='save_and_share'" title="<?php echo $this->__('Share Collection List') ?>" class="button btn-share">
							<span><span><?php echo $this->__('Share Collection List') ?></span></span>
						</button>

						<button class="button btn-update" type="submit">
							<span><?php echo $this->__('Update Collection List') ?> </span>
						</button>

						<?php if($this->getAddAllToCartUrl() && $this->hasSaleableItems()): ?>
							<a href="<?php echo $this->getAddAllToCartUrl() ?>" class="button btn-update">
								<span><?php echo $this->__('Add All to Cart') ?> </span>
							</a>
						<?php endif; ?>
                    </td>
                </tr>
            </tfoot>
			<tbody>
				<?php foreach($this->getItems() as $_item): ?>
					<?php echo $this->getItemHtml($_item) ?>
				<?php endforeach ?>
			</tbody>
		</table>

		<script type="text/javascript">
			//<![CDATA[
			decorateTable('collection-list-table');

			function focusComment(obj) {
		        if( obj.value == '<?php echo $this->helper('sidwishlist')->defaultCommentString() ?>' ) {
		            obj.value = '';
		        } else if( obj.value == '' ) {
		            obj.value = '<?php echo $this->helper('sidwishlist')->defaultCommentString() ?>';
		        }
		    }

			function addWItemToCart(itemId) {
		        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
		        url = url.gsub('%item%', itemId);
		        var form = $('collection-list-view-form');
		        if (form) {
		            var input = form['qty[' + itemId + ']'];
		            if (input) {
		                var separator = (url.indexOf('?') >= 0) ? '&' : '?';
		                url += separator + input.name + '=' + encodeURIComponent(input.value);
		            }
		        }
		        setLocation(url);
		    }
			//]]>
		</script>

	</form>

	<div class="cart-totals-wrapper">
        <!--Sprungziel Tastatursteuerung -->
        <div class="cart-totals" id="jumptarget<?php echo $this->getNameInLayout();?>">
            <?php echo $this->getChildHtml('totals'); ?>
        </div>
    </div>

<?php else: ?>
	<p><?php echo $this->__('This list is empty.'); ?></p>
	<div class="buttons-set">
	    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	</div>
<?php endif;?>
</div>

<div class="clear"></div>

