<?php
/**
 * Created by PhpStorm.
 * User: f.rochlitzer
 * Date: 06.04.2018
 * Time: 11:07
 */

class Bkg_VirtualGeo_Model_Resource_Bundle_Selection_Collection extends Mage_Bundle_Model_Resource_Selection_Collection
{
    /**
     * Init model and resource model
     *
     */
    protected function _construct()
    {
        parent::_construct();
        $this->_selectionTable = $this->getTable('virtualgeo/bundle_selection');
    }

    public function addFieldToFilter($attribute, $condition = null) {
        if (is_string($attribute) && stripos($attribute, 'selection') === 0) {
            $field = explode('.', $attribute);

            if (count($field) == 2 && $field[0] == 'selection') {
                $this->getSelect()->where("{$attribute} = ?", $condition);

                return $this;
            }
        } else {
            return parent::addFieldToFilter($attribute, $condition); // TODO: Change the autogenerated stub
        }
    }
}