<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Egovs
 * @package    Egovs_Bankpayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @copyright  Copyright (c) 2012 EDV Beratung Hempel
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
<?php echo $this->getMethod()->getTitle(); ?>
<br />
</p>
<div style="font-style: italic;">
	<?php echo $this->__('Account info'); ?>
</div>
<table>
    <tbody>
    <?php if ($this->getMethod()->getBankName()): ?>
		<?php echo '<tr><td><label>' . $this->__('Bank name') . '</label>:</td><td>' . $this->getMethod()->getBankName(); ?>
    <?php endif; ?>
     <?php if ($this->getMethod()->getAccountHolder()): ?>
		<?php echo '<tr><td><label>' . $this->__('Account holder') . '</label>:</td><td>' . $this->getMethod()->getAccountHolder(); ?>
    <?php endif; ?>
    <?php if ($this->getMethod()->getAccountNumber()): ?>
		<?php echo '<tr><td><label>' . $this->__('Account number') . '</label>:</td><td>' . $this->getMethod()->getAccountNumber(); ?>
    <?php endif; ?>
    <?php if ($this->getMethod()->getSortCode()): ?>
		<?php echo '<tr><td><label>' . $this->__('Sort code') . '</label>:</td><td>' . $this->getMethod()->getSortCode(); ?>
    <?php endif; ?>
    <?php if ($this->getMethod()->getIBAN()): ?>
        <?php echo '<tr><td><label>' . $this->__('IBAN') . '</label>:</td><td>' . $this->getMethod()->getIBAN() . '</td></tr>'; ?>
    <?php endif; ?>
    <?php if ($this->getMethod()->getBIC()): ?>
        <?php echo '<tr><td><label>' . $this->__('BIC') . '</label>:</td><td>' . $this->getMethod()->getBIC() . '</td></tr>'; ?>
	<?php endif; ?>
    </tbody>
</table>
<?php if ($this->getMethod()->getCustomText()): ?>
    <br />
	<?php echo $this->getMethod()->getCustomText(); ?>
	<br />
<?php endif; ?>
<?php if ($this->getMethod()->getPayWithinXDays()): ?>
	<br />
	<?php echo $this->__('Pay within %s days.', $this->getMethod()->getPayWithinXDays()); ?>
	<br />
<?php endif; ?>