<h2 class="checknewsletter"><?php echo $this->__('Please inform me about these:')?></h2>
<ul>
<li> 
	<input class="checkbox" type="checkbox" name="extnewsletter[0]" id="extnewsletter_0" value="0" />
	<label for="extnewsletter_0">
	<?php echo $this->__('general topics')?>
	</label>
	</li>
<?php foreach($this->getProducts() as $_product){?>
	<li>
		<input class="checkbox" type="checkbox" id="extnewsletter_<?php echo $_product->getId() ?>" name="extnewsletter[<?php echo $_product->getId() ?>]" value="1" />
		<label for="extnewsletter_<?php echo $_product->getId() ?>">
			<?php echo $this->__('news about product: %s',$_product->getName()) ?> 
		</label>
		</li>
<?php }?>
</ul>