<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var $this Mage_Catalog_Block_Product_View_Options_Type_Date
 */
?>
<?php $_option = $this->getOption() ?>
<?php $_optionId = $_option->getId() ?>
<dt class="option-block type-<?php echo $_option->getType(); ?>">
    <span class="option-block-label">
        <label>
            <?php if ($_option->getIsRequire()) echo '<em class="required">*</em>' ?>
            <?php echo  $this->escapeHtml($_option->getTitle()) ?>
        </label>
        <?php echo $this->getFormatedPrice() ?>
    </span>
    <br />
    <span class="option-block-elements">
    <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE_TIME
        || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_DATE): ?>

        <input type="text" name="options[<?php echo $_optionId ?>][date]" id="options_<?php echo $_optionId ?>_date" value="" class="product-custom-option datetime-picker input-text" onchange="opConfig.reloadPrice()"/>
        <script type="text/javascript">
            $j(document).ready(function(){
            	//$j('#options_<?php echo $_optionId ?>_date_trig').remove();
            	$j('#options_<?php echo $_optionId ?>_date').datepicker({
            		'changeMonth'    : true,
            		'changeYear'     : true,
            		'yearRange'      : '1900:<?php echo date('Y'); ?>',
            		'maxDate'        : 0,
            		'dateFormat'     : '<?php echo $this->getDateFormat(); ?>',
            		'dayNames'       : <?php echo json_encode(array_values($this->getDayNames())); ?>,
            		'dayNamesShort'  : <?php echo json_encode(array_map('ucfirst', array_keys($this->getDayNamesAbbr()))); ?>,
            		'dayNamesMin'    : <?php echo json_encode(array_values($this->getDayNamesAbbr())); ?>,
            		'monthNames'     : <?php echo json_encode(array_values($this->getMonthNames())); ?>,
            		'monthNamesShort': <?php echo json_encode(array_values($this->getMonthNamesAbbr())); ?>,
                    'firstDay'       : <?php echo $this->getFirstWDay();?>,
            		'nextText'       : '<?php echo Mage::helper('catalog')->__('Next'); ?>',
            		'prevText'       : '<?php echo Mage::helper('catalog')->__('Prev'); ?>'
            	});
            });
        </script>
    <?php endif; ?>
        <input type="hidden"
               id="validate_datetime_<?php echo $_optionId ?>"
               name="validate_datetime_<?php echo $_optionId ?>"
               class="validate-datetime-<?php echo $_optionId ?>"
               value="" />

        <script type="text/javascript">
        //<![CDATA[
    <?php if ($_option->getIsRequire()): ?>
            Validation.addAllThese(
            [
                   ['validate-datetime-<?php echo $_optionId ?>', '<?php echo $this->jsQuoteEscape( Mage::helper('catalog')->__('This is a required option') )?>', function(v) {
                       var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                       for (var i=0; i < dateTimeParts.length; i++) {
                           if (dateTimeParts[i].value == "") return false;
                       }
                       return true;
                    }]
            ]
            );
    <?php else: ?>
            Validation.add(
                'validate-datetime-<?php echo $_optionId ?>',
                '<?php echo $this->jsQuoteEscape( Mage::helper('catalog')->__('Field is not complete') )?>',
                function(v) {
                    var dateTimeParts = $$('.datetime-picker[id^="options_<?php echo $_optionId ?>"]');
                    var hasWithValue = false, hasWithNoValue = false;
                    var pattern = /day_part$/i;
                    for (var i=0; i < dateTimeParts.length; i++) {
                       if (! pattern.test(dateTimeParts[i].id)) {
                           if (dateTimeParts[i].value === "") {
                               hasWithValue = true;
                           } else {
                               hasWithNoValue = true;
                           }
                       }
                    }
                    return hasWithValue ^ hasWithNoValue;
                }
            );
    <?php endif; ?>
        //]]>
        </script>
    </span>
</dt>
