<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
	<h2>
		<?php echo $this->__('Review Order') ?>
	</h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post">
	<?php echo $this->getBlockHtml('formkey'); ?>
	<fieldset>
			<ul class="form-list group-select">
				<li>
					<input type="hidden" name="sendOrderEmail" id="sendOrderEmail" value="1"/> <!-- <label for="sendOrderEmail"> <?php echo $this->__('Please send me a confirmation of this order by e-Mail')?></label> -->
				</li>
			</ul>

			<div>
				<?php echo $this->getChildHtml('infotexts'); ?>
				<?php echo $this->getChildHtml('agreementtexts'); ?>

				<?php echo $this->getChildHtml('agreements') ?>
			</div>
	</fieldset>
	<fieldset class="multiple-checkout">
		<?php $_address=$this->getBaseAddress() ?>
		<?php if (Mage::helper('core')->isModuleEnabled('Egovs_GermanTax') && $_address):?>
			<div class="col2-set">
				<h3>
					<?php echo $this->__('Tax Information') ?>
				</h3>
				<div class="col-1">
					<h4>
						<?php echo $this->__('Base Address') ?>
					</h4>
					<address id="baseAddress">
						<?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
					</address>
				</div>
				<div></div>
			</div>
		<?php endif;?>
		<div class="col2-set">
			<h3>
				<?php echo $this->__('Billing Information') ?>
			</h3>
			<div class="col-1">
				<?php $_address=$this->getBillingAddress() ?>
				<h4>
					<?php echo $this->__('Billing Address') ?>
					<span class="spacer"> | </span>
					<a class="egov-pencile"
					   href="<?php echo $this->getAddressesEditUrl() ?>"
					   title="<?php echo $this->__('Billing Address') ?> <?php echo $this->__('Change') ?>"> </a>
				</h4>
				<address id="invoiceAddress">
					<?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
				</address>
			</div>
			<div class="col-2">
				<h4>
					<?php echo $this->__('Payment Method') ?>
					<span class="spacer"> | </span>
					<a class="egov-pencile"
						 href="<?php echo $this->getEditBillingUrl() ?>"
						 title="<?php echo $this->__('Payment Method') ?> <?php echo $this->__('Change') ?>"> </a>
				</h4>
				<input type="hidden" name="payment[cc_number]"
					value="<?php echo $this->htmlEscape($this->getPayment()->getCcNumber())?>" />
				<input type="hidden" name="payment[cc_cid]"
					value="<?php echo $this->htmlEscape($this->getPayment()->getCcCid())?>" />
				<?php echo $this->getPaymentHtml() ?>
			</div>
		</div>
		<?php if(!$this->isVirtual()):?>
		<h3>
			<?php echo $this->__('Shipping Information') ?>
		</h3>
		<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
		<?php  $_address = $this->getShippingAddress() ?>
		<div class="col2-set">
			<div class="col-1">
				<?php if(!$this->isStorePickup()):?>
				<h4>
					<?php echo $this->__('Shipping to') ?>
					<span class="spacer"> | </span>
					<a class="egov-pencile"
						 href="<?php echo $this->getEditShippingUrl() ?>"
						 title="<?php echo $this->__('Shipping to') ?> <?php echo $this->__('Change') ?>"> </a>
				</h4>
				<address id="shippingAddress">
					<?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
				</address>
				<?php endif;?>

			</div>

			<div class="col-2">
				<h4>
					<?php echo $this->__('Shipping Method') ?>
					<span class="spacer"> | </span>
					<a class="egov-pencile"
						 href="<?php echo $this->getEditShippingmethodUrl() ?>"
						 title="<?php echo $this->__('Shipping Method') ?> <?php echo $this->__('Change') ?>"> </a>
				</h4>
				<?php if($_rate=$this->getShippingAddressRate($_address)): ?>
				<div class="overview_shipping">
					<?php
					if($_rate->getCarrierTitle() === $_rate->getMethodTitle())
						echo $_rate->getCarrierTitle();
					else
						echo $_rate->getCarrierTitle() ." (" . $_rate->getMethodTitle().")";
					?>
					<br /> <strong>Versandkosten:&nbsp;</strong>
					<?php $_excl = $this->getShippingPriceExclTax($_address); ?>
					<?php $_incl = $this->getShippingPriceInclTax($_address); ?>
					<?php if ($this->helper('tax')->displayShippingPriceExcludingTax()):?>
						<?php echo $_excl; ?>
					<?php endif;?>
					<?php if ($this->helper('tax')->displayShippingPriceIncludingTax()):?>
						<?php echo $_incl; ?>
					<?php endif;?>
					<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
						<?php echo sprintf('%s (%s %s)', $_excl, $this->__('Incl. Tax'), $_incl); ?>
					<?php endif; ?>
				</div>
				<?php endif; ?>


			</div>
		</div>
		<?php endif; ?>

		<div class="col1-wide">

			<table class="data-table" id="checkout-review-table">
				<?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
				<col />
				<col width="80" />
				<col width="80" />
				<col width="10" />
				<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
				<col width="80" />
				<col width="80" />
				<?php endif; ?>
				<thead>
					<tr>
						<th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
						<th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
						<th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Qty') ?></th>
						<th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
					</tr>
					<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
					<tr>
						<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
						</th>
						<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
						<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
						</th>
						<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
					</tr>
					<?php endif; ?>
				</thead>

				<tbody>
					<?php foreach($this->getItems() as $_item): ?>
					<?php echo $this->getItemHtml($_item)?>
					<?php endforeach ?>
				</tbody>
			</table>
			<table id="checkout-review-totals-table" class="data-table">
				<?php echo $this->getChildHtml('totals'); ?>
			</table>
		</div>

		<div class="buttons-set" id="review-buttons-container">
			<a href="<?php echo $this->getBackUrl() ?>"class="button"><?php echo $this->__('Back') ?> </a>
			<a class="button" href="<?php echo $this->getUrl() ?>">
			    <span><?php echo $this->__('Continue Shopping') ?></span>
			</a>
			<button type="submit" class="button" id="review-button">
				<span><?php echo $this->__('Buy for %s', $this->helper('checkout')->getQuote()->getStore()->formatPrice($this->getTotal(), false)) ?> </span>
			</button>
		</div>
    	<span id="review-please-wait" class="please-wait"
	          style="display: none;"> <img
			  src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
			  alt="<?php echo $this->__('Please Wait') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
		</span>
	</fieldset>
</form>
