<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * @see Mage_Page_Block_Template_Links
 */

$_links = $this->getLinks();
$_homeUrl = Mage::app()->getStore()->getHomeUrl();
$_storeCode = Mage::app()->getStore()->getCode();

if ( strpos($_homeUrl, $_storeCode) ) {
    $_startPos = strpos( $_homeUrl, 'index.php' ) + strlen('index.php') + strlen($_storeCode) + 2;
}
else {
    $_startPos = strpos( $_homeUrl, 'index.php' ) + strlen('index.php') + 1;
}

if(count($_links)>0):
    $_allowedRegister = Mage::getStoreConfig('customer/create_account/register_user_on_login', $this->getStoreId());

    foreach($_links as $id => $_link) {
        if ( !$_allowedRegister && ($_link->getTitle() == $this->__('Register')) ) {
            unset( $_links[$id] );
        }
    }
?>
<div class="links">
    <?php if($this->getTitle()): ?>
    <div class="block-title"><strong><span><?php echo $this->__($this->getTitle()); ?></span></strong></div>
    <?php endif; ?>
    <ul<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
        <?php foreach($_links as $_link): ?>
            <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
                <?php echo $_link->toHtml() ?>
            <?php else: ?>
                <?php
                    $_url = $_link->getUrl();
                    $_tmp = substr($_url, $_startPos);
                    $_tmp = substr($_tmp, 0, strpos($_tmp, '/?') );
                    $_tmp = str_replace('/', '-', $_tmp);
                ?>
                <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>>
                    <?php echo $_link->getBeforeText() ?>
                    <a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?> id="<?php echo $_tmp; ?>" name="<?php echo $_tmp; ?>">
                        <?php echo $_link->getLabel() ?>
                    </a>
                    <?php echo $_link->getAfterText() ?>
                </li>
            <?php endif;?>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
