<?php
$url      = str_replace(Mage::helper('core/url')->getHomeUrl(), '', Mage::helper('core/url')->getCurrentUrl());
$varname  = str_replace('/', '', $url) . '_active';
$$varname = 'active';
?>
<div class="block block-links">
    <div class="block-title">
	    <h2><?php echo $this->helper('herausgeberbox')->__('Publisher')?></h2>
	</div>
	<div class="block-content">
	    <div id="jumptarget<?php echo $this->getNameInLayout();?>">
	        <ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
	            <li class="last <?php echo $agb_active; ?>">
	                <a href="<?php echo $this->getUrl("agb");?>"><?php echo Mage::helper('herausgeberbox')->__('AGB')?></a>
                </li>
                <?php if ($this->checkIfActive("impressum")): ?>
                <li class="last <?php echo $impressum_active; ?>">
                    <a href="<?php echo $this->getUrl("impressum");?>"><?php echo $this->helper('herausgeberbox')->__('Impress')?></a>
                </li>
                <?php endif;?>
                <?php if ($this->checkIfActive("contact")): ?>
                <li class="last <?php echo $contact_active; ?>">
                    <a href="<?php echo $this->getUrl("contact");?>"><?php echo Mage::helper('herausgeberbox')->__('Contact')?></a>
                </li>
                <?php endif;?>
                <?php if ($this->checkIfActive("esignatur")): ?>
                <li class="last <?php echo $esignatur_active; ?>">
                    <a href="<?php echo $this->getUrl("esignatur");?>"><?php echo Mage::helper('herausgeberbox')->__('eSignature')?></a>
                </li>
                <?php endif;?>
                <?php if ($this->checkIfActive("rechtlichehinweise")): ?>
                <li class="last <?php echo $rechtlichehinweise_active; ?>">
                    <a href="<?php echo $this->getUrl("rechtlichehinweise");?>"><?php echo Mage::helper('herausgeberbox')->__('Legal Informations')?></a>
                </li>
                <?php endif;?>
                <?php if ($this->checkIfActive("behoerdenwegweiser")): ?>
                <li class="last <?php echo $behoerdenwegweiser_active; ?>">
                    <a href="<?php echo $this->getUrl("behoerdenwegweiser");?>"><?php echo Mage::helper('herausgeberbox')->__('Authority Finder')?></a>
                </li>
                <?php endif;?>
                <?php if ($this->checkIfActive("widerruf")): ?>
		        <li class="last <?php echo $widerruf_active; ?>">
		        	<a href="<?php echo $this->getUrl("widerruf");?>"><?php echo Mage::helper('herausgeberbox')->__('Revocation')?></a>
		        </li>
		        <?php endif;?>
		        <?php if ($this->checkIfActive("widerruf")): ?>
		        <li class="last <?php echo $lieferung_active; ?>">
		        	<a href="<?php echo $this->getUrl("lieferung");?>"><?php echo Mage::helper('herausgeberbox')->__('Shipment')?></a>
		        </li>
		        <?php endif;?>
		        <?php if ($this->checkIfActive("zahlung")): ?>
		        <li class="last <?php echo $zahlung_active; ?>">
		        	<a href="<?php echo $this->getUrl("zahlung");?>"><?php echo Mage::helper('herausgeberbox')->__('Paymentmethodes')?></a>
		        </li>
		        <?php endif;?>
		        <?php if ($this->checkIfActive("datenschutz")): ?>
		        <li class="last <?php echo $datenschutz_active; ?>">
		        	<a href="<?php echo $this->getUrl("datenschutz");?>"><?php echo Mage::helper('herausgeberbox')->__('Privacy Policy')?></a>
		        </li>
		        <?php endif;?>
		        <?php if ($this->checkIfActive("bestellung")): ?>
		        <li class="last <?php echo $bestellung_active; ?>">
		        	<a href="<?php echo $this->getUrl("bestellung");?>"><?php echo Mage::helper('herausgeberbox')->__('Ordering')?></a>
		        </li>
		        <?php endif;?>

		        <li class="last <?php echo $catalogseo_sitemapcategory_active; ?>">
		        	<a href="<?php echo $this->getUrl("catalog/seo_sitemap/category");?>"><?php echo Mage::helper('herausgeberbox')->__('Sitemap')?></a>
		        </li>
		        <li class="last <?php echo $catalogsearchtermpopular_active; ?>">
		        	<a href="<?php echo $this->getUrl("catalogsearch/term/popular");?>"><?php echo Mage::helper('herausgeberbox')->__('popular Searches')?></a>
		        </li>
		        <li class="last <?php echo $catalogsearchadvanced_active; ?>">
		        	<a href="<?php echo $this->getUrl("catalogsearch/advanced");?>"><?php echo Mage::helper('herausgeberbox')->__('advanced Search')?></a>
		        </li>
		        <li class="last <?php echo $salesguestform_active; ?>">
		        	<a href="<?php echo $this->getUrl("sales/guest/form");?>"><?php echo Mage::helper('herausgeberbox')->__('Orders and Returns')?></a>
		        </li>
		        <li class="last <?php echo $contacts_active; ?>">
		        	<a href="<?php echo $this->getUrl("contacts");?>"><?php echo Mage::helper('herausgeberbox')->__('Contact us')?></a>
		        </li>
            </ul>
        </div>
	</div>

 </div>


