<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<?php echo $this->getChildHtml('bitvmenu') ?>


<header id="header" class="page-header">

    <?php echo $this->getChildHtml('loadingMask') ?>

    <div class="page-header-container">
        <div class="logo-top-row">
            <a class="logo" href="<?php echo $this->getUrl('') ?>">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
            </a>

            <?php
                // In order for the language switcher to display next to logo on smaller viewports, it will be moved here.
                // See app.js for details
            ?>

            <div id="header-function-block">
                <div class="header-function-row">
                    <div id="normal-header-minicart" class="header-function-cell-half">
                        <!-- Cart -->
                        <div class="header-minicart">
                            <?php echo $this->getChildHtml('minicart_head'); ?>
                        </div>
                    </div>
                    <div class="header-function-cell-half">
                        <!-- Store-Switcher -->
                        <div id="big-view-switcher" class="store-language-container">
                            <?php echo $this->getChildHtml('store_language') ?>
                        </div>
                        <?php echo $this->getChildHtml('currency_switcher') ?>
                    </div>
                </div>
                <div class="header-function-row">
                    <div id="full-search" class="header-function-cell-full">
                        <!-- Search -->
                        <div id="header-search" class="skip-content">
                            <?php echo $this->getChildHtml('topSearch') ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="showmobile mobile-top-header">
                <h1><?php echo Mage::getStoreConfig('general/store_information/name'); ?></h1>
                <div id="small-view-switcher" class="store-language-container"></div>
            </div>

            <div class="showmobile mobile-top-store">
                <div id="mobile-header-search"></div>
            </div>
        </div>

        <div class="showmobile mobile-welcome">
            <span class="welcome-msg">
                <?php echo $this->getChildHtml('welcome') ?>
            </span>
        </div>

        <div class="showmobile mobile-navigation">
            <div id="jumptargetheader" class="account-cart-wrapper">
	            <a href="#header-nav" class="skip-link skip-nav" data-target-element="#mobile-nav">
	                <span class="icon"></span>
	                <span class="label"><?php echo $this->__('Menu'); ?></span>
	            </a>
	            <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" id="egov-account-menu" data-target-element="#header-account" class="skip-link skip-account">
                    <span class="icon egov-user"></span>
                    <span class="label"><?php echo $this->__('Account'); ?></span>
                </a>
                <div id="mobile-header-minicart" class="header-minicart">
                    <?php echo $this->getChildHtml('minicart_head'); ?>
                </div>
            </div>
        </div>

        <!-- Skip Links -->

        <div class="skip-links">
            <?php echo $this->getChildHtml('topLinks') ?>

            <a href="#header-nav" class="skip-link skip-nav">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Menu'); ?></span>
            </a>

            <a href="#header-search" class="skip-link skip-search">
                <span class="icon"></span>
                <span class="label"><?php echo $this->__('Search'); ?></span>
            </a>
            <div class="welcome-header">
                <h1 class="header-position"><?php echo Mage::getStoreConfig('general/store_information/name'); ?></h1>
                <span class="welcome-msg">
                    <?php echo $this->getChildHtml('welcome') ?>
                    <?php echo $this->getChildHtml('accountLinks') ?>
                </span>
            </div>
        </div>

        <!-- Navigation -->
        <div id="header-nav" class="skip-content">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>

        <!-- Account -->
        <div id="header-account" class="skip-content">
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>


        <!-- eGov-Menu -->
        <div id="egov-menu" class="skip-content">
            <?php echo $this->getChildHtml('topEgovmenu') ?>
        </div>

    </div>
</header>

<?php echo $this->getChildHtml('topContainer'); ?>
