<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
        <div class="col2-set egov-account-login">

            <div class="page-title">
                <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                        <?php echo $this->__('Login or Create an Account') ?>
                    <?php else: ?>
                        <?php echo $this->__('Login'); ?>
                    <?php endif; ?></h1>
            </div>


            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
            <div class="col-1 new-users">
                <form action="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>" method="get" id="register-form" class="scaffold-form">
                    <h2><?php echo $this->__('New Here?') ?></h2>
                    <div class="content">
                        <p class="form-instructions">
                            <?php echo $this->__('Registration is free and easy!') ?>
                        </p>
                        <ul class="benefits">
                            <li><?php echo $this->__('Faster checkout') ?></li>
                            <li><?php echo $this->__('Save multiple shipping addresses') ?></li>
                            <li><?php echo $this->__('View and track orders and more') ?></li>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2">
                            <?php echo $this->__('Create an Account') ?>
                        </button>
                    </div>
                </form>
            </div>
            <?php endif; ?>

            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>col-2<?php else: ?>col-1<?php endif; ?> registered-users">
                <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
                    <?php echo $this->getBlockHtml('formkey'); ?>
                    <h2><?php echo $this->__('Already registered?') ?></h2>
                    <div class="content fieldset">
                        <p class="form-instructions">
                            <?php echo $this->__('If you have an account with us, please log in.') ?>
                        </p>
                        <p class="required">
                            <?php echo $this->__('* Required Fields') ?>
                        </p>
                        <ul class="form-list">
                            <li>
                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
                                </div>
                            </li>
                            <li>
                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <li>
                            </li>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                    </div>
                    <div class="button-recovery">
                        <a class="button" href="<?php echo $this->getForgotPasswordUrl() ?>">
                            <?php echo $this->__('Forgot Your Password?') ?>
                        </a>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2">
                            <?php echo $this->__('Login') ?>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
