<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

        <p class="form-instructions">
            <?php echo $this->__('Please enter the following information to create your account.') ?>
        </p>

        <div class="fieldset wide no-space">
            <ul class="form-list">
                <li class="fields fullwide">
                  <?php
                    echo $this->getLayout()->createBlock('customer/widget_name')
                              ->setObject($this->getFormData())
                              ->setForceUseCustomerAttributes(true)->toHtml();
                  ?>
                </li>
                <li class="fields halfwide">
                    <div class="field">
                        <label for="email_address">
                            <span class="required">*</span>
                            <?php echo $this->__('Email Address') ?>
                        </label>
                        <input tabindex="5" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
              <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
              <?php if ($_dob->isEnabled()): ?>
                <li class="fields fullwide">
                    <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
                </li>
              <?php endif ?>
              <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
              <?php if ($_gender->isEnabled()): ?>
                <li class="fields fullwide">
                    <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
                </li>
              <?php endif ?>
            </ul>
        </div>

      <?php if($this->getShowAddressFields()): ?>
        <input type="hidden" name="create_address" value="1" />
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1" />

      <?php $companyAttr = Mage::getModel('eav/entity_attribute')->loadByCode('customer', 'company') ?>
      <?php if ($companyAttr && !$companyAttr->isEmpty()) : ?>
        <div class="fieldset wide no-space">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company">
                            <?php echo $this->__('Company') ?>
                        </label>
			          				<input tabindex="6" type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" maxlength="27" />
			          		</div>
		            </li>
            </ul>
        </div>
      <?php endif ?>

        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('company')):?>
                <li class="fields">
                    <div class="field">
                        <label for="company">
                            <?php echo $this->getFieldRequiredHtml('company')?>
                            <?php echo $this->__('Company') ?>
                        </label>
                        <input tabindex="6" type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </li>
              <?php endif ?>
              <?php if($this->isFieldVisible('telephone')):?>
                <li class="fields">
                    <div class="field">
                        <label for="telephone">
                            <?php echo $this->getFieldRequiredHtml('telephone')?>
                            <?php echo $this->__('Telephone') ?>
                        </label>
                        <input tabindex="8" type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                    </div>
                </li>
              <?php endif ?>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
              <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
              <?php if ($_taxvat->isEnabled()): ?>
                <li class="fields">
                    <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
                </li>
              <?php else: ?>
                <li class="dummy">&nbsp;</li>
              <?php endif ?>
              <?php if($this->isFieldVisible('fax')):?>
                <li class="fields">
	                  <div class="field">
	                      <label for="fax">
	                          <?php echo $this->getFieldRequiredHtml('fax')?>
	                          <?php echo $this->__('Fax') ?>
	                      </label>
	                      <input tabindex="9" type="text" name="fax" id="fax" value="<?php echo $this->htmlEscape($this->getFormData()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php if ($this->isFieldRequired('fax')):?>required-entry<?php endif;?>" maxlength="32"/>
	                  </div>
	              </li>
              <?php endif ?>
            </ul>
        </div>

        <div class="fieldset wide no-space">
            <ul class="form-list">
              <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="fields">
                    <div class="field">
                        <label for="street_1">
                            <span class="required">*</span>
                            <?php echo $this->__('Street Address') ?>
                        </label>
                        <input tabindex="10" type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <div class="field">
                        <label for="billing:street<?php echo $_i ?>">
                            <?php echo $this->__('Street Address %s', $_i) ?>
                        </label>
                        <input tabindex="11" type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                  <?php endfor; ?>
                </li>
            </ul>
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('postcode')):?>
                <li class="fields">
                    <div class="field">
                        <label for="zip">
                            <?php echo $this->getFieldRequiredHtml('postcode')?>
                            <?php echo $this->__('Zip/Postal Code') ?>
                        </label>
                        <input tabindex="12" type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                </li>
              <?php endif; ?>
              <?php if($this->isFieldVisible('region')):?>
                <li class="fields">
                    <div class="field">
                        <label for="region_id">
                            <?php echo $this->getFieldRequiredHtml('region')?>
                            <?php echo $this->__('State/Province') ?>
                        </label>
                        <select tabindex="14" id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('city')):?>
                <li class="fields">
                    <div class="field">
                        <label for="city">
                            <?php echo $this->getFieldRequiredHtml('city')?>
                            <?php echo $this->__('City') ?>
                        </label>
                        <input tabindex="13" type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </li>
              <?php endif; ?>
              <?php if($this->isFieldVisible('country_id')):?>
                <li class="fields">
                    <div class="field">
                        <label for="country">
                            <?php echo $this->getFieldRequiredHtml('country_id')?>
                            <?php echo $this->__('Country') ?>
                        </label>
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>
      <?php endif ?>

        <div class="fieldset half-space">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password">
                            <span class="required">*</span>
                            <?php echo $this->__('Password') ?>
                        </label>
                        <input tabindex="16" type="password" name="password" id="password" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="confirmation">
                            <span class="required">*</span>
                            <?php echo $this->__('Confirm Password') ?>
                        </label>
                        <input tabindex="17" type="password" name="confirmation" title="<?php echo $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                    </div>
                </li>
            </ul>
        </div>

        <div class="fieldset wide no-space">
            <ul class="form-list">
              <?php echo $this->getChildHtml('form.additional.info'); ?>
              <?php if ($this->isNewsletterEnabled()): ?>
                <li class="fields">
                    <div class="field">
                        <input tabindex="18" type="checkbox" name="is_subscribed" title="<?php echo $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    </div>
                </li>
              <?php endif ?>
              <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>


      <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
        <input name="context" type="hidden" value="checkout" />
      <?php endif; ?>

        <p class="required"><?php echo $this->__('* Required Fields') ?></p>

        <div class="buttons-set">
            <button tabindex="19" class="button back-button" title="<?php echo $this->__('Back') ?>" onclick="window.location.href='<?php echo $this->escapeUrl($this->getBackUrl()) ?>'">
                <small>&laquo; </small>
                <?php echo $this->__('Back') ?>
            </button>
            <button tabindex="20" class="button" type="submit" title="<?php echo $this->quoteEscape($this->__('Register')) ?>">
                <?php echo $this->__('Register') ?>
            </button>
        </div>
    </form>

    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        $j('#prefix').attr('tabindex', '1');
        $j('#firstname').attr('tabindex', '2');
        $j('#middlename').attr('tabindex', '3');
        $j('#lastname').attr('tabindex', '4');
        $j('#taxvat').attr('tabindex', '7');
        $j('#country').attr('tabindex', '15');

        $j('#firstname').focus();
    //]]>
    </script>
</div>
