<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Egovs_Base_Block_Customer_Form_Register */
?>
<!--Sprungziel Tastatursteuerung -->
<div id="jumptarget<?php echo $this->getNameInLayout();?>"></div>

<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data" autocomplete="off">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <input type="hidden" name="method" value="register" />
        <?php echo $this->getBlockHtml('formkey'); ?>

        <p class="form-instructions">
            <?php echo $this->__('Please enter the following information to create your account.') ?>
        </p>

        <div class="fieldset wide half-space">
            <ul class="form-list">
                <li class="fields fullwide">
                  <?php
                    echo $this->getLayout()->createBlock('egovsbase/customer_widget_name')
                              ->setMethod('register')
                              ->setObject($this->getFormData())
                              ->setForceUseCustomerAttributes(true)->toHtml();
                  ?>
                </li>
                <li class="fields halfwide" id="adress-new-email">
                    <div class="field">
                        <label for="email_address">
                            <span class="required">*</span>
                            <?php echo $this->__('Email Address') ?>
                        </label>
                        <input tabindex="6" type="email" spellcheck="false" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <li class="fields fullwide" id="adress-new-dob-gender">
                  <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                  <?php if ($_dob->isEnabled()): ?>
                    <div id="birthday-box" class="field">
                        <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
                    </div>
                  <?php endif ?>

                  <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                  <?php if ($_gender->isEnabled()): ?>
                    <div id="gender-box" class="field">
                        <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
                    </div>
                  <?php endif ?>
                </li>
            </ul>
        </div>

      <?php if($this->getShowAddressFields()): ?>
        <input type="hidden" name="create_address" value="1" />
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1" />
        <input type="hidden" name="base_address" value="1" />

        <div class="fieldset wide half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('company')):?>
                <li class="fields" id="adress-new-company">
                    <div class="field">
                    <?php $companyAttr = Mage::getModel('eav/entity_attribute')->loadByCode('customer', 'company') ?>
                    <?php if ($companyAttr && !$companyAttr->isEmpty()) : ?>
                        <label for="company">
                            <?php echo $this->getFieldRequiredHtml('company')?>
                            <?php echo $this->__('Company') ?>
                        </label>
                        <input tabindex="7" type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->isFieldRequired('company') ? 'required-entry' : ''?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        <?php if($this->isAdditionalCompanyVisible()):?>
        			  		<input tabindex="7" type="text" name="company2" id="company2" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany2()) ?>" title="<?php echo $this->__('Company 2') ?>" class="input-text" maxlength="27" />
        			  		<input tabindex="7" type="text" name="company3" id="company3" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany3()) ?>" title="<?php echo $this->__('Company 3') ?>" class="input-text" maxlength="27" />
        			  	<?php endif; ?>
                    <?php endif; ?>
                    </div>
                </li>
				      <?php endif; ?>

              <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li class="fields halfwide" id="adress-new-taxvat">
                    <div class="field">
                        <label for="vat_id">
                            <?php echo $this->getFieldRequiredHtml('taxvat')?>
                            <?php echo $this->__('VAT Number') ?>
                        </label>
                        <input tabindex="8" type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('VAT Number')) ?>" id="vat_id" class="input-text <?php echo $this->isFieldRequired("taxvat") ? 'required-entry' : ''?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
				      <?php endif; ?>
            </ul>
        </div>

      <?php if($this->isFieldVisible('street')):?>
        <div class="fieldset wide half-space">
            <ul class="form-list">
              <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="fields" id="adress-new-street">
                    <div class="field">
                        <label for="street_1">
                            <?php echo $this->getFieldRequiredHtml('street')?>
                            <?php echo $this->__('Street Address') ?>
                        </label>
                        <input tabindex="9" type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $this->isFieldRequired('street') ? 'required-entry' : ''?> <?php echo $_streetValidationClass ?>" />
                      <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                      <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <input tabindex="9" type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                      <?php endfor; ?>
                    </div>
                </li>
            </ul>
        </div>
      <?php endif; ?>

        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('postcode')):?>
                <li class="fields" id="adress-new-zip">
                    <div class="field">
                        <label for="zip">
                            <?php echo $this->getFieldRequiredHtml('postcode')?>
                            <?php echo $this->__('Zip/Postal Code') ?>
                        </label>
                        <input tabindex="10" type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->isFieldRequired('postcode') ? 'required-entry' : 'egov'?>" />
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('city')):?>
                <li class="fields" id="adress-new-city">
                    <div class="field">
                        <label for="city">
                            <?php echo $this->getFieldRequiredHtml('city')?>
                            <?php echo $this->__('City') ?>
                        </label>
                        <input tabindex="11" type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->isFieldRequired('city') ? 'required-entry' : ''?>" id="city" />
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('region')):?>
                <li class="fields" id="adress-new-region">
                    <div class="field">
                        <label for="region_id">
                            <?php echo $this->getFieldRequiredHtml('region') ?>
                            <?php echo $this->__('State/Province') ?>
                        </label>
                        <select tabindex="12" id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->isFieldRequired('region') ?  'required-entry' : ''; ?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('country_id')):?>
                <li class="fields" id="adress-new-contry">
                    <div class="field">
                        <label for="country">
                            <?php echo $this->getFieldRequiredHtml('country_id')?>
                            <?php echo $this->__('Country') ?>
                        </label>
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </li>
              <?php endif; ?>
            </ul>
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('telephone')):?>
                <li class="fields" id="adress-new-telephone">
                    <div class="field">
                        <label for="telephone">
                            <?php echo $this->getFieldRequiredHtml('telephone')?>
                            <?php echo $this->__('Telephone') ?>
                        </label>
                        <input tabindex="14" type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->isFieldRequired('telephone') ? 'required-entry' : ''?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                    </div>
                </li>
              <?php endif ?>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
              <?php if($this->isFieldVisible('fax')):?>
                <li class="fields" id="adress-new-fax">
	                  <div class="field">
	                      <label for="fax">
	                          <?php echo $this->getFieldRequiredHtml('fax')?>
	                          <?php echo $this->__('Fax') ?>
	                      </label>
	                      <input tabindex="15" type="text" name="fax" id="fax" value="<?php echo $this->htmlEscape($this->getFormData()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->isFieldRequired('fax') ? 'required-entry' : ''?>" maxlength="32"/>
	                  </div>
	              </li>
              <?php endif ?>
            </ul>
        </div>
      <?php else: ?>
        <div class="fieldset wide half-space">
            <ul class="form-list">
                <li class="fields" id="adress-new-company">
                    <div class="field">
                        <label for="company">
                            <?php echo $this->getFieldRequiredHtml('company')?>
                            <?php echo $this->__('Company') ?>
                        </label>
                        <input tabindex="7" type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </li>
            </ul>
        </div>
      <?php endif ?>

        <div style="display:none;">
            <!-- Dieses Feld verhindet nur den Auto-Fill durch den Browser -->
            <input name="autofill-prevent" id="autofill-prevent" type="text" value="-" readonly="readonly" />
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password">
                            <span class="required">*</span>
                            <?php echo $this->__('Password') ?>
                        </label>
                        <input tabindex="16" type="password" name="password" id="password" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset half-space">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="confirmation">
                            <span class="required">*</span>
                            <?php echo $this->__('Confirm Password') ?>
                        </label>
                        <input tabindex="17" type="password" name="confirmation" title="<?php echo $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                    </div>
                </li>
            </ul>
        </div>

        <div class="fieldset half-space">
            <ul class="form-list">
              <?php echo $this->getChildHtml('form.additional.info'); ?>
              <?php if ($this->isNewsletterEnabled()): ?>
                <li class="fields">
                    <div class="field">
                        <input tabindex="18" type="checkbox" name="is_subscribed" title="<?php echo $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php echo $this->getFormData()->getIsSubscribed() ? ' checked="checked"' : ''?> class="checkbox" />
                        <label id="is-subscribed" for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    </div>
                </li>
              <?php endif ?>
              <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>

      <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
        <input name="context" type="hidden" value="checkout" />
      <?php endif; ?>

        <p class="required"><?php echo $this->__('* Required Fields') ?></p>

        <div class="buttons-set">
            <button tabindex="19" class="button back-button" title="<?php echo $this->__('Back') ?>" onclick="window.location.href='<?php echo $this->escapeUrl($this->getBackUrl()) ?>'">
                <small>&laquo; </small>
                <?php echo $this->__('Back') ?>
            </button>
            <button tabindex="20" class="button" type="submit" title="<?php echo $this->quoteEscape($this->__('Register')) ?>">
                <?php echo $this->__('Register') ?>
            </button>
        </div>
    </form>

    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>

        if( $j('#region').hasClass('required-entry') ) {
            $j('#adress-new-region label').prepend('<span class="required">*</span>');
        }

        function setFirstRegionForDe(element) {
            if ( element.val() == 'DE' ) {
                $j('#region_id').children('option:first').text( pleaseSelect );
            }
        }

        $j('#country').on('change', function(){
            setFirstRegionForDe( $j(this) );
        });

        var pleaseSelect = '<?php echo $this->__('-- Please Select --'); ?>';
        var TabData = {'prefix': 1, 'firstname': 2, 'middlename': 3, 'lastname': 4, 'suffix': 5, 'country': 13};
        setTabIndex(TabData);

        $j(document).ready(function(){
            $j('#firstname').focus();
            setFirstRegionForDe( $j('#country') );
        });
    </script>
</div>
