    <h3><?php echo $this->getTitle();?></h3>
<?php
var_dump( $this->getOptions() );
?>
    <div class="virtualgeo-georeft">
      <?php foreach($this->getOptions() as $option):?>
        <input type="radio" name="geohref" value="<?php echo $this->getGeoref(); ?>"<?php echo  $option->getIsDefault() ? ' checked="checked"' : ''; ?> />
        <span><?php echo $option->getCode();?> </span>
        <span><?php echo $option->getName();?> </span>
        <span><?php echo $option->getDescription();?> </span>
      <?php endforeach;?>
    </div>
