<?php 
/* @var $this Bkg_VirtualGeo_Block_Catalog_Product_View_Components_Georef */
?>
<?php if($this->hasOptions()):?>
    <h3>
        <?php echo $this->getTitle(); ?>
        <div class="select-options" id="title-<?php echo $this->getHtmlID(); ?>"></div>
    </h3>
    <div class="virtualgeo-default">
      <?php foreach($this->getOptions() as $option): ?>
        <?php $_default = ($option->getIsDefault() == '1' ? ' checked="checked"' : ''); ?>
        <?php //var_dump($option); ?>
        <div class="option-row">
            <div>
                <input type="radio"
                       class="radio"
                       name="bundle_option[<?php echo $option->getOptionId(); ?>]"
                       value="<?php echo $option->getSelectionId(); ?>"
                       data-id="<?php echo $this->getHtmlID(); ?>"
                       data-code="<?php echo $option->getCode(); ?>"
                       data-epsg="<?php echo $option->getEpsgCode(); ?>"
                       data-shortname="<?php echo $option->getShortname(); ?>"
                       data-name="<?php echo $option->getName();?>"
                       <?php echo $_default; ?> />
            </div>
            <div class="virtualgeo-name"><?php echo $option->getName();?></div>
            <div class="virtualgeo-desc"><?php echo $option->getDescription();?></div>
        </div>
      <?php endforeach; ?>
    </div>
<?php endif;?>