
    <h3><?php echo $this->getTitle();?></h3>
    <div class="virtualgeo-structure">
      <?php foreach($this->getOptions() as $option):?>
        <span><?php echo $option->getCode();?> </span>
        <span><?php echo $option->getName();?> </span>
        <span><?php echo $option->getDescription();?> </span>
        <span><?php echo $option->getIsDefault();?> </span>
      <?php endforeach;?>
    </div>
