<?php 
/* @var $this Bkg_VirtualGeo_Block_Catalog_Product_View_Components_Toll */
?>
    <h3>
        <?php echo $this->getTitle(); ?>
        <div class="select-options" id="title-<?php echo $this->getHtmlID(); ?>"></div>
    </h3>
    <div class="virtualgeo-default">
      
<?php
foreach ($this->getTollCategory()->getActiveTolls() as $toll) {
    /**
     * @var Bkg_Tollpolicy_Model_Toll $toll
     */
    //echo "<span>".$toll->getName()."</span>";
    echo "<fieldset class='virtualgeo-components-toll'>";
    echo "<legend>Internal</legend>";
    echo "<ul>";
    foreach ($toll->getActiveUseTypes(true) as $use) {
        echo "<li>";
        $useId = "virtualgeo-components-toll-" . $use->getId();
        
        $options = $use->getOptions();
        /**
         * @var Bkg_Tollpolicy_Model_Usetype $use
         */
        $label = "<label for='".$useId."'>".$use->getName()."</label>";
        
        if (sizeof($options) == 1) {
            /**
             * @var Bkg_Tollpolicy_Model_Useoptions $opt
             */
            $opt = array_values($options)[0];
            $val = $opt->getCode();
            if (empty($val)) {
                $val = $opt->getId();
            }
            echo "<input id='".$useId."' name='".$useId."' value='".$val."' type='checkbox'/>";
            echo $label;
        } else {
            echo $label;
            echo "<select id='".$useId."' name='".$useId."'>";
            echo "<option></option>";
            foreach ($options as $opt) {
                /**
                 * @var Bkg_Tollpolicy_Model_Useoptions $opt
                 */
                echo "<option value='".$opt->getCode()."'>".$opt->getName()."</option>";
            }
            echo "</select>";
        }
        echo "</li>";
    }
    echo "</ul>";
    echo "</fieldset>";
    
    echo "<fieldset class='virtualgeo-components-toll'>";
    echo "<legend>External</legend>";
    echo "<ul>";
    foreach ($toll->getActiveUseTypes(false) as $use) {
        echo "<li>";

        $useId = "virtualgeo-components-toll-" . $use->getId();
        $options = $use->getOptions();
        /**
         * @var Bkg_Tollpolicy_Model_Usetype $use
         */
        $label = "<label for='".$useId."'>".$use->getName()."</label>";
        
        if (sizeof($options) == 1) {
            /**
             * @var Bkg_Tollpolicy_Model_Useoptions $opt
             */
            $opt = array_values($options)[0];
            $val = $opt->getCode();
            if (empty($val)) {
                $val = $opt->getId();
            }
            echo "<input id='".$useId."' name='".$useId."' value='".$val."' type='checkbox'/>";
            echo $label;
        } else {
            echo $label;
            echo "<select id='".$useId."' name='".$useId."'>";
            echo "<option></option>";
            foreach ($options as $opt) {
                /**
                 * @var Bkg_Tollpolicy_Model_Useoptions $opt
                 */
                echo "<option value='".$opt->getCode()."'>".$opt->getName()."</option>";
            }
            echo "</select>";
        }
        echo "</li>";
    }
    echo "</ul>";
    echo "</fieldset>";
}
//die;
?>
    </div>
