<?php 
/* @var $this Bkg_VirtualGeo_Block_Catalog_Product_View_Components_Toll */
?>
    <h3>
        <?php echo $this->escapeHtml($this->getTitle()); ?>
        <span class="select-options" id="title-<?php echo $this->getHtmlID(); ?>"></span>
    </h3>
    <div class="virtualgeo-default">
      
<?php
foreach ($this->getTollCategory()->getActiveTolls() as $toll) {
    /**
     * @var Bkg_Tollpolicy_Model_Toll $toll
     */
    //echo "<span>".$toll->getName()."</span>";
    echo "<fieldset class='virtualgeo-components-toll' style='border: 1px solid #c0c0c0; padding: 5px;'>";
    echo "<legend><input id='virtualgeo-components-toll-int' name='virtualgeo-components-toll[int][use]' value='' type='checkbox'/>".$this->__('Internal Usage')."</legend>";

    echo "<ul>";
    foreach ($toll->getActiveUseTypes(true) as $use) {
        echo "<li>";
        $useId = "virtualgeo-components-toll-" . $use->getId();
        $useName = "virtualgeo-components-toll[int][" . $use->getId()."]";



        /**
         * @var Bkg_Tollpolicy_Model_Usetype $use
         */
        $label = "<label for='".$useId."'>".$this->escapeHtml($use->getName())."</label>";

        $options = $use->getOptions();

        if (sizeof($options) == 1) {
            /**
             * @var Bkg_Tollpolicy_Model_Useoptions $opt
             */
            $opt = array_values($options)[0];
            $val = $this->escapeHtml($opt->getCode());
            if (empty($val)) {
                $val = $opt->getId();
            }

            echo "<input id='" . $useId . "' name='" . $useName . "' value='" . $val . "' type='checkbox'/>";
            echo $label;

            if($opt->getUserdefined() == 'text')
            {
                echo "<p> <input id='" . $useId . "' name='" . $useName . "_value' value='' type='text'/></p>";

            }

        } else {
            echo $label;
            echo "<select id='".$useId."' name='".$useName."'>";
            echo "<option></option>";
            foreach ($options as $opt) {
                /**
                 * @var Bkg_Tollpolicy_Model_Useoptions $opt
                 */
                echo "<option value='".$this->escapeHtml($opt->getCode())."'>".$this->escapeHtml($opt->getName())."</option>";
            }
            echo "</select>";
        }
        echo "</li>";
    }
    echo "</ul>";
    echo "</fieldset>";

    echo "<fieldset class='virtualgeo-components-toll' style='border: 1px solid #c0c0c0; padding: 5px;'>";
    echo "<legend><input id='ext' name='virtualgeo-components-toll[ext][use]' value='' type='checkbox'/>". $this->__('External Usage')."</legend>";

    echo "<ul>";
    foreach ($toll->getActiveUseTypes(false) as $use) {
        echo "<li>";

        $useId = "virtualgeo-components-toll-" . $use->getId();
        $useName = "virtualgeo-components-toll[ext][" . $use->getId()."]";
        
        $options = $use->getOptions();
        /**
         * @var Bkg_Tollpolicy_Model_Usetype $use
         */
        $label = "<label for='".$useId."'>".$this->escapeHtml($use->getName())."</label>";
        
        if (sizeof($options) == 1) {
            /**
             * @var Bkg_Tollpolicy_Model_Useoptions $opt
             */
            $opt = array_values($options)[0];
            $val = $this->escapeHtml($opt->getCode());
            if (empty($val)) {
                $val = $opt->getId();
            }
                echo "<input id='" . $useId . "' name='" . $useName . "' value='' type='checkbox'/>";
                echo $label;

            if($opt->getUserdefined() == 'text')
            {
                echo "<p> <input id='" . $useId . "' name='" . $useName . "_value' value='' type='text'/></p>";

            }

        } else {
            echo $label;
            echo "<select id='".$useId."' name='".$useName."'>";
            echo "<option></option>";
            foreach ($options as $opt) {
                /**
                 * @var Bkg_Tollpolicy_Model_Useoptions $opt
                 */
                echo "<option value='".$this->escapeHtml($opt->getCode())."'>".$this->escapeHtml($opt->getName())."</option>";
            }
            echo "</select>";
        }
        echo "</li>";
    }
    echo "</ul>";
    echo "</fieldset>";
}
//die;
?>
    </div>
