<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$js_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);
?>

<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/jquery-easing-1.3.0.js"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/modernizr.mediaqueries.transforms3d.js"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/responsive-hub.js"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/jquery.silver_track.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/plugins/jquery.silver_track.navigator.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/plugins/jquery.silver_track.responsive_hub_connector.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/plugins/jquery.silver_track.css3_animation.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo $js_url; ?>egovs/silver_track/plugins/jquery.silver_track.circular_navigator.js" charset="utf-8"></script>
<script type="text/javascript" charset="utf-8">
$j(document).ready(function(){
    var container = $j(".silver-track");
    var track = $j('.product-image-thumbs').silverTrack({
        'itemClass': 'item',
        'mode'     : 'horizontal',
        'easing'   : 'swing',
        'perPage'  : 4
    });

    track.install(new SilverTrack.Plugins.Navigator({
        'prev': $j('a.prev', container),
        'next': $j('a.next', container)
    }));

    track.start();
});
</script>
