<?php if(count($this->getItems()) > 0):?>
<div class="egovs-agreement-text">
    <ol class="checkout-agreements">
      <?php foreach($this->getItems() as $item){?>
        <li>
            <input class="checkbox" type="checkbox" name="agreementtext[<?php echo $item['value']?>]" id="agreementtext[<?php echo $item['value']?>]"value="" />
            <label for="agreementtext[<?php echo $item['value']?>]">
                <?php echo $item['content'] ?>
                <span class="required">*</span>
            </label>
        </li>
      <?php }?>
    </ol>
</div>
<?php endif;?>