<?php
/**
 */
?>


<?php if($this->getTitle()): ?>
    <h3><?php echo $this->getTitle() ?></h3>
<?php endif ?>





<div >
<button class="" onclick="nodeOptions.add();" type="button">New</button>
<button class="btn btn-warning btn-sm" onclick="nodeOptions.edit();" type="button">Rename</button>
<button class="btn btn-danger btn-sm" onclick="nodeOptions.remove();" type="button">Delete</button>
</div>


<div id="jstree_demo" class="demo"></div>

<div id="category_details" ></div>

<script type="text/javascript">
//<![CDATA[
var root_node_title = "<?php echo Mage::helper('sidcms')->__('Root node')?>";
//]]>
</script>

<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>sid/cms/init_menu.js"></script>
<script type="text/javascript">
//<![CDATA[
function init_db_nodes()
{
<?php foreach ($this->getNodes() as $node):
	$parent = $node->getParentId();
	if($node->getParentId())
	{
		$parent = 'node_'.$node->getParentId();
	}
	else{
		$parent = '"root"';
	}
	echo "var node_".$node->getId()." = nodeOptions.add(".$node->toJson().",$parent);"

?>
<?php endforeach;?>
	nodeOptions.open_all();
}

//]]>
</script>

