<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="col2-set">
    <div class="col-1">
        <h2>
            <?php echo $this->__('Default Billing Address') ?>
            <a class="egov-pencile"
               href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"
               title="<?php echo $this->__('Edit Address') ?>"> </a>
        </h2>
        <address>
            <?php echo $this->getPrimaryBillingAddressHtml() ?>
        </address>
    </div>
    <div class="col-2">
        <h2>
            <?php echo $this->__('Default Shipping Address') ?>
            <a class="egov-pencile"
               href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"
               title="<?php echo $this->__('Edit Address') ?>"> </a>
        </h2>
        <address>
            <?php echo $this->getPrimaryShippingAddressHtml() ?>
        </address>
    </div>
</div>
