<?php
/**
 * @see Mage_Checkout_Block_Agreements
 */
?>

<?php if (!$this->getAgreements()) return; ?>
<ul class="form-list group-select">
<?php foreach ($this->getAgreements() as $_a): ?>
		<li class="agree">
			<input type="checkbox" title="<?php echo Mage::helper('checkout')->__('Required. Please agree the following Text: ').$this->escapeHtml($_a->getCheckboxText()) ?>" id="agreement-<?php echo $_a->getId()?>" name="agreement[<?php echo $_a->getId()?>]" value="1" class="checkbox" />
			<label for="agreement-<?php echo $_a->getId()?>">
				<span class="required">*</span>
				<?php
				if ( $_a->getIsHtml() ) {
					echo $_a->getCheckboxText();
				}
				else {
					echo $this->escapeHtml($_a->getCheckboxText());
				}
				?>
			</label>
		</li>
		<li class="agree-content">
			<?php 
			if ( $_a->getIsHtml() ) {
				echo $_a->getContent();
			}
			else {
				echo nl2br($_a->getContent());
			}
			?>
		</li>  
<?php endforeach ?>
</ul>
<p class="required"><?php echo $this->__('* Required Fields') ?></p>
