<?php
/**
 * Multishipping checkout billing information
 *
 * @see Mage_Checkout_Block_Multishipping_Billing
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Billing Information') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="multishipping-billing-form" class="multiple-checkout">
<?php echo $this->getBlockHtml('formkey'); ?>
<div class="col2-set">
    <div class="col-1">
        <h2><?php echo $this->__('Billing Address') ?></h2>
        <?php $_address=$this->getAddress() ?>
        <address><?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?></address>
    </div>
    <div class="col-2">
        <h2><?php echo $this->__('Payment Method') ?></h2>
        <div class="tool-tip" id="payment-tool-tip" style="display:none;">
            <div class="btn-close"><a href="#" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" title="<?php echo $this->__('Close') ?>" /></a></div>
            <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
        </div>
        <!-- Payment methods forms list -->
        <fieldset>
	        <dl class="sp-methods">
	        <?php
	            $_methods       = $this->getMethods();
	            $_methodsCount  = count($_methods);
	        ?>
	        <?php foreach ($_methods as $_method): $_code = $_method->getCode() ?>
	            <dt>
	                <?php if ($_methodsCount > 1): ?>
	                <input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" <?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
	                <?php else :?>
	                <span class="no-display"><input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" checked="checked" class="radio" /></span>
	                <?php endif;?>
	                <label for="p_method_<?php echo $_code ?>"><?php echo $_method->getTitle() ?></label>
	            </dt>
	            
	        <?php endforeach; ?>
	        <?php if($_methodsCount == 0) 
	        	echo '<div class="error-msg">'.$this->__('Sorry,an Error occurs:<br/>Maybe you have exceeded the payment limits or you can not buy this products together. Please contact the Owner of the Webshop!').'</div>'?>
	        </dl>
        <?php echo $this->getChildHtml('checkout_billing_items') ?>
        </fieldset>
    </div>
</div>
   <div class="buttons-set">
        <a href="<?php echo $this->getBackUrl() ?>" class="button"><?php echo $this->__('Back') ?></a>
       <a class="button" href="<?php echo $this->getUrl() ?>"><span><?php echo $this->__('Continue Shopping') ?></span></a>
       <button  class="button" type="submit"><span><?php echo $this->__('Continue') ?></span></button>
    </div>
</form>

