<?php
/**
 * Multishipping checkout shipping template
 *
 * @see Mage_Checkout_Block_Multishipping_Shipping
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Select Shipping Method') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="shipping_method_form" class="multiple-checkout">
	<?php echo $this->getBlockHtml('formkey'); ?>
    <?php foreach ($this->getAddresses() as $_index => $_address): ?>

    <div class="col2-set">
        <div class="col-1">
            <h2><?php echo $this->__('Shipping to') ?> </h2>
            <address><?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?></address>
        </div>
        <div class="col-2">
            <h2><?php echo $this->__('Shipping Method') ?></h2>
			<fieldset>
	            <?php if (!($_shippingRateGroups = $this->getShippingRates($_address))): ?>
	                <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
	            <?php else: ?>
	            <dl class="sp-methods">
	                <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
	                    <dt><?php echo $this->getCarrierName($code) ?></dt>
	                    <dd>
	                        <ul class="form-list group-select">
	                        <?php foreach ($_rates as $_rate): ?>
	                            <li>
	                               <?php if ($_rate->getErrorMessage()): ?>
	                                    <strong><?php echo $_rate->getCarrierTitle() ?>: <?php echo $_rate->getErrorMessage() ?></strong>
	                               <?php else: ?>
	                                    <input type="radio" name="shipping_method[<?php echo $_address->getId() ?>]" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod($_address)) echo ' checked="checked"' ?> class="radio" />
	                                    <label for="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
	                                    <?php $_excl = $this->getShippingPrice($_address, $_rate->getPrice(), false); ?>
	                                    <?php $_incl = $this->getShippingPrice($_address, $_rate->getPrice(), true); ?>
	                                    <?php if ($this->helper('tax')->displayShippingPriceExcludingTax()):?>
											<?php echo $_excl; ?>
										<?php endif;?>
										<?php if ($this->helper('tax')->displayShippingPriceIncludingTax()):?>
											<?php echo $_incl; ?>
										<?php endif;?>
										<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
											<?php echo sprintf('%s (%s %s)', $_excl, $this->__('Incl. Tax'), $_incl); ?>
										<?php endif; ?>
	                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
	                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
	                                    <?php endif; ?>
	                                    </label>
	                               <?php endif ?>
	                            </li>
	                        <?php endforeach; ?>
	                        </ul>
	                    </dd>
	                <?php endforeach; ?>
	            </dl>
	            <?php endif; ?>
			</fieldset>
        </div>

    </div>
    <?php endforeach; ?>

    <div class="buttons-set">
        <a href="<?php echo $this->getBackUrl() ?>" class="button"><?php echo $this->__('Back') ?></a>
       <a class="button" href="<?php echo $this->getUrl() ?>"><span><?php echo $this->__('Continue Shopping') ?></span></a>
       <button  class="button <?php if (!$_shippingRateGroups) : ?> <?php echo 'disabled'; endif; ?>" type="submit" <?php if (!$_shippingRateGroups) : ?> <?php echo 'disabled="disabled"'; endif;?>><span><?php echo $this->__('Continue') ?></span></button>
    </div>
</form>
