<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015-2018 B3 IT Systeme GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * GrandTotal der Order enthält immer den Gesamtpreis inkl. MwSt.
 */

/**
 * Annahme: Falls tax/sales_display/full_summary false dann ist Shop MwSt befreit
 */
$_taxPostfix = Mage::getStoreConfigFlag('tax/sales_display/full_summary') ?
    $this->__('(Incl. Tax)') : $this->__('(Tax Free)');
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getChildHtml('info');?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<table class="data-table orders" id="my-orders-table">
    <col style="width: 14%" />
    <col />
    <col />
    <col style="width: 11%" />
    <col style="width: 11%" />
    <col style="width: 2%" />
    <thead>
        <tr>
            <th class="number"><?php echo $this->__('Order #') ?></th>
            <th class="date"><?php echo $this->__('Date') ?></th>
            <th class="ship"><?php echo $this->__('Ship To') ?></th>
            <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?> <?php echo $_taxPostfix; ?></span></th>
            <th class="status"><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>
            <th class="view">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_orders as $_order): ?>
            <?php /** @var $_order \Mage_Sales_Model_Order */ ?>
        <tr>
            <td class="number">
                <a class=""
                   href="<?php echo $this->getViewUrl($_order) ?>"
                   title="<?php echo $this->__('View Order') ?>"><?php echo $_order->getRealOrderId() ?></a>
            </td>
            <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
            <td class="a-center view">
                <span class="nobr">
                <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <a href="<?php echo $this->getReorderUrl($_order) ?>"
                       class="link-reorder egov-reorder"
                       title="<?php echo $this->__('Reorder') ?>"> </a>
                <?php endif ?>
                </span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
