<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php  $_order = $this->getOrder() ?>
<table class="cart-table data-table linearize-table-large" id="my-orders-table" summary="<?php echo $this->__('Items Ordered') ?>">
    <colgroup>
        <col />
        <col style="width: 11%" />
        <col style="width: 13%" />
        <col style="width: 10%" />
    </colgroup>
    <thead>
        <tr>
            <th><?php echo $this->__('Product') ?></th>
            <th class="a-right">
                <?php echo $this->__('Price') ?>
                <?php if (Mage::getStoreConfig('tax/sales_display/price') == 1): ?>
                    <?php echo sprintf(' (%s)', $this->__('Excl. Tax')) ?>
                <?php else: ?>
                    <?php echo sprintf(' (%s)', $this->__('Incl. Tax')) ?>
                <?php endif; ?>
            </th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right">
                <?php echo $this->__('Subtotal') ?>
                <?php if (Mage::getStoreConfig('tax/sales_display/subtotal') == 1): ?>
                    <?php echo sprintf(' (%s)', $this->__('Excl. Tax')) ?>
                <?php else: ?>
                    <?php echo sprintf(' (%s)', $this->__('Incl. Tax')) ?>
                <?php endif; ?>
            </th>
        </tr>
    </thead>
    <tfoot>
        <?php echo $this->getChildHtml('order_totals') ?>
    </tfoot>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_index = 0; ?>
            <?php $_count = $_items->count(); ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getParentItem()) continue; ?>
        <tbody>
            <?php echo $this->getItemHtml($_item) ?>
            <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
            <tr class="border<?php echo ($_index++ > $_count ?' last':'') ?>" id="order-item-gift-message-<?php echo $_item->getId() ?>" style="display:none;">
                <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
                <td class="gift-message-row" colspan="7">
                    <a href="#" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>');" class="btn-close"><?php echo $this->__('Close') ?></a>
                    <dl class="gift-message">
                        <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dt>
                        <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                        <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></dd>
                    </dl>
                </td>
            </tr>
            <?php endif ?>
        </tbody>
        <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
