﻿<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?>
        <span class="spacer"> | </span>
        <a href="<?php echo $this->getUrl('sales/order/history') ?>"
           class="egov-view-all"
           title="<?php echo $this->__('View All') ?>"> </a>
        <?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table orders" id="my-orders-table">
    <col width="80" />
    <col width="80" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="10" />
        <thead>
            <tr>
                <th class="space number"><?php echo $this->__('Order #') ?></th>
                <th class="space date"><?php echo $this->__('Date') ?></th>
                <th class="space ship"><?php echo $this->__('Ship To') ?></th>
                <th class="space total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th class="space status"><?php echo $this->__('Status') ?></th>
                <th class="space view">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td class="number">
                        <a class=""
                           href="<?php echo $this->getViewUrl($_order) ?>"
                           title="<?php echo $this->__('View Order') ?>"><?php echo $_order->getRealOrderId() ?></a>
                        
                    </td>
                    <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center view">
                        <span class="nobr">
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <a href="<?php echo $this->getReorderUrl($_order) ?>"
                               class="link-reorder egov-reorder"
                               title="<?php echo $this->__('Reorder') ?>"> </a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
