<?php

?>
<?php
/**
 * Totals für Merklisten
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<table id="shopping-cart-totals-table">
    <col />
    <col width="80" />
    <tfoot>
        <?php echo $this->renderTotals('footer'); ?>
    </tfoot>
    <tbody>
        <?php echo $this->renderTotals(); ?>
    </tbody>
</table>
<div class="clear"></div>

<!--Sprungziel Tastatursteuerung -->
<div id="jumptarget<?php echo $this->getNameInLayout();?>">
	<!-- <a href="<?php echo $this->getCheckoutUrl(); ?>" class="totalsorderbutton" title="<?php echo $this->__('Order now')?>"><?php echo $this->__('Order now')?><br /><span class="subtitle">(<?php echo $this->__('Checkout')?>)</span></a>  -->
</div>


