<script type="text/javascript">
    var addCartUrl = '<?php echo $this->getAddUrl();?>';
    var products   = new Array();
    <?php echo $this->getProducts(); ?>
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/quickform.js'); ?>"></script>

<?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="quick_form" action="#" method="post" onsubmit="addCart(); return;">

<fieldset class="form-search">
    <legend>Search Site</legend>
    <label for="search"></label>

    <input id="quicksearch" type="text" class="input-text" name="quicksuggest" value="" autocomplete="off"/>
    <input type="hidden" name="quicksuggest_id" id="_quicksuggest_id" value="0" />
    <button type="button" class="form-button-alt" id="bt_addCart" onclick="addCart();">
		<span>Hinzuf&uuml;gen</span>
	</button>
    <div id="quick_autocomplete" class="search-autocomplete" style="display:none;"></div>
    
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Quick.searchForm('quick_form', 'quicksearch', '');
        //searchForm.initAutocomplete('<?php echo $this->getSuggestUrl();?>', 'quick_autocomplete');
    //]]>
    </script>

</fieldset>

</form>


<div id="quick.card">
	<?php echo $this->getCart();?>
</div>

