<?php
/* @var $this Dwd_Stationen_Block_Catalog_Product_View_Abstract */
/**/
if ( $this->hasStationen() ) {
	$_features  = array();
	$_jsonArray = array();
	
	foreach($this->getStationsList() as $station) {
		$_features[] = array(
				           "type"      => "Feature",
				           'properties'=> array(
				           		             'id'  => $station->getId(),
				           		             'name'=> $station->getName()
				           		          ),
			               'geometry'  => array(
			               		             'type'       => 'Point',
			               		             'coordinates'=> array(
			               		             		             $station->getLon(),
			               		             		             $station->getLat()
			               		             		         )
			               		          )
					   );
	}
	
	$_jsonArray = array(
						"type"=> "FeatureCollection",
						"crs" => array(
								 	'type'      => 'name',
								 	'properties'=> array(
								 				      'name'=> 'EPSG:4326'
									               )
								),
			            'features'=> $_features
					);
}
echo json_encode($_jsonArray);
exit;

?>



<?php if ($this->hasStationen()):?>
{
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:4326"
    }
  },
  "features": [
  <?php foreach($this->getStationsList() as $station){?>
    {
      "type": "Feature",
      "properties": {
        "id": <?php echo $station->getId(); ?>,
        "name": "<?php echo $station->getName(); ?>"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          <?php echo $station->getLon()?>,
          <?php echo $station->getLat()?>
        ]
      }
    }
  <?php }?>
  ]
}
<?php endif;?>