<?php
/* @var $this Dwd_Stationen_Block_Catalog_Product_View_Abstract */

if ($this->hasStationen()) {
    $data = array(
        "type" => "FeatureCollection",
        "crs" => array(
            "type" => "name",
            "properties" => array(
                  "name" => "EPSG:4326"
            )
        )
    );

    $features = array();
    foreach($this->getStationsList() as $station) {
        $features[] = array(
            "type" => "Feature",
            "properties" => array(
                "id" => intval($station->getId()),
                "name" => $station->getName()
            ),
            "geometry" => array(
                "type" => "Point",
                "coordinates" => array(
                    floatval($station->getLon()),
                    floatval($station->getLat())
                )
            )
        );
    }
    $data["features"] = $features;
    echo json_encode($data);
}
?>