<?php if ($this->hasStationen()):?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/map-functions-suggest.js'); ?>"></script>
<script type="text/javascript">
var stationen = [
    <?php foreach($this->getStationsList() as $station) { ?>
    {id: <?php echo $station->getId()?>, name: "<?php echo $station->getName()?>"},
    <?php } ?>
];
</script>
<div id="suggest">
  <input id="quicksearch" type="text" class="input-text" name="quicksuggest" value="" autocomplete="off" />
  <div id="quick_autocomplete" class="search-autocomplete" style="display:none;"></div>

  <script type="text/javascript">
  //<![CDATA[
      var searchForm = new Quick.searchForm('quicksearch', '');
      //searchForm.initAutocomplete('<?php echo $this->getSuggestUrl();?>', 'quick_autocomplete');
  //]]>
  </script>
</div>
<?php endif;?>