<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="page-title">
    <h1><?php echo Mage::helper('gka_reports')->__('Transactions'). " " . $this->getCustomer(); ?></h1>
</div>

<div id="journal-block">
    <?php echo $this->getChildHtml("transaction_grid") ?>
    <!--
    <div class="buttons-set">
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Print Table')) ?>" class="button" onclick="window.print();">
            <span><?php echo $this->__('Print Table') ?></span>
        </button>
    </div>
    -->
</div>
