<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2018 B3-IT Systeme GmbH
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
$_item  = $this->getItem();
$_order = $this->getItem()->getOrder();

$_product = Mage::getModel('catalog/product')->load($_item->getProductId());

$_showThumbnail = Mage::getStoreConfig('sales_email/invoice_additional/show_thumbnail_in_email');
$_sizeThumbnail = Mage::getStoreConfig('sales_email/invoice_additional/thumbnail_dimension');
$_showLong      = Mage::getStoreConfig('sales_email/invoice_additional/show_description_in_invoice');
$_showShort     = Mage::getStoreConfig('sales_email/invoice_additional/show_short_description_in_invoice');
$_showDelivery  = Mage::getStoreConfig('sales_email/invoice_additional/show_delivery_time_in_invoice');

$_cellStyle = 'font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;';
?>
<tr>
    <td align="left" valign="top" style="<?php echo $_cellStyle; ?>">
        <?php if($_showThumbnail): ?>
          <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_sizeThumbnail); ?>"
               alt="<?php echo $this->escapeHtml($_item->getName()) ?>"
               title="<?php echo $this->escapeHtml($_item->getName()) ?>" />
        <?php endif; ?>
        <div><strong style="font-size:11px;"><?php echo $this->escapeHtml($_item->getName()) ?></strong></div>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?php echo nl2br($option['value']) ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php if ($_showDelivery): ?>
            <div class="default-delivery">
                <?php echo $this->__('Delivery Time'); ?>: <?php echo $this->escapeHtml($_product->getDeliveryTime()); ?>
            </div>
        <?php endif; ?>
        <?php if($_showLong): ?>
            <div class="default-long">
                <?php echo $this->escapeHtml($_product->getDescription()); ?>
            </div>
        <?php endif; ?>
        <?php if($_showShort): ?>
          <div class="default-short">
              <?php echo $this->escapeHtml($_product->getShortDescription()); ?>
          </div>
        <?php endif; ?>
    </td>
    <td align="left" valign="top" style="<?php echo $_cellStyle; ?>"><?php echo $this->escapeHtml($this->getSku($_item)) ?></td>
    <td align="center" valign="top" style="<?php echo $_cellStyle; ?>"><?php echo $_item->getQty()*1 ?></td>
    <td align="right" valign="top" style="<?php echo $_cellStyle; ?>">
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                    <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                <?php else: ?>
                    <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>
