<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2017 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<table class="table-totals" style="border:0; float:right;">
    <tr>
        <td class="padding-totals">
            <table style="border:0;">
                <?php echo $this->getChildHtml(); ?>
            </table>
        </td>
    </tr>
</table>
