<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
$_product = $this->getProduct();
?>

<?php if ($this->canEmailToFriend()): ?>
<ul class="sharing-links">
    <li id="send-friend">
        <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="link-email-friend" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email to a Friend')) ?>">
            <?php echo $this->__('Email to a Friend') ?>
        </a>
    </li>
</ul>
<?php endif; ?>

