<?php
/**
 * @category    design
 * @package     bfr_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="widget widget-new-products">
    <div class="widget-title">
        <h2><?php echo $this->__('New Products') ?></h2>
    </div>
    <div class="widget-products">
        <?php echo $this->getPagerHtml() ?>
        <?php $_params = $this->escapeHtml(json_encode(array('form_key' => $this->getFormKey()))); ?>
        <ol class="products-list">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
            <?php
                $_helper  = $this->helper('catalog/output');
                $_isorder = $_helper->productAttribute($_product, $_product->getShowOrderability(), 'show_orderability');
                if ( is_null($_isorder) ) {
                    $_isorder = true;
                }
            ?>
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                <div class="product-list-left-col">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(500) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                        <span class="image-copyright-box"><span><?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?></span></span>
                    </a>
                    <div class="product-add-links">
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <?php $_wishlistUrl = $this->getAddToWishlistUrlCustom($_product, false); ?>
                                <li>
                                    <a href="#"
                                       data-url="<?php echo $_wishlistUrl ?>"
                                       data-params="<?php echo $_params ?>"
                                       class="link-wishlist"
                                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Wishlist')) ?>"
                                       onclick="customFormSubmit('<?php echo $_wishlistUrl ?>', '<?php echo $_params ?>', 'post')">
                                        <?php echo $this->__('Add to Wishlist') ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)): ?>
                                <li>
                                    <span class="separator">|</span>
                                    <a href="#"
                                       class="link-compare"
                                       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Compare')) ?>"
                                       onclick="customFormSubmit('<?php echo $_compareUrl ?>', '<?php echo $_params ?>', 'post')">
                                        <?php echo $this->__('Add to Compare') ?>
                                    </a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
                <div class="product-shop">
                    <h2 class="product-name">
                        <?php $_productPrefix = $_product->getNamePrefix(); ?>
                        <?php if (strlen($_productPrefix)) : ?><span class="name-prefix"><?php echo $_productPrefix ?></span><?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)">
                            <?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?>
                        </a>
                    </h2>
                    <div class="product_sku">
                        <?php
                        $_sku = $_sku_full = $this->escapeHtml($_product->getSku());

                        if ( strlen($_sku) > 24 ) {
                            $_sku = substr($_sku, 0, 24) . '...';
                        }
                        echo $this->__('Sku').': <span title="'.$_sku_full.'">'.$_sku.'</span>';
                        ?>
                    </div>
                    <div class="desc std">
                        <?php
                        $_short_description = $this->helper('catalog/output')->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                        echo "<div class=\"full\">$_short_description<div class=\"shorter\"></div></div>\n";

                        if ( strlen($_short_description) > 1000 ) {
                            $_short_description = substr($_short_description, 0, 1000) . '...';
                        }
                        echo "<div class=\"short\">$_short_description<div class=\"shorter\"></div></div>\n";
                        ?>
                    </div>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
                    <?php if( $_isorder ): ?>
                        <div class="product-action">
                          <?php if (!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <button type="button"
                                    title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                    class="button btn-cart egov-cart"
                                    onclick="customFormSubmit(
                                            '<?php echo $this->getAddToCartUrlCustom($_product, array(), false) ?>',
                                            '<?php echo $_params ?>',
                                            'post')">
                                <span><?php echo $this->__('Add to Cart') ?></span>
                            </button>
                          <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>"
                               class="button egov-view"
                               href="<?php echo $_product->getProductUrl() ?>">
                                <span><?php echo $this->__('View Details') ?></span>
                            </a>
                          <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                          <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
