<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */


$_priceDisplay = ($this->helper('tax')->displayCartBothPrices()) ? 'display-both-prices' : 'display-single-price';
$mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1);
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?>
        <span class="spacer"> | </span>
        <a href="<?php echo $this->getUrl('sales/order/history') ?>"
           class="egov-view-all"
           title="<?php echo $this->__('View All') ?>"> </a>
        <?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table orders" id="my-orders-table">
        <colgroup>
            <col class="my-orders-suk" width="80" />
            <col class="my-orders-date" width="60" />
            <col class="my-orders-shipping" />
            <col class="my-orders-price" width="80" />
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <col class="my-orders-price" width="80" />
            <?php endif; ?>
            <col class="my-orders-status" width="1" />
            <col class="my-orders-options" width="10" />
        </colgroup>
        <thead>
            <tr>
                <th rowspan="<?php echo $mergedCells; ?>" class="space number"><?php echo $this->__('Order #') ?></th>
                <th rowspan="<?php echo $mergedCells; ?>" class="space date"><?php echo $this->__('Date') ?></th>
                <th rowspan="<?php echo $mergedCells; ?>" class="space ship"><?php echo $this->__('Ship To') ?></th>
                <th class="a-center cart-total-head" colspan="<?php echo $mergedCells; ?>">
                    <?php echo $this->__('Order Total') ?>
                    <?php if( Mage::getStoreConfig('tax/cart_display/price') == 1 ): ?>
                        <?php echo $this->__('(Excl. Tax)'); ?>
                    <?php elseif( Mage::getStoreConfig('tax/cart_display/price') == 2 ): ?>
                        <?php echo $this->__('(Incl. Tax)'); ?>
                    <?php endif; ?>
                </th>
                <th rowspan="<?php echo $mergedCells; ?>" class="space status"><?php echo $this->__('Status') ?></th>
                <th rowspan="<?php echo $mergedCells; ?>" class="space view">&nbsp;</th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th class="a-center cart-total-head"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
            <?php endif; ?>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
            <?php /** @var $_order \Mage_Sales_Model_Order */ ?>
                <tr>
                    <td class="number"><?php echo $_order->getRealOrderId() ?></td>
                    <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <td class="total"><?php echo $_order->formatPrice($_order->getSubtotal()) ?></td>
                    <?php endif; ?>
                    <td class="total">
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <?php if( Mage::getStoreConfig('tax/cart_display/price') == 1 ): ?>
                                <?php echo $_order->formatPrice($_order->getSubtotal()) ?>
                            <?php elseif( Mage::getStoreConfig('tax/cart_display/price') == 2 ): ?>
                                <?php echo $_order->formatPrice($_order->getGrandTotal()) ?>
                            <?php else: ?>
                                <?php echo $_order->formatPrice($_order->getGrandTotal()) ?>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php echo $_order->formatPrice($_order->getGrandTotal()) ?>
                        <?php endif; ?>
                    </td>
                    <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center view">
                        <span class="nobr">
                        <a class="egov-view"
                           href="<?php echo $this->getViewUrl($_order) ?>"
                           title="<?php echo $this->__('View Order') ?>"> </a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <a href="<?php echo $this->getReorderUrl($_order) ?>"
                               class="link-reorder egov-reorder"
                               title="<?php echo $this->__('Reorder') ?>"> </a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
