<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2018 B3 IT Systeme GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * GrandTotal der Order enthält immer den Gesamtpreis inkl. MwSt.
 */

/**
 * Annahme: Falls tax/sales_display/full_summary false dann ist Shop MwSt befreit
 */
$_taxPostfix = Mage::getStoreConfigFlag('tax/sales_display/full_summary') ?
    $this->__('(Incl. Tax)') : $this->__('(Tax Free)');
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?>
        <span class="spacer"> | </span>
        <a href="<?php echo $this->getUrl('sales/order/history') ?>"
           class="egov-view-all"
           title="<?php echo $this->__('View All') ?>"> </a>
        <?php endif; ?>
    </div>
<?php if ($_orders->getSize()) : ?>
    <table class="data-table orders" id="my-orders-table">
        <colgroup>
            <col class="my-orders-suk" width="80" />
            <col class="my-orders-date" width="60" />
            <col class="my-orders-shipping" />
            <col class="my-orders-price" width="80" />
            <col class="my-orders-status" width="1" />
            <col class="my-orders-options" width="10" />
        </colgroup>
        <thead>
            <tr>
                <th class="space number"><?php echo $this->__('Order #') ?></th>
                <th class="space date"><?php echo $this->__('Date') ?></th>
                <th class="space ship"><?php echo $this->__('Ship To') ?></th>
                <th class="space total"><?php echo $this->__('Order Total') ?> <?php echo $_taxPostfix; ?></th>
                <th class="space status"><?php echo $this->__('Status') ?></th>
                <th class="space view">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <?php /** @var $_order \Mage_Sales_Model_Order */ ?>
                <tr>
                    <td class="number"><?php echo $_order->getRealOrderId() ?></td>
                    <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center view">
                        <span class="nobr">
                        <a class="egov-view"
                           href="<?php echo $this->getViewUrl($_order) ?>"
                           title="<?php echo $this->__('View Order') ?>"> </a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <a href="<?php echo $this->getReorderUrl($_order) ?>"
                               class="link-reorder egov-reorder"
                               title="<?php echo $this->__('Reorder') ?>"> </a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
