<div class="entry-edit">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">Toll Information</h4>
    <div class="form-buttons"></div>
</div>
    <div class="fieldset " id="mastertext_form">
    <div class="hor-scroll">
 
		<table>
			<thead>
			<tr>
				<th><?php echo $this->__('Fee')?></th>
				<th><?php echo $this->__('Discount')?></th>
				<th><?php echo $this->__('Percent')?></th>
				<th><?php echo $this->__('Remove')?></th>
			</tr>
			</thead>
			<tbody>
			
			</tbody>
		</table>
			<select>
			<?php foreach($this->getFeesSections() as  $block):?>
			<option value="<?php echo $block['value']?>"><?php echo $block['label']?></option>
			<?php endforeach;?>
			</select>
			
			<button class="scalable" onclick="" type="button" title="<?php echo Mage::helper('bkg_license')->__('New')?>">
            <?php echo Mage::helper('bkg_license')->__('Add')?>
            </div>
        </div>
</div>

