        <div class="col2-set">
			<div class="col-1">
                <div class="page-title">
                    <h2>
                        <span class="required">*</span>
                        <?php echo $this->__('Singular amount'); ?>
                    </h2>
                </div>
	            <div class="input-box">
   	            	<input type="text" name="givenamount" id="givenamount" value="" class="input-text validate-price validate-givenamount required-entry" style="width:90%;" />
    	            <h2><?php echo $this->__('Change') ?>: <span id="balance"></span></h2>
    	        </div>
    	        <script type="text/javascript">
    	        	var price = '<?php echo $this->getTotal(); ?>';
        	        var currency = '<?php echo $this->getCurrencySymbol(); ?>';

                    $j(document).ready(function(){
                    	// Kassenbuch-Journal
                    	$j('#withdrawal').on('keyup change', function(event) {
                    		setDiffPrice($j('#withdrawal').val(), $j('#endsaldo').val(),  '#balance', true);
                    	});

                    	// Checkout => Bestellübersicht
                    	$j('#givenamount').on('keyup input', function(event) {
                    		setDiffPrice(price, $j('#givenamount').val(), '#balance', true);
                    	});
                    });
    	        </script>
	        </div>
	    </div>
