        <div class="col2-set">
			<div class="col-1">
                <h4>
                    <span class="required">*</span>
                    <?php echo $this->__('Singular amount'); ?>
                </h4>
	            <div class="input-box">
   	            	<input type="text" name="givenamount" id="givenamount" value="" class="input-text validate-price validate-givenamount required-entry" style="width:90%;" />
    	            <h2><?php echo $this->__('Change') ?>: <span id="balance"></span></h2>
    	        </div>
    	        <script type="text/javascript">
    	        	var price = '<?php echo $this->getTotal(); ?>';
        	        var currency = '<?php echo $this->getCurrencySymbol(); ?>';

        	        $j(document).ready(function(){
        	        	// Kassenbuch-Journal
        	        	$j('#withdrawal').bind('keyup', function() {
        	        		var v = $j('#endsaldo').val();
            	        	v = v.replace(/,/g , ".");
        	        		setDiffPrice($j('#withdrawal').val(),v,  '#balance', true);
        	        	});

        	        	// Checkout => Bestellübersicht
        	        	$j('#givenamount').bind('keyup', function() {
            	        	var v = $j('#givenamount').val();
            	        	v = v.replace(/,/g , ".");
        	        		setDiffPrice(price, v, '#balance', true);
        	        	});
        	        });
    	        </script>
	        </div>
	    </div>
