<?php
/**
 * @category   gka_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
	<h2>
		<?php echo $this->__('Review Order') ?>
	</h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
	<?php echo $this->getBlockHtml('formkey'); ?>
	
<div class="col2-set">
	<div class="col-1">
		<?php echo $this->getChildHtml('singlepage_payment') ?>
	</div>
	<div class="col-2">
	<?php if(!$this->isVirtual()):?>
		<?php //echo $this->getChildHtml('singlepage_shipping') ?>
	<?php endif;?>
	</div>
</div>

<div id="address">
	<?php echo $this->getChildHtml('singlepage_billing') ?>
</div>	
	
<fieldset>
	<ul class="form-list group-select">
		<li>
			<input type="hidden" name="sendOrderEmail" id="sendOrderEmail" value="1"/>
		</li>
	</ul>

	<div>
		<?php echo $this->getChildHtml('infotexts'); ?>
		<?php echo $this->getChildHtml('agreementtexts'); ?>

		<?php echo $this->getChildHtml('agreements') ?>
	</div>
</fieldset>
	<fieldset class="multiple-checkout">
		<?php $_address=$this->getBaseAddress() ?>
		<?php if (Mage::helper('core')->isModuleEnabled('Egovs_GermanTax') && $_address):?>
			<div class="col2-set">
				<h3>
					<?php echo $this->__('Tax Information') ?>
				</h3>
				<div class="col-1">	
					<h4>
						<?php echo $this->__('Base Address') ?>
					</h4>
					<address>
						<?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
					</address>
				</div>
			</div>
		<?php endif;?>
		
	<div id='cashpayment'> </div> 	

		<div class="col1-wide">

			<table class="data-table" id="checkout-review-table">
				<?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
				<col />
				<col width="80" />
				<col width="80" />
				<col width="10" />
				<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
				<col width="80" />
				<col width="80" />
				<?php endif; ?>
				<thead>
					<tr>
						<th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
						<th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
						<th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Qty') ?></th>
						<th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
					</tr>
					<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
					<tr>
						<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
						</th>
						<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
						<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?>
						</th>
						<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
					</tr>
					<?php endif; ?>
				</thead>

				<tbody>
					<?php foreach($this->getItems() as $_item): ?>
					<?php echo $this->getItemHtml($_item)?>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
		<p class="grand-total">
			<span style="font-weight: bold;"><?php echo $this->__('Grand Total:') ?> </span>
			<?php echo $this->helper('checkout')->formatPrice($this->getTotal()) ?>
		</p>
		<div class="buttons-set" id="review-buttons-container">
			
			<a class="button" href="<?php echo $this->getUrl() ?>">
			    <span><?php echo $this->__('Continue Shopping') ?></span>
			</a>
			<button type="submit" class="button" id="review-button">
				<span><?php echo $this->__('Buy for %s', $this->helper('checkout')->getQuote()->getStore()->formatPrice($this->getTotal(), false)) ?> </span>
			</button>
		</div>
    	<span id="review-please-wait" class="please-wait" style="display: none;">
    	    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
			     alt="<?php echo $this->__('Please Wait') ?>"
			     class="v-middle" />
			<?php echo $this->__('Submitting order information...') ?>
		</span>
	</fieldset>
</form>

<script type="text/javascript">
if(Validation) {
	Validation.addAllThese([
    	['validate-givenamount', '<?php echo $this->__('Change Amount not plausible!'); ?>', function(v) {
    		v = parseFloat(v.replace(/,/g , "."));
        	return v >= price ? true : false;
        }],
        ['validate-price', '<?php echo $this->__('Please enter a valid price in this field.'); ?>', function(v) {
            v = v.replace(/,/g , ".");
            return Validation.get('IsEmpty').test(v) || (!isNaN(parseNumber(v)) && !/^\s+$/.test(parseNumber(v)));
        }]
    ]);
}
var dataForm = new VarienForm('form-validate', true);
</script>
