<?php echo $this->getMessagesBlock()->toHtml() ?>
<form  method="POST" action="<?php echo $this->getPostUrl();?>">
<div class="col2-set">
	<div class="col-1">
		<?php echo $this->getChildHtml('singlepage_billing') ?>
	</div>
	<div class="col-2">
		<?php //echo $this->getChildHtml('singlepage_payment') ?>
	</div>
</div>
<div class="buttons-set">
    <a class="button" href="<?php echo $this->getCardUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Card') ?></a>
    <button id="payment-continue" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Buy Now')) ?>" class="button">
        <span><?php echo $this->__('Buy Now') ?></span>
    </button>
</div>
</form>