<?php echo $this->getMessagesBlock()->toHtml() ?>
<form  method="POST" action="<?php echo $this->getPostUrl();?>">
<div style="float: left">
	<?php echo $this->getChildHtml('singlepage_billing') ?>
</div>
<div>
	<?php echo $this->getChildHtml('singlepage_payment') ?>
</div>
        
        <div class="buttons-set">
            <a class="button" href="<?php echo $this->getCardUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Card') ?></a></p>
            <button id="payment-continue" type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Buy Now')) ?>" class="button"><span><span><?php echo $this->__('Buy Now') ?></span></span></button>
        </div>
</form>