<?php /** @var B3it_Solr_Block_Facet $this */ ?>

<?php if(!empty($this->getFacetNames())): ?>
<div class="solr-facet">

    <h3><?php echo $this->__('Filter Results'); ?></h3>

    <form id="solr_search_facet_form" action="" method="get">
        <fieldset>
            <?php foreach ($this->getFacetNames() as $facet =>$label) :?>
            <div id="<?php echo $facet ?>" class="solr-facet-groupbox" data-type="accordion">
                <h3>
                    <?php echo $this->__($label); ?>
                </h3>
                <div>
                    <?php if($this->getFacetExtended($facet) == 0) :?>
                        <?php if($this->getFacetBox($facet) == 0) : ?>
                            <div class="solr-facet-input"><input type="radio" name="<?php echo $facet ?>" value="*" checked="checked"><span><?php echo $this->__('All'); ?></span></div>
                        <?php endif; ?>
                        <?php foreach($this->getFacetValues($facet) as $value) :?>
                            <?php if($this->getFacetBox($facet) == 1) : ?>
                                <div class="solr-facet-input"><input type="checkbox" name="<?php echo $facet ?>" value="<?php echo $value['name'] ?>"><span><?php echo $value['name'] ?></span></div>
                            <?php endif; ?>
                            <?php if($this->getFacetBox($facet) == 0) : ?>
                                <div class="solr-facet-input"><input type="radio" name="<?php echo $facet ?>" value="<?php echo $value['name'] ?>"><span><?php echo $value['name'] ?></span></div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php if($this->getFacetExtended($facet) == 1) :?>
                        <?php if($this->getFacetBox($facet) == 0) : ?>
                            <div class="solr-facet-input"><input type="radio" name="<?php echo $facet ?>" value="*" checked="checked"><span><?php echo $this->__('All'); ?></span></div>
                        <?php endif; ?>
                        <?php foreach($this->getFacetPriceRange($facet) as $value) :?>
                            <?php if($this->getFacetBox($facet) == 1) : ?>
                                <div class="solr-facet-input"><input type="checkbox" name="<?php echo $facet ?>" value="<?php echo '['.$value['min'].' TO '.$value['max'].']'; ?>"><span><?php echo $value['min'].$this->getSymbol().' - '.$value['max'].$this->getSymbol() ?></span></div>
                            <?php endif; ?>
                            <?php if($this->getFacetBox($facet) == 0) : ?>
                                <div class="solr-facet-input"><input type="radio" name="<?php echo $facet ?>" value="<?php echo '['.$value['min'].' TO '.$value['max'].']'; ?>"><span><?php echo $value['min'].$this->getSymbol().' - '.$value['max'].$this->getSymbol() ?></span></div>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </fieldset>
    </form>
</div>
<?php endif; ?>
<script src="<?php echo Mage::getBaseUrl('js', array("_secure", $this->_isSecure())).'b3it/solr/facet.js'?>" ></script>

<script type="text/javascript">
    $j( document ).ready(function() {
        $j('#solr_search_facet_form').solrFacet({
            "ajaxUrl":  "<?php echo Mage::helper('b3it_solr')->getFacetUrl() ?>",
            "resultId": "solr-result-set"
        });
    });
</script>
