<?php
/** @var Mage_Core_Block_Template $this */
$_showMiniSearch = true;
$_configSetting  = Mage::getStoreConfig('design/header/enable_ajax_search', Mage::app()->getStore());
$_isCustomer     = Mage::helper('customer')->isLoggedIn();

if ( $_configSetting >= 1 ) {
    if ( $_configSetting == 1 ) {
        $_showMiniSearch = false;
    }
    else {
        if ( !$_isCustomer ) {
            $_showMiniSearch = false;
        }
    }
}
?>
<?php if ( $_showMiniSearch ): ?>
    <form id="solr-form" class="solr-search-form" action="<?= $this->helper('b3it_solr')->getResultUrl() ?>" method="get">
        <fieldset class="solr-search-fieldset">

            <label for="search"><?= $this->__('Search:') ?></label>
            <input id="search"
                   type="text"
                   class="input-text"
                   tabindex="1"
                   name="<?= $this->helper('b3it_solr')->getQueryParamName() ?>"
                   title="<?= $this->__('Enter the search term here.'); ?>"
                   placeholder="<?= $this->__('Search term'); ?>"
                   value="<?= $this->helper('b3it_solr')->getEscapedQueryText() ?>"
                   required
                   pattern=".{2,}"
            />
            <button type="submit" class="button"><span><?= $this->__('Search ') ?></span></button>

            <script src="<?= Mage::getBaseUrl('js', array("_secure", $this->_isSecure())).'b3it/solr/suggestion_plugin.js'?>" ></script>

            <script type="text/javascript">
                $j( document ).ready(function() {
                    $j('#search').solrSearch({
                        "ajaxUrl": "<?= Mage::helper('b3it_solr')->getSuggestUrl() ?>",
                        "formID": "solr-form",
                    });
                });
            </script>

        </fieldset>
    </form>
<?php endif; ?>
