<?php
/**
* @category    design
* @package     gka_default
* @copyright   Copyright (c) 2018 B3-it System GmbH (https://www.b3-it.de)
* @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <input type="hidden" name="qty" id="qty" value="1" />
        <button type="button"
                title="<?php echo $this->__('Add to Cart'); ?>"
                id="product-addtocart-button"
                class="button btn-cart"
                onclick="productAddToCartForm.submit(this)">
            <span><?php echo $this->__('Add to Cart'); ?></span>
        </button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
