<?php
/**
* @category    design
* @package     gka_default
* @copyright   Copyright (c) 2018 B3-it System GmbH (https://www.b3-it.de)
* @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if($_product->getCanChangeQty()):?>
            <div class="qty-wrapper">
                <label for="qty"><?php echo $this->__('Qty:') ?></label>
                <input type="text" pattern="\d*"
                       onchange="showTotal()"
                       name="qty"
                       id="qty" maxlength="12" value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
            </div>
        <?php else: ?>
            <input type="hidden" name="qty" id="qty" value="1" />
        <?php endif; ?>
        <button type="button"
                title="<?php echo $this->__('Add to Cart'); ?>"
                id="product-addtocart-button"
                class="button btn-cart"
                onclick="productAddToCartForm.submit(this)">
            <span><?php echo $this->__('Add to Cart'); ?></span>
        </button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
