<?php
/**
 * @category    design
 * @package     gka_default
 * @copyright   Copyright (c) 2018 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct();
$pre = $_product->getPreconfiguredValues();
$price = 0;
if($pre) {
	$price = floatval($pre->getFelxprice());
}
?>

<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>

<div id="flexprice-block">
	<label for="amount">
        <?php echo $this->__('Amount'); ?>
        <?php if(!$_product->getAllowPriceZero()):?><span class="required">*</span><?php endif;?>
    </label>
	<input type="text"
           name="amount"
           id="amount"
           onchange="showTotal()"
           value="<?php if($price > 0): echo $price; endif; ?>"
           placeholder="<?php echo $this->__('Please insert an valid Amount.'); ?>"
           <?php if(!$_product->getAllowPriceZero()):?>class="input-text required-entry"<?php else: ?>class="input-text"<?php endif; ?> />
</div>
<?php if(!$_product->getAllowPriceZero()): ?>
<script type="text/javascript">
if(Validation) {
    Validation.addAllThese([
        ['validate-amount', '<?php echo $this->__('The amount must be greather than 0') ?>', function(v) {
            return parseFloat(v) > 0;
        }]
    ]);
}

    function showTotal()
    {
        var p =  $j('#amount').val();
        p = p.replace(',','.');
        p = parseFloat(p);
        p = p *  parseFloat($j('#qty').val());
        p ='<span class="price">'+p.toFixed(2)+'&nbsp;€</span>';
        var box = $j('#product-price-<?php echo $_product->getId() ?>');
        box.html(p);
    }

</script>
<?php endif; ?>

