<?php

/**
 * Magento
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @category   Mage
* @package    Mage_BankPayment
* @copyright  Copyright (c) 2008 Andrej Sinicyn
* @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

?>
<?php echo $this->getPaymentInfoHtml(); ?>
<div class="block-footer">
    <?php echo $this->__("<a target='_blank' href='%s'>Here</a> you can read details to the payment method!", $this->getUrl('zahlung')); ?>
</div>
