SET foreign_key_checks = 0;
drop table IF EXISTS bkg_license_copy;
drop table IF EXISTS bkg_license_copy_address;
drop table IF EXISTS bkg_license_copy_agreement;
drop table IF EXISTS bkg_license_copy_customergroup;
drop table IF EXISTS bkg_license_copy_fee;
drop table IF EXISTS bkg_license_copy_file;
drop table IF EXISTS bkg_license_copy_product;
drop table IF EXISTS bkg_license_copy_toll;
drop table IF EXISTS bkg_license_copy_useoption;
drop table IF EXISTS bkg_license_master;
drop table IF EXISTS bkg_license_master_agreement;
drop table IF EXISTS bkg_license_master_customergroup;
drop table IF EXISTS bkg_license_master_fee;
drop table IF EXISTS bkg_license_master_product;
drop table IF EXISTS bkg_license_master_toll;
drop table IF EXISTS bkg_license_master_useoption;
SET foreign_key_checks = 1;
DELETE FROM core_resource WHERE code = 'bkg_license_setup';
DELETE FROM pdftemplate_template WHERE type = 'license_copy';