<?php
 /**
  *
  * @category   	Bkg
  * @package    	Bkg_VirtualGeo
  * @name       	Bkg_VirtualGeo_Model_Resource_Components_Formatentity
  * @author 		Holger Kögel <h.koegel@b3-it.de>
  * @copyright  	Copyright (c) 2017 B3 It Systeme GmbH - http://www.b3-it.de
  * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
  */
class Bkg_VirtualGeo_Model_Resource_Components_Contentproduct extends Bkg_VirtualGeo_Model_Resource_Components_Componentproduct
{
    public function _construct()
    {
        // Note that the id refers to the key field in your database table.
        $this->_init('virtualgeo/components_content_product', 'id');
    }

    protected function _afterSave(Mage_Core_Model_Abstract $object) {
        $this->_saveAdditional($object);
        return parent::_afterSave($object); // TODO: Change the autogenerated stub
    }

    protected function _getContentOptionValueTable() {
        return $this->getTable('virtualgeo/components_content_option_value');
    }

    protected function _saveAdditional($object)
    {
        if ($object->getId()) {
            $condition = $this->_getWriteAdapter()->prepareSqlCondition('id', intval($object->getId()));
            $this->_getWriteAdapter()->update($this->_getContentOptionValueTable(), $object->getData(), $condition);
        } else {
            $this->_getWriteAdapter()->insert($this->_getContentOptionValueTable(), $this->_prepareContentOptionDataForSave($object));
        }
    }

    protected function _prepareContentOptionDataForSave($object)
    {
        return $this->_prepareDataForTable($object, $this->_getContentOptionValueTable());
    }

    protected function _loadAdditional($object)
    {
        $table = $this->_getContentOptionValueTable();

        $read = $this->_getReadAdapter();
        if ($read) {
            $condition = $read->prepareSqlCondition('id', $object->getId());
            $select = "SELECT * FROM {$table} {$condition}";
            $data = $read->fetchRow($select);

            if ($data) {
                $object->setData($data);
            }
        }

        return $this;
    }

    protected function _afterLoad(Mage_Core_Model_Abstract $object) {
        parent::_afterLoad($object);

        return $this->_loadAdditional($object);
    }
}
