<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2018 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /* @var $this Mage_Core_Block_Captcha_Zend */ ?>

<?php /* @var $captcha Mage_Core_Model_Captcha_Zend */ ?>
<?php $captcha = $this->getCaptchaModel() ?>
        <li class="fields captcha-img-container">
            <div class="captcha-image" id="captcha-image-box-<?php echo $this->getFormId()?>">
                <img id="<?php echo $this->getFormId() ?>" class="captcha-img" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>"/>
                <?php if ($captcha->isCaseSensitive()) :?>
                    <div class="captcha-note">
                        <?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
                    </div>
                <?php endif; ?>
            </div>
            <script type="text/javascript">//<![CDATA[
                $('<?php echo $this->getFormId() ?>').captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');
                //]]></script>
        </li>
    </ul>
</div>
<div class="fieldset half-space">
    <ul class="form-list">
        <li class="fields captcha-input-container" id="captcha-input-box-<?php echo $this->getFormId()?>">
            <label for="captcha_<?php echo $this->getFormId() ?>" class="required"><em>*</em><?php echo $this->__('Please type the letters below')?></label>
            <div class="input-box captcha">
                <input name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" type="text" class="input-text required-entry" id="captcha_<?php echo $this->getFormId() ?>" />
            </div>
        </li>
    </ul>
</div>
<div class="fieldset half-space">
    <ul class="form-list">
        <li class="fields captcha-image-reload-info">
            <img id="captcha-reload" class="captcha-reload" src="<?php echo $this->getSkinUrl('images/reload.png') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Reload captcha')) ?>" onclick="$('<?php echo $this->getFormId()?>').captcha.refresh(this)">
            <?php echo $this->__('If the code is not readable, please click on the button'); ?>
        </li>
