<?php
/**
 *
  *-- TODO:: kurze Beschreibung --
  *
  *
  *
  * @category        	Egovs_Ready_Block_Catalog_Product_Price
  * @package			package_name
  * @name            	Egovs_Ready_Block_Catalog_Product_Price
  * @author 			Frank Rochlitzer <f.rochlitzer@b3-it.de>
  * @copyright      	Copyright (c) 2010 - 2015 B3 IT Systeme GmbH - http://www.b3-it.de
  * @license        	http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
  *
 */
?>
<?php
/** 
 * @var $this Mage_Core_Block_Template
 * @see Egovs_Ready_Block_Catalog_Product_Price
 */
?>
<?php $shippingCostUrl = Mage::helper( 'egovsready' )->getShippingCostUrl() ?>
<?php if( $this->getFormattedTaxRate() > 0 ): ?>
    <?php if( !empty( $shippingCostUrl ) && $this->getShowShippingLink() ): ?>
        <?php if( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_EXCLUDING_TAX ): ?>
            <?php if( $this->getIsIncludingShippingCosts() ): ?>
                <span class="tax-details"><?php echo $this->__( 'Excl. %s Tax', $this->getFormattedTaxRate() ) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo $this->__( 'incl. <a href="%s">Shipping Cost</a>', $shippingCostUrl ) ?></span></span>
            <?php else: ?>
                <span class="tax-details"><?php echo $this->__( 'Excl. %s Tax', $this->getFormattedTaxRate() ) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo $this->__( 'excl. <a href="%s">Shipping Cost</a>', $shippingCostUrl ) ?></span></span>
            <?php endif ?>
        <?php elseif( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_INCLUDING_TAX ): ?>
            <?php if( $this->getIsIncludingShippingCosts() ): ?>
                <span class="tax-details"><?php echo $this->__( 'Incl. %s Tax', $this->getFormattedTaxRate() ) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo $this->__( 'incl. <a href="%s">Shipping Cost</a>', $shippingCostUrl ) ?></span></span>
            <?php else: ?>
                <span class="tax-details"><?php echo $this->__( 'Incl. %s Tax', $this->getFormattedTaxRate() ) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo $this->__( 'excl. <a href="%s">Shipping Cost</a>', $shippingCostUrl ) ?></span></span>
            <?php endif ?>
        <?php elseif( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_BOTH ): ?>
            <?php if( $this->getIsIncludingShippingCosts() ): ?>
                <span class="tax-details"><?php echo $this->__('incl. <a href="%s">Shipping Cost</a>', $shippingCostUrl) ?></span>
            <?php else: ?>
                <span class="tax-details"><?php echo $this->__('excl. <a href="%s">Shipping Cost</a>', $shippingCostUrl) ?></span>
            <?php endif ?>
        <?php endif ?>
        <?php if ($this->getDisplayProductWeight()): ?>
            	<br/> (<?php echo $this->__('Shipping Weight %s', $this->getFormattedWeight()) ?>)
        <?php endif ?>
    <?php else: ?>
        <?php if( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_EXCLUDING_TAX ): ?>
            <span class="tax-details"><?php echo $this->__( 'Excl. %s Tax', $this->getFormattedTaxRate() ) ?></span>
        <?php elseif( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_INCLUDING_TAX ): ?>
            <span class="tax-details"><?php echo $this->__( 'Incl. %s Tax', $this->getFormattedTaxRate() ) ?></span>
     <?php elseif( $this->getPriceDisplayType() == Mage_Tax_Model_Config::DISPLAY_TYPE_BOTH ): ?>
            <span class="tax-details"><?php echo $this->__( 'Incl. %s Tax', $this->getFormattedTaxRate() ) ?></span>
        <?php endif ?>
    <?php endif ?>
<?php endif ?>