<?php $_element =  $this->getElement();?>
<?php $_itemID = $_element->getId(); ?>

<script type="text/javascript" src="<?php echo $this->getJsUrl('egovs/table-assign.js'); ?>"></script>
<script>
var assign_<?php echo $_itemID?> = new assignTable('<?php echo $_itemID?>','<?php echo  $_element->getName();?>');
</script>



<tr class='grid'>
	<td class="label">
		<?php echo $this->__($_element->getLabel())?>
	</td>
	<td class="value">
		<script type="text/javascript">
			var messageNoItemSelected = '<?php echo $this->__('At least one option must be selected.'); ?>';
			var templateDelButton = '<button class="scalable delete add-widget position-delete" type="button" title="<?php echo Mage::helper('bkg_license')->__('Remove')?>"><span></span></button>';
		</script>
		
		<table cellspacing="0" class="data" id="table-<?php echo $_itemID; ?>">
			<colgroup>
				<col />
				<col />
				<col style="width: 110px;" />
			</colgroup>
			<thead>
				<tr class="headings">
					<th><?php echo $this->__($_element->getLeftLabel())?></th>
					<th><?php echo $this->__($_element->getRightLabel())?></th>
					<th>&nbsp;</th>
				</tr>
				<tr class="massaction">
					<th>
						<select id='left-assign-<?php echo $_itemID?>' >
									<?php foreach($_element->getLeftValues() as $opt):?>
										<option value="<?php echo $opt['value']?>"><?php echo $opt['label']?></option>
									<?php endforeach;?>
								</select>
					</th>
					<th>
						<select  id='right-assign-<?php echo $_itemID?>' >
									<?php foreach($_element->getRightValues() as $opt):?>
										<option value="<?php echo $opt['value']?>"><?php echo $opt['label']?></option>
									<?php endforeach;?>
								</select>
					</th>
					<th><button class="scalable add" onclick="assign_<?php echo $_itemID?>.appendRow();" type="button" title="<?php echo Mage::helper('bkg_license')->__('Add')?>">
									<span>
										<?php echo Mage::helper('bkg_license')->__('Add')?>
									</span>
								</button>
					</th>
				</tr>
			</thead>
			<tbody >
			</tbody>
		</table>
		<script>
			<?php foreach($_element->getValue() as $value):?>
			assign_<?php echo $_itemID?>.appendRow(<?php echo $value?>);
			<?php endforeach;?>
		</script>
	</td>
</tr>
