<?php
/**
 * @category    design
 * @package     egov_adlerwarte
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <?php echo $this->getChildHtml('head') ?>
    </head>

    <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?> id="1-column">
        <?php echo $this->getChildHtml('after_body_start') ?>
        <div class="wrapper">
            <?php echo $this->getChildHtml('global_notices') ?>
            <div id="background-image"></div>
            <div class="page">
                <div id="top-wave" class="top-wave"></div>
                <?php echo $this->getChildHtml('header') ?>
                <div class="main-container col1-layout">
                    <div class="main">
                        <div class="col-left" style="display: none !important;">
                            <?php /* Das muß hier rein, da es im 1-Spaltigen-Layout keine Navigation o.Ä. gibt => Mobil wird unbedienbar! */ ?>
                            <?php echo $this->getChildHtml('left') ?>
                        </div>
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                        <div class="col-main">
                            <?php echo $this->getChildHtml('global_messages') ?>
                            <?php echo $this->getChildHtml('content') ?>
                            <?php echo $this->getChildHtml('footer_before') ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('global_cookie_notice') ?>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
        </div>
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
</html>
