<?php
/**
 * @category    design
 * @package     egov_adlerwarte
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <?php echo $this->getChildHtml('head') ?>
    </head>

    <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?> id="2-columns-left">
        <?php echo $this->getChildHtml('after_body_start') ?>
        <div class="wrapper">
            <div id="background-image"></div>
            <div class="page">
                <div id="top-wave" class="top-wave"></div>
                <?php echo $this->getChildHtml('header') ?>

                <?php echo $this->getChildHtml('global_notices') ?>

                <div class="main-container col2-left-layout">
                    <div class="main">
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                        <div class="col-wrapper">
                        <?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                            <div class="col-left sidebar col-left-first">
                                <?php echo $_leftContent;   ?>
                            </div>
                        <?php endif; ?>
                            <div class="col-left sidebar">
                                <?php echo $this->getChildHtml('left') ?>
                            </div>
                            <div class="col-main">
                                <?php echo $this->getChildHtml('global_messages') ?>
                                <?php echo $this->getChildHtml('content') ?>
                                <?php echo $this->getChildHtml('footer_before') ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('global_cookie_notice') ?>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
        </div>
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
</html>
