<?php
/**
 * @category    design
 * @package     dwd_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/** @var $this Mage_Customer_Block_Form_Login */
?>

<?php
$_allowedRegister = Mage::getStoreConfig('customer/create_account/register_user_on_login', $this->getStoreId());

$_use_ssl_logo  = Mage::getStoreConfig('design/login/ssl_logo_use', Mage::app()->getStore());
$_ssl_image     = Mage::getStoreConfig('design/login/ssl_logo', Mage::app()->getStore());
$_ssl_image_css = Mage::getStoreConfig('design/login/ssl_logo_style', Mage::app()->getStore());
$_ssl_alt       = $this->__( Mage::getStoreConfig('design/login/ssl_logo_alt', Mage::app()->getStore()) );
$_ssl_title     = $this->__( Mage::getStoreConfig('design/login/ssl_logo_title', Mage::app()->getStore()) );

$_is_https   = Mage::app()->getFrontController()->getRequest()->isSecure();
$_show_image = ( strlen($_ssl_image) ? Mage::getBaseUrl('media') . 'ssl_logo/' . $_ssl_image : $this->getSkinUrl('images/litessl_tl_trans.gif') );

$_show_ssl = false;
if ( ($_use_ssl_logo == 0) || ($_use_ssl_logo == 2 && $_is_https) ) {
    $_show_ssl = true;
}
$show_css = '';
if ( strlen($_ssl_image_css) && !empty($_ssl_image_css) ) {
    $show_css = ' style="' . $this->escapeHtml($_ssl_image_css) . '"';
}
?>

<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
        <div class="col2-set dwd-account-login">

            <div class="page-title">
                <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                        <?php echo $this->__('Login or Create an Account') ?>
                    <?php else: ?>
                        <?php echo $this->__('Login'); ?>
                    <?php endif; ?></h1>
            </div>

            <?php if ($_allowedRegister): ?>
            <div class="col-1 new-users">
                <form action="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>" method="get" id="register-form" class="scaffold-form">
                    <h2><?php echo $this->__('New Here?') ?></h2>
                    <div class="content">
                        <p><?php echo $this->__("By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.") ?></p>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send">
                            <?php echo $this->__('Create an Account') ?>
                        </button>
                    </div>
                </form>
            </div>
            <?php endif; ?>

            <?php // This column should be col-1 if the registration column is not displayed ?>
            <div class="<?php if ($this->helper('customer')->isRegistrationAllowed()): ?>col-2<?php else: ?>col-1<?php endif; ?> registered-users">
                <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
                    <?php echo $this->getBlockHtml('formkey'); ?>
                    <h2><?php echo $this->__('Already registered?') ?></h2>
                    <div class="content">
                        <p class="form-instructions">
                            <?php echo $this->__('If you have an account with us, please log in.') ?>
                        </p>

			            <div class="securityLabel">
			              <?php if( $_show_ssl ): ?>
				            <img src="<?php echo $_show_image; ?>" alt="<?php echo $this->__($_ssl_alt); ?>" title="<?php echo $this->__($_ssl_title); ?>" />
			              <?php endif; ?>
			            </div>
			            <fieldset<?php if( $_is_https != true ): ?> class="width"<?php endif; ?>>
                        <ul class="form-list">
                            <li>
                                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
                                </div>
                            </li>
                            <li>
                                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                <div class="input-box">
                                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <li>
                            </li>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        <p class="required">
                            <?php echo $this->__('* Required Fields') ?>
                        </p>
                        </fieldset>
                    </div>
                    <div class="buttons-set">
                        <a class="button" href="<?php echo $this->getForgotPasswordUrl() ?>">
                            <?php echo $this->__('Forgot Your Password?') ?>
                        </a>
                        <button type="submit" class="button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2">
                            <?php echo $this->__('Login') ?>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
