<script type="text/javascript">
//<![CDATA[

var hitEnter = false;

function addItem(id)
{
	new Ajax.Request('<?php echo $this->getItemsAddUrl();?>',
	  {
	    method:'post',
	    parameters: 'id='+id,
	    onSuccess: function(transport){
			$('contract_item_list').update(transport.responseText);
	    },
	    onFailure: function(){ alert('<?php echo $this->__('Something went wrong...')?>') }
	  });
}

function preventRemove(event)
{
	if(event.keyCode==13)
	{
		hitEnter = true;
	}
}

function changeItem(id,html_id)
{
	new Ajax.Request('<?php echo $this->getItemsChangeUrl();?>',
	  {
	    method:'post',
	    parameters: 'id='+id +'&qty='+$(html_id).value,
	    onSuccess: function(transport){
			$('contract_item_list').update(transport.responseText);
	    },
	    onFailure: function(){ alert('<?php echo $this->__('Something went wrong...')?>') }
	  });
}

function removeContractItem(id,event)
{
	//if(! hitEnter)
	if((event.clientX != 0) && (event.clientY != 0))
	{
		new Ajax.Request('<?php echo $this->getItemsRemoveUrl();?>',
			  {
			    method:'post',
			    parameters: 'id='+id,
			    onSuccess: function(transport){
					$('contract_item_list').update(transport.responseText);
			    },
			    onFailure: function(){ alert('<?php echo $this->__('Something went wrong...')?>') }
			  });
	}
	hitEnter = false;
}


//]]>
</script>



<form id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post">
  <?php echo $this->getBlockHtml('formkey')?>
	<div class="content-header" style="visibility: visible;">
		<table>
			<tbody>
				<tr>
				  <td style="width:50%;">
				    <h3 class="icon-head head-pickup"><?php echo $this->__('Creating Distribution Order')?></h3>
			    </td>
			    <td class="form-buttons"></td>
			  </tr>
			</tbody>
		</table>
	</div>
  <div id="product_selection">
      <?php echo $this->getChildHtml('product') ?>
  </div>
  <div class="entry-edit">
    <div class="entry-edit-head">
	    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Order Details')?></h4>
    </div>
    <fieldset>
      <div id="contract_customer">
  	    <?php echo $this->getChildHtml('customer') ?>
      </div>
      <div id="contract_item_list">
  	    <?php echo $this->getChildHtml('list') ?>
      </div>
	    <button type="button" style="" class="scalable save" onclick="$('edit_form').submit()" ><span><?php echo $this->__('Submit Order')?></span></button>
    </fieldset>
  </div>
</form>