<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Egovs
 * @package    Egovs_Openaccountpayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_credit_period"><?php echo Mage::helper('payment')->__('Credit Period Days') ?> 
            <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Credit Period') ?>" 
            	class="required-entry input-text validate-zero-or-greater validate-digits" 
            	id="<?php echo $_code ?>_credit_period" 
            	name="payment[paywithinxdays]" 
            	value="<?php echo $this->getInfoData('paywithinxdays') ?>"/>
        </div>
    </li>
</ul>
