<?php
/** Bfr_Eventparticipants_Block_Notification_Order $this */
?>

<?php if ($this->getValidHash()): ?>
    <div class="page-title">
        <h1><?= $this->__('Participationlist') ?></h1>
    </div>
    <div class="product-options">
        <form id="accept-participationslist-form" method="post" enctype="multipart/form-data" action="<?= $this->getAcceptUrl()?>">
            <input id="useless-participationslist-accept" type="checkbox" name="accept">
            <label for="useless-participationslist-accept"><?= $this->__('I accept the use of my personal data for a participation list.') ?></label>
            <button class="button" type="submit">
                <span>Akzeptieren</span>
            </button>
        </form>
    </div>
<?php else: ?>
    <div class="page-title">
        <h1><?= $this->__('Whoops, something went wrong...') ?></h1>
    </div>
    <span><?= $this->__('The requested url is not valid.') ?></span>
<?php endif; ?>
