<?php
/** Bfr_Eventparticipants_Block_Notification_Order $this */
?>

<?php if ($this->getValidHash()): ?>
    <div class="page-title">
        <h1><?php echo $this->__('Participationlist'); ?></h1>
    </div>
    <div class="product-options">
        <form id="accept-participationslist-form" method="post" action="<?php echo $this->getAcceptUrl(); ?>">
            <input id="useless-participationslist-accept" type="checkbox" name="accept">
            <label for="useless-participationslist-accept"><?php echo $this->__('I accept the use of my personal data for a participation list.'); ?></label>
            <div class="buttons-set">
                <button class="button" type="submit"><span><?php echo $this->__('Accept'); ?></span></button>
            </div>
        </form>
    </div>
<?php else: ?>
    <div class="page-title">
        <h1><?php echo $this->__('Whoops, something went wrong...') ?></h1>
    </div>
    <span><?php echo $this->__('The requested url is not valid.') ?></span>
<?php endif; ?>
