<script type="text/javascript">

if (!window.Quick)
    var Quick = new Object();

Quick.searchForm = Class.create();
Quick.searchForm.prototype = {
    initialize : function(form, field, emptyText){
        this.form   = $(form);
        this.field  = $(field);
        this.emptyText = emptyText;

        Event.observe(this.form,  'submit', this.submit.bind(this));
        Event.observe(this.field, 'focus', this.focus.bind(this));
        Event.observe(this.field, 'blur', this.blur.bind(this));
        Event.observe(this.field, 'onkeypress', this.onkeypress.bind(this));
        this.blur();
    },

    submit : function(event){
        if (this.field.value == this.emptyText || this.field.value == ''){
            Event.stop(event);
            return false;
        }
        return true;
    },

    focus : function(event){
        if(this.field.value==this.emptyText){
            this.field.value='';
        }

    },

    blur : function(event){
        if(this.field.value==''){
            this.field.value=this.emptyText;
        }
    },

    onkeypress : function(event){
        if(this.field.value==''){
            this.field.value=this.emptyText;
        }
        $('_quicksuggest_id').value = 0; 
    },
    initAutocomplete : function(url, destinationElement){
        new Ajax.Autocompleter(
            this.field,
            destinationElement,
            url,
            {
                paramName: this.field.name,
                minChars: 2,
                updateElement: this._selectAutocompleteItem.bind(this),
                onShow : function(element, update) {
            		$('_quicksuggest_id').value = 0; 
                    if(!update.style.position || update.style.position=='absolute') {
                        update.style.position = 'absolute';
                        Position.clone(element, update, {
                            setHeight: false, 
                            offsetTop: element.offsetHeight
                        });
                    }
                    Effect.Appear(update,{duration:0});
                }

            }
        );
    },

    _selectAutocompleteItem : function(element){
    	$('_quicksuggest_id').value = 0;
        if(element.title){
            this.field.value = element.title;
            $('_quicksuggest_id').value = element.id;
        }
        //this.form.submit();
    }
}


function addCart()
{
	new Ajax.Updater('quick.card','<?php echo $this->getAddUrl();?>',{parameters:{id: $('_quicksuggest_id').value}});
	$('quicksearch').value = '';
}

</script>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="quick_form" action="#" method="post">

<fieldset class="form-search">
    <legend>Search Site</legend>
    <label for="search"></label>

    <input id="quicksearch" type="text" class="input-text" name="quicksuggest" value="" />
    <input type="hidden" name="quicksuggest_id" id="_quicksuggest_id" value="0" />
    <button type="button" class="button" id="bt_addCart" onclick="addCart();">
		<span>Add</span>
	</button>
    <div id="quick_autocomplete" class="search-autocomplete" style="display:none;"></div>
    
    <script type="text/javascript">
    //<![CDATA[
        var searchForm = new Quick.searchForm('quick_form', 'quicksearch', '');
        searchForm.initAutocomplete('<?php echo $this->getSuggestUrl();?>', 'quick_autocomplete');
    //]]>
    </script>

</fieldset>

</form>


<div id="quick.card">
	<?php echo $this->getCart();?>
</div>
