<?php

/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>

<!--Sprungziel Tastatursteuerung -->
<div id="jumptarget<?php echo $this->getNameInLayout();?>">
	<div class="page-title">
		<h2><?php echo $this->__('Shopping Cart') ?></h2>
	</div>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml()?>
<?php echo $this->getChildHtml('form_before') ?>
<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
	<?php echo $this->getBlockHtml('formkey'); ?>
	<table style="border:0;" id="shopping-cart-table" class="data-table box-table shopping-cart">
		<col width="40" />
		<col width="75" />
		<col />
		<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    		<col width="1" />
		<?php endif ?>
		<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		    <col width="80" />
		<?php endif; ?>
		<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		    <col width="80" />
		<?php endif; ?>
		    <col width="1" />
		<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		    <col width="80" />
		<?php endif; ?>
		<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		    <col width="80" />
		<?php endif; ?>
		<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
	    <thead>
				<tr>
					<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Remove') ?></th>
					<th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
					<th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Name') ?></th>
	            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
	            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Move to Wishlist') ?></th>
	            <?php endif ?>
	            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Unit Price') ?></th>
					<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
					<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
				</tr>
	        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
	        <tr>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
					<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
				</tr>
	        <?php endif; ?>
	    </thead>
		<tbody>
		    <?php foreach($this->getItems() as $_item): ?>
		        <?php echo $this->getItemHtml($_item)?>
		    <?php endforeach ?>
		</tbody>
	</table>
	<div class="buttons-set-shopping-cart">
		<a href="<?php echo $this->getDeleteAllUrl(); ?>" class="button">
			<span><?php echo $this->__('Delete All Items') ?></span>
		</a>
	  <?php if($this->getContinueShoppingUrl()): ?>
	   	<a href="<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>" class="button">
	   		<span><?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?></span>
	   	</a>
	  <?php endif; ?>
		<button class="button" type="submit"> <span><?php echo $this->__('Update Shopping Cart') ?></span></button>
	</div>

	<script type="text/javascript">decorateTable('shopping-cart-table');</script>
</form>

<div class="shopping-cart-collaterals">
	<div class="col2-set">
        <?php echo $this->getChildHtml('crosssell')?>
        <?php if (!$this->getIsVirtual()): ?>
	        <div class="col-1 block">
				<div class="block-title">
					<h3><?php echo $this->__('Shipping cost information')?></h3>
				</div>
				<div class="block-content">
	                <?php echo $this->getChildHtml('shipping');?>
	                <a href="<?php echo $this->getUrl('lieferung') ?>"><?php echo $this->__('Click here to get the shipping cost information');?></a>
				</div>
			</div>
        <?php endif; ?>

        <div class="col-2">
			<div class="shopping-cart-totals">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php echo $this->getChildHtml('methods')?>
            </div>
            <?php echo $this->getChildHtml('coupon')?>
        </div>
	</div>
</div>
<div class="clear"></div>

