<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2015 X.commerce, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$_hidePrice = false;
if (Mage::helper('core')->isModuleEnabled('Egovs_B2b')) {
    $_hidePrice = Mage::helper('egovs_b2b')->hidePrice();
}

$_isLoggedIn = false;
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
    $_isLoggedIn = true;
}

?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = Mage::helper('core')->quoteEscape($this->__('Add to Cart')); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
    <?php if(!$_isLoggedIn): ?>
        <button type="button"
                title="<?php echo $this->quoteEscape($this->__('Login')) ?>"
                class="button btn-cart"
                onclick="setLocation('<?php echo Mage::getBaseUrl(); ?>customer/account/login/')">
            <span>
                <?php echo $this->__('Login') ?>
            </span>
        </button>
    <?php else: ?>
        <?php if(!$_hidePrice): ?>
            <?php if(!$_product->isGrouped()): ?>
                <div class="qty-wrapper">
                    <label for="qty"><?php echo $this->__('Qty:') ?></label>
                    <input type="tel" pattern="\d*" name="qty" id="qty" maxlength="12" value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
                </div>
            <?php endif; ?>
            <div class="add-to-cart-buttons">
                <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)">
                    <span class="egov-cart">
                        <span class="default-font">
                            <?php echo $buttonTitle ?>
                        </span>
                    </span>
                </button>
                <?php echo $this->getChildHtml('', true, true) ?>
            </div>
        <?php else: ?>
            <button type="button"
                    title="<?php echo $this->quoteEscape($this->__('Send request')) ?>"
                    class="button btn-cart"
                    onclick="setLocation('<?php echo Mage::getBaseUrl(); ?>contacts/')">
                <span>
                    <?php echo $this->__('Send request') ?>
                </span>
            </button>
        <?php endif; ?>
    <?php endif; ?>
    </div>
<?php endif; ?>
