<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

/* @var $this Mage_Catalog_Block_Product_View_Media */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="product-image product-image-zoom">
    <div class="product-image-gallery">
        <img id="image-main"
             class="gallery-image visible"
             src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />

        <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
            <?php if ($this->isGalleryImageVisible($_image)): ?>
            <img id="image-<?php echo $i; ?>"
                 class="gallery-image"
                 src="<?php echo $this->getGalleryImageUrl($_image); ?>"
                 data-zoom-image="<?php echo  $this->getGalleryImageUrl($_image); ?>" />
            <?php endif; ?>
        <?php $i++; endforeach; ?>
    </div>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul class="product-image-thumbs">
    <?php
      $js_url      = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);
      $media_url   = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
      $types_flash = array('flv', 'avi');
      $types_html5 = array('ogg', 'mp4', 'webm', 'wav', 'ogv', 'oga', 'm4v', 'm4a');
      $i = 0;

      $thumb_width  = 300;  // Breite des Vorschaubildes für Videos
      $thumb_height = 200;  // Höhe des Vorschaubildes für Video
      $pre_image    = 75;   // Größe des Vorschaubildes für normale Bilder

      foreach ($this->getGalleryImages() as $_image): ?>
        <?php if ($this->isGalleryImageVisible($_image)): ?>
        <?php
            if ( !strlen($image_thumb) ) {
                $image_thumb = $this->helper('catalog/image')->init(
                                   $this->getProduct(),
                                   'thumbnail',
                                   $_image->getFile()
                               )->resize($pre_image);
            }

            if ( !strlen($image_path) ) {
                $image_path  = $this->helper('catalog/image')->init(
                                   $this->getProduct(),
                                   'thumbnail',
                                   $_image->getFile()
                               )->resize($thumb_width, $thumb_height);
            }

            $file_name  = $_image->getFile();
            $full_url   = $media_url . "catalog/product" . $file_name;
            $file_label = $this->escapeHtml($_image->getLabel());
            $file_info  = pathinfo($file_name);
        ?>
        <li>
            <?php
                if ( in_array($file_info['extension'], $types_flash) ):
            ?>
            <object id="egov_flash_video_<?php echo $i; ?>"
                    type="application/x-shockwave-flash"
                    data="<?php echo $js_url; ?>flash/player_flv.swf"
                    class="egov-product-flash"
                    width="<?php echo $thumb_width; ?>"
                    height="<?php echo $thumb_height; ?>">
                <param name="movie" value="<?php echo $js_url; ?>flash/player_flv.swf" />
                <param name="wmode" value="transparent" />
                <param name="quality" value="high" />
                <param name="allowFullScreen" value="true" />
                <param name="allowScriptAccess" value="always" />
                <param name="flashvars" value="flv=<?php echo $full_url; ?>" />
            </object>
            <?php elseif ( in_array($file_info['extension'], $types_html5) ): ?>
            <video id="egov_product_video_<?php echo $i; ?>"
                   width="<?php echo $thumb_width; ?>"
                   height="<?php echo $thumb_height; ?>"
                   class="egov-product-video"
                   controls="true"
                   autobuffer="true"
                   preload="auto"
                   poster="<?php echo $image_path; ?>">
                <source src="<?php echo $full_url; ?>"
                        type='video/<?php echo $file_info['extension']; ?>' />
            </video>
            <?php else: ?>
            <a class="thumb-link egov-product-image" href="javascript:void(0);" title="<?php echo $file_label ?>" data-image-index="<?php echo $i; ?>">
                <img src="<?php echo $image_thumb; ?>" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
            </a>
            <?php endif; ?>
        </li>
        <?php endif; ?>
    <?php $i++; endforeach; ?>
    </ul>
</div>
<?php endif; ?>

<?php echo $this->getChildHtml('after'); ?>
