<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 - 2019 B3 IT System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
$_product = $this->getProduct();
$_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrlWithCustomParams($_product, array(), false);
$_helper = $this->helper('catalog/output');
$_productName = urlencode(trim($_helper->productAttribute($_product, $_product->getName(), 'name')));
$_productImageUrl = urlencode(trim($this->helper('catalog/image')->init($_product, 'image')));
$_productUrl = urlencode(trim($_product->getProductUrl()));
$_u = 'p[url]=' . $_productUrl . '&p[images][0]=' . $_productImageUrl . '&p[title]=' . $_productName . '&p[summary]=' . urlencode(trim($_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description')));
?>

<ul class="sharing-links">
  <?php if ($this->canEmailToFriend()): ?>
    <li id="send-friend">
        <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>" class="link-email-friend" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email to a Friend')) ?>">
            <?php echo $this->__('Email to a Friend') ?>
        </a>
    </li>
  <?php endif; ?>
    <li id="send-facebook">
        <a href="<?php echo 'http://www.facebook.com/sharer.php?s=100&' . $_u; ?>" target="_blank" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share on Facebook')) ?>" class="link-facebook">
            <?php echo $this->__('Share Facebook') ?>
        </a>
    </li>
    <li id="send-twitter">
        <a href="<?php echo 'http://twitter.com/home?status=' . $_productName . '+' . $_productUrl; ?>" target="_blank" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share on Twitter')) ?>" class="link-twitter">
            <?php echo $this->__('Share on Twitter') ?>
        </a>
    </li>
</ul>

