<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2018 B3-IT Systeme GmbH
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
$_order = $this->getOrder();

$_thStyle = 'border:1px solid #bebcb7; padding:5px 9px 6px 9px; background-color:#d9e5ee;';
?>

<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <?php $_itemCount = count($_items); ?>
    <tr>
        <td>
            <br />
            <table class="items" style="width:100%; border-collapse:collapse;">
                <thead>
                    <tr>
                        <th class="cell-name" style="<?php echo $_thStyle; ?>">
                            <?php if($_itemCount > 1): ?>
                                <?php echo $this->__('Items in your order'); ?>
                            <?php else: ?>
                                <?php echo $this->__('Item in your order'); ?>
                            <?php endif; ?>
                        </th>
                        <th class="cell-name align-center" style="<?php echo $_thStyle; ?>">
                            <?php echo $this->__('Sku'); ?>
                        </th>
                        <th class="cell-name align-center" style="<?php echo $_thStyle; ?>">
                            <?php echo $this->__('Qty'); ?>
                        </th>
                        <th class="cell-name align-right" style="<?php echo $_thStyle; ?>">
                            <?php echo $this->__('Price'); ?>
                        </th>
                    </tr>
                </thead>
                <tbody style="border:1px solid #bebcb7; border-top-width:0;">
                 <?php $i=0; foreach ($_order->getAllItems() as $_item): ?>
                  <?php if($_item->getParentItem()) continue; else $i++; ?>
                   <?php echo $this->getItemHtml($_item) ?>
                 <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td align="right" colspan="4">
                            <?php echo $this->getChildHtml('order_totals') ?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </td>
    </tr>
    <?php if ($this->helper('giftmessage/message')->isMessagesAvailable('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
    <tr>
        <td>
            <br />
            <table style="width:100%; border:1px solid #EAEAEA;">
                <thead>
                    <tr>
                        <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><strong><?php echo $this->__('Gift Message for this Order') ?></strong></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="4" align="left" style="padding:3px 9px">
                        <strong><?php echo $this->__('From:'); ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?php echo $this->__('To:'); ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?php echo $this->__('Message:'); ?></strong><br /> <?php echo $this->escapeHtml($_giftMessage->getMessage()) ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </td>
    </tr>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
