<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="col2-set">
    <div class="col-1">
        <div class="box egov-float-left">
            <div class="box-title">
                <h3>
                    <?php echo $this->__('Default Billing Address') ?>
                </h3>
            </div>
            <div class="box-content">
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box egov-float-right">
            <div class="box-title">
                <h3>
                    <?php echo $this->__('Default Shipping Address') ?>
                </h3>
            </div>
            <div class="box-content">
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
        </div>
    </div>
</div>
