<?php
/**
 * @category    design
 * @package     egov_default
 * @copyright   Copyright (c) 2015 B3-it System GmbH (https://www.b3-it.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Shoping cart sidebar
 *
 * @var Mage_Checkout_Block_Cart_Minicart $this
 */
?>

<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
    $_cartQty = 0;
}
?>
<div id="minicart-error-message" class="minicart-message"></div>
<div id="minicart-success-message" class="minicart-message"></div>

<div class="minicart-wrapper">

    <p class="block-subtitle">
        <?php echo $this->__('Recently added item(s)') ?>
        <a class="close skip-link-close" href="#" title="<?php echo $this->quoteEscape($this->__('Close')); ?>">&times;</a>
    </p>

    <?php $_items = $this->getRecentItems() ?>
    <?php $countItems = count($_items); ?>
    <?php if($countItems): ?>
        <div>
            <ul id="cart-sidebar" class="mini-products-list">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <script type="text/javascript">
            truncateOptions();
            decorateList('cart-sidebar', 'none-recursive');
            $j('document').ready(function() {
                var minicartOptions  = {
                    formKey:           "<?php echo $this->getFormKey();?>"
                }
                var Mini = new Minicart(minicartOptions);
                Mini.init();
            });
        </script>

        <div id="minicart-widgets">
            <?php echo $this->getChildHtml('cart_promotion') ?>
        </div>
        <div class="block-content">
            <p class="subtotal">
            <?php if ($this->canApplyMsrp()): ?>
                <span class="map-cart-sidebar-total">
                    <?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?>
                </span>
                <?php else: ?>
                <span class="label">
                    <?php echo $this->__('Cart Subtotal:') ?>
                </span>
                <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                <?php endif; ?>
            <?php endif; ?>
            </p>
        </div>


        <div class="minicart-actions">
            <button class="button egov-float-left"
                    onclick="window.open('<?php echo $this->getUrl('checkout/cart', array('_secure' => $this->getRequest()->isSecure())); ?>','_self');">
                <?php echo $this->__('View Shopping Cart'); ?>
            </button>
        <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
         <?php if($this->isEventRequest()):?>
            <button class="button egov-float-right"
                    onclick="window.open('<?php echo $this->getRegistrationUrl()?>','_self');"
                    title="<?php echo $this->quoteEscape($this->__('Proceed to application')) ?>">
                <?php echo $this->__('Proceed to application') ?>
            </button>
         <?php else:?>
         	<button class="button egov-float-right"
                    onclick="window.open('<?php echo $this->getCheckoutUrl() ?>','_self');"
                    title="<?php echo $this->quoteEscape($this->__('Checkout')) ?>">
                <?php echo $this->__('Checkout') ?>
            </button>
         <?php endif;?>
        <?php endif ?>
               <!--
                <ul class="checkout-types minicart">
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <li>
                    </li>
                </ul>
                -->
        </div>

    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>

    <?php endif ?>
</div>
