<?php
/**
 * @category   design_blank
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Review Order') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" >
<fieldset class="multiple-checkout">
    <div class="col2-set">
        <h3><?php echo $this->__('Billing Information') ?></h3>
        <div class="col-1">
            <?php $_address=$this->getBillingAddress() ?>
            <h4><?php echo $this->__('Billing Address') ?> <span class="separator">|</span> <a href="<?php echo $this->getAddressesEditUrl() ?>"><?php echo $this->__('Change') ?></a></h4>
            <address>
                <?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
            </address>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Payment Method') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditBillingUrl() ?>"><?php echo $this->__('Change') ?></a></h4>
            <input type="hidden" name="payment[cc_number]" value="<?php echo $this->htmlEscape($this->getPayment()->getCcNumber())?>" />
            <input type="hidden" name="payment[cc_cid]" value="<?php echo $this->htmlEscape($this->getPayment()->getCcCid())?>" />
            <?php echo $this->getPaymentHtml() ?>
        </div>
     </div>
     <?php if(!$this->isVirtual()):?>
    <h3><?php echo $this->__('Shipping Information') ?></h3>
    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <?php  $_address = $this->getShippingAddress() ?>
        <div class="col2-set">
        <h4></h4>
            <div class="col-1 narrow">
            <?php if(!$this->isStorePickup()):?>
                <h5><?php echo $this->__('Shipping to') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditShippingUrl() ?>"><?php echo $this->__('Change') ?></a></h5>
                <address>
                    <?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
                </address>
                <?php endif;?>
                <h5><?php echo $this->__('Shipping Method') ?> <span class="separator">|</span> <a href="<?php echo $this->getEditShippingmethodUrl() ?>"><?php echo $this->__('Change') ?></a></h5>
                <?php if($_rate=$this->getShippingAddressRate($_address)): ?>
                <p>
                <?php echo $_rate->getCarrierTitle() ?> (<?php echo $_rate->getMethodTitle() ?>)
                <?php $_excl = $this->getShippingPriceExclTax($_address); ?>
                <?php $_incl = $this->getShippingPriceInclTax($_address); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
                </p>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="col-2 wide">
            
            <table class="data-table" id="checkout-review-table">
			    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
			    <col />
			    <col width="1" />
			    <col width="1" />
			    <col width="1" />
			    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			    <col width="1" />
			    <col width="1" />
			    <?php endif; ?>
			    <thead>
			        <tr>
			            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
			            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
			            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Qty') ?></th>
			            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
			        </tr>
			        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			            <tr>
			                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
			                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
			                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			            </tr>
			        <?php endif; ?>
			    </thead>
			    <?php echo $this->getChildHtml('totals'); ?>
			    <tbody>
			    <?php foreach($this->getItems() as $_item): ?>
			        <?php echo $this->getItemHtml($_item)?>
			    <?php endforeach ?>
			    </tbody>
			</table>
            
            
            
            
            
   </div></div>
	<p><input class="checkbox" type="checkbox" name="sendOrderEmail" value="1"><?php echo $this->__('Please send me a confirmation of this order by e-Mail')?></p>
	<div>
		<?php echo $this->getChildHtml('infotexts'); ?>
	</div>
	<div>
		<?php echo $this->getChildHtml('agreementtexts'); ?>
	</div>
    <?php echo $this->getChildHtml('agreements') ?>
    <div>
    	<?php echo $this->getChildHtml('newsletter') ?>
    </div>
    <p class="grand-total">
        <span style="font-size: 1.1rem;"><?php echo $this->__('Grand Total:') ?></span>
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()) ?>
    </p>
    <div class="buttons-set" id="review-buttons-container">
        <a href="<?php echo $this->getBackUrl() ?>" class="back-link">&laquo; <?php echo $this->__('Back') ?></a>
        <a class="break-link" href="<?php echo $this->getUrl() ?>" class="button"><span><?php echo $this->__('Continue Shopping') ?></span></a>
        <button type="submit" class="button" id="review-button"><span><?php echo $this->__('Place Order') ?></span></button>
        <span id="review-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
  
</fieldset>
</form>

