<div id="list" >
<script >
	function selectStation(id)
	{	
			$$('select#stationenListe option').each(function(o) {
				  if(o.readAttribute('value') == id) { 
				    o.selected = true;
				    throw $break; 
				  }
				});
	}
</script>
<select id="stationenListe" id="station">
<?php foreach($this->getStationsList() as $station){?> 
<option value="<?php echo $station->getId()?>"><?php echo $station->getName()?></option> 			
<?php }?>
</select>
</div>
