<?php
/**
 * @category   design
 * @package    Egov
 * @copyright  Copyright (c) 2018 B3 IT Systeme GmbH (http://www.b3-it.de)
 *
 *
 * @var $this Egovs_Checkout_Block_Multipage_Total_Tax
 * @see Mage_Sales_Model_Quote_Address_Total
 */
?>
<?php
    $_value = $this->getTotal()->getValue();
    $_style = $this->getTotal()->getStyle();
    
    $_colSpan = $this->getColspan();
    
    // ersatz für $this->helper('tax')->displayFullSummary()
    $_showFullSummary = Mage::getStoreConfig('tax/cart_display/full_summary');
    $_showZeroTax     = Mage::getStoreConfig('tax/cart_display/zero_tax');
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ( ($_showFullSummary AND $_value!=0)  OR ($_value == 0 AND $_showZeroTax) ): ?>
	<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
        <tr class="tax-details tax-details-<?php echo $taxIter; ?>">
            <td class="a-right" style="<?php echo $_style ?>" colspan="<?php echo $_colSpan; ?>">
                <?php echo $rate['title']; ?> <?php if ($rate['percent']): ?>(<?php echo $rate['percent']; ?>%)<?php endif; ?>
                <br />
            </td>
            <?php if ($isFirst): ?>
            <td rowspan="<?php echo count($rates); ?>" class="a-right" style="<?php echo $_style ?>">
                <?php echo $this->helper('checkout')->formatPrice($amount); ?>
            </td>
            <?php endif; ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>

        <?php $weees = $this->getAllWeee(); ?>

        <?php if( is_array($weees) && count($weees) ): ?>
            <?php foreach ($weees as $weeeTitle => $weeeAmount): ?>
            <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                <td class="a-right" style="<?php echo $_style ?>" colspan="<?php echo $_colSpan; ?>">
                    <?php echo $this->escapeHtml($weeeTitle); ?>
                    <br />
                </td>
                <td style="<?php echo $_style ?>" class="a-right" rowspan="1">
                    <?php echo $this->helper('checkout')->formatPrice($weeeAmount); ?>
                </td>
            </tr>
            <?php endforeach; ?>
        <?php endif; ?>

    <?php endforeach; ?>
<?php endif;?>

<tr id="overview-tax" <?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?> class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')"<?php endif; ?>>
    <td style="<?php echo $_style ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php if ($_showFullSummary): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif;?>
    </td>
    <td style="<?php echo $_style ?>" class="a-right"><?php echo $this->helper('checkout')->formatPrice($_value) ?></td>
</tr>