<?php
/**
 * @category   design_blank
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h2><?php echo $this->__('Your order has been received') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h3><?php echo $this->__('Your order # is:').' '. $this->getOrderId() ?></h3>
<h3><?php echo $this->getKassenzeichen()?></h3>
<fieldset class="multiple-checkout">
    <div class="col2-set">
        <h3><?php echo $this->__('Billing Information') ?></h3>
        <div class="col-1">
            <?php $_address=$this->getBillingAddress() ?>
            <h4><?php echo $this->__('Billing Address') ?></h4>
            <address>
                <?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
            </address>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Payment Method') ?> </h4>
            <?php echo $this->getPaymentHtml() ?>
        </div>
     </div>
     <?php if(!$this->isVirtual()):?>
    <h3><?php echo $this->__('Shipping Information') ?></h3>
    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <?php  $_address = $this->getShippingAddress() ?>
        <div class="col2-set">
        <h4></h4>
            <div class="col-1 narrow">
                <h5><?php echo $this->__('Shipping to') ?></h5>
                <address>
                    <?php echo Mage::helper('mpcheckout/addressformat')->formatHtml($_address) ?>
                </address>
                <h5><?php echo $this->__('Shipping Method') ?> </h5>
                <?php if($_rate=$this->getShippingAddressRate($_address)): ?>
                <p>
                <?php echo $_rate->getCarrierTitle() ?> (<?php echo $_rate->getMethodTitle() ?>)
                <?php $_excl = $this->getShippingPriceExclTax($_address); ?>
                <?php $_incl = $this->getShippingPriceInclTax($_address); ?>

                <?php echo $_excl; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>
                </p>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="col-2 wide">
            
            <table class="data-table" id="checkout-review-table">
			    <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
			    <col />
			    <col width="1" />
			    <col width="1" />
			    <col width="1" />
			    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			    <col width="1" />
			    <col width="1" />
			    <?php endif; ?>
			    <thead>
			        <tr>
			            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
			            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
			            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Qty') ?></th>
			            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
			        </tr>
			        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
			            <tr>
			                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
			                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
			                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
			            </tr>
			        <?php endif; ?>
			    </thead>
			    <?php echo $this->getChildHtml('totals'); ?>
			    <tbody>
			    <?php foreach($this->getItems() as $_item): ?>
			        <?php echo $this->getItemHtml($_item)?>
			    <?php endforeach ?>
			    </tbody>
			</table>
            
            
            
            
            
   </div></div>
	
    

</fieldset>

<div class="buttons-set">
<a href="<?php echo $this->getUrl() ?>" class="button"><span><?php echo $this->__('Continue Shopping') ?></span></a>
</div>
