<?php
/**
 * Widget für Kreditkartenlogos
 *
 * @category	Egovs
 * @package		dwd_default
 * @author 		Frank Rochlitzer <f.rochlitzer@edv-beratung-hempel.de>
 * @copyright	Copyright (c) 2013 EDV Beratung Hempel
 * @license		http://sid.sachsen.de OpenSource@SID.SACHSEN.DE
 */
/**
 * Credit Card Logos Widget
 *
 * @see Egovs_Paymentbase_Block_Widget_Creditcardlogos
 */
 
 /* @var $this Egovs_Paymentbase_Block_Widget_Creditcardlogos */

$_placeHolder = '%payLogo%';
$_blockTitle  = $this->escapeHtml($this->getTitle());

if ( strpos($_blockTitle, $_placeHolder) !== false ) {
	$_blockTitle = str_replace($_placeHolder, '<span id="pay-logo-before" class="pay-logo-before"><span id="pay-logo-two"></span></span>', $_blockTitle);
}
?>
<div class="block widget-credit-cards">
	<div class="block-title">
		<h4><?php echo $_blockTitle; ?></h4>
	</div>
	<div class="block-content">
		<div id="widget_credit_cards" class="widget_credit_cards">
			<img id="widget_logo_master_card" title="MasterCard" src="<?php echo $this->getSkinUrl('credit_cards/mc.png') ?>" alt="MasterCard" />
			<img id="widget_logo_visa" title="VISA" src="<?php echo $this->getSkinUrl('credit_cards/visa.png') ?>" alt="VISA" />
		</div>
	</div>
</div>